### ISSUE TITLE
Mobile Safari not display caret/cursor.

### ISSUE THREAD

**Issue by gotnull** [Mottie/Keyboard#105]
We have an issue where we've implemented a custom keyboard within a Phonegap application.

First of all we've noticed that the virtual keyboard on this URL when accessed via Mobile Safari does not display a blinking cursor:

http://mottie.github.com/Keyboard/mobile.html

Is this a bug? This is happening with our Phonegap application and we absolutely require the caret/cursor to appear within the input field and require the ability to tap on the input field to place the cursor inbetween words.

This is happening on devices with a target deployment of 4.3 and devices running firmware 5.1.1.

NOTE: We don't want the native keyboard displaying at all so clicking inside the input field is out of the question as this initiates the native keyboard if we don't set the input field to be readonly.

Any help would be greatly appreciated as this has become a blocker for us and we are awaiting a fix before we submit to the AppStore for review.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.
