### ISSUE TITLE
attach sound to buttons?

### ISSUE THREAD

**Issue by antixian** [Mottie/Keyboard#135]
i have been trying to attach sound to the buttons on the keyboard but have been unsuccessful since it appends to the body and i cant get the jquery code under the button divs on the page. 

i'm trying to add sound to each button similar to this example.
http://css-tricks.com/examples/SoundOnHover/

is it possible? would be really cool if so.
thanks.

**Comment by deniro21** [comment]
Hello. How i can attacj sound on "Shift" or "Caps" buttons? This buttons return false :((

**Comment by Mottie** [comment]
Hi @deniro21!

Hmm, well I guess you could also bind to the keyset change event... so after this snippet of code:

```js
// target ALL keys for clicky time!
kb.$allKeys.on('mousedown.audio', function () {
	// play clicky noise
	clicky.pause();
	clicky.play();
});
```

add this ([demo](http://jsfiddle.net/Mottie/MK947/3882/)):

```js
// target ALL keys for clicky time!
kb.$allKeys.on('mousedown.audio', function () {
	// play clicky noise
	clicky.pause();
	clicky.play();
});
kb.$el.on('keysetChange.audio', function(){
	clicky.pause();
	clicky.play();
});
```

**Comment by deniro21** [comment]
Mottie, thank you very much. I've done a little differently:

    $('#field_for_text').keyboard().on('keyboardChange', function(e, keyboard, el){
            var button_name = keyboard.last.key;
            if( button_name.slice(-4)== "Caps" || button_name.slice(-4)== "hift"  ) {

                var audio = $("#lock_sound")[0];
                audio.pause();
                audio.currentTime = 0;
                audio.play();

            } else{
                var audio = $("#tock_sound")[0];
                audio.pause();
                audio.currentTime = 0;
                audio.play();
            }

       });

**Comment by celimun** [comment]
HI. imfrom argentina ! i have this code....
not working
please help me ! i want to listen to sound . when the mouse is over a animated gif...

i try first with a jpg. and not working. thanksss... celina


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Documento sin título</title>


<img id="u" src="n.jpg" alt="La descripcion de la imagen" />


<audio id="pu">
  <source src="b.mp3"></source>
  <source src="b.ogg"></source>
Your browser isn't invited for super fun audio time.
</audio>



<style type="text/css">
#u {
	position: absolute;
	left: 112px;
	top: 97px;
	width: 127px;
	height: 137px;
	z-index: 1;
}
#u:hover {
  cursor: pointer;
}
</style>










<script language="JavaScript" type="text/JavaScript">
var audio = $("#pu")[0];
$("#u").mouseenter(function() {
  console.log('Hola');
  audio.play();
});
</script>












</head>

<body>
<div id="u"><img src="n.jpg" width="120" height="132" /></div>
</body>
</html>

**Comment by celimun** [comment]
<title>Documento sin título</title>


<img id="u" src="n.jpg" alt="La descripcion de la imagen" />


<audio id="pu">
  <source src="b.mp3"></source>
  <source src="b.ogg"></source>
Your browser isn't invited for super fun audio time.
</audio>



<style type="text/css">
#u {
	position: absolute;
	left: 112px;
	top: 97px;
	width: 127px;
	height: 137px;
	z-index: 1;
}
#u:hover {
  cursor: pointer;
}
</style>










<script language="JavaScript" type="text/JavaScript">
var audio = $("#pu")[0];
$("#u").mouseenter(function() {
  console.log('Hola');
  audio.play();
});
</script>






</head>

<body>
<div id="u"><img src="n.jpg" width="120" height="132" /></div>
</body>
</html>

**Comment by Mottie** [comment]
Hi @celimun!

That really isn't related to the keyboard, but I think all you need to do is:
* Load jQuery

    ```html
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    ```

* Wrap all your code inside a document ready function

    ```js
    $(function(){
        // add your javascript here
    });
    ```

The next time you have a question, please try asking it on [Stackoverflow](http://stackoverflow.com/questions/tagged/javascript).

**Comment by celimun** [comment]
I copy this:
http://codepen.io/anon/pen/GjgamW

because i dont know nothing of java

2016-09-06 20:21 GMT-03:00 celina mundet <celinamundet@gmail.com>:

**Comment by Mottie** [comment]
I think you mean javascript, Java is a different language.

The demo on CodePen works because the javascript is at the bottom of the page, so the document ready function wrapper isn't needed; but it is needed in the code you shared because the script is above the `<body>`.

[Try this demo](https://jsbin.com/qomumu/edit?html,output)... it shows everything you need.
