### ISSUE TITLE
multiple inputs, focus wont fire first time ?

### ISSUE THREAD

**Issue by gabrielbix** [Mottie/Keyboard#138]
The keyboard is opened on an input. if i focus out on another input, the keyboard wont open on the first click, it will open on the second click.

**Comment by DaveJalpan** [comment]
I also facing same issue when i try it from IE 11. Ok in chrome. Please help

**Comment by Mottie** [comment]
Hi @DaveJalpan!

I found the problem, I'll have a fix available very soon.
