### ISSUE TITLE
Double character when using firefox

### ISSUE THREAD

**Issue by anhntbk08** [Mottie/Keyboard#184]
I tested demo page http://mottie.github.io/Keyboard/index.html with touch screen devices ( in here a kiosk and asus utrabook SonicMaster) some time the character is double when touch on every button)

Could you tell me how to fix this
Thank you
Best regards

**Comment by niravjgandhi** [comment]
What about chrome. 
Because I facing the same issue in chrome with input field and virtual keyboard.
Character repeating twice randomly on touch screen not ipad or not mobile.
normal system with touch display still having a same problem
 Please check and let me know if you have some solution to handle this.

**Comment by Mottie** [comment]
Hi @niravjgandhi!

The method to prevent double characters discussed in this issue *should* also work for Chrome. Please let me know if it doesn't.

**Comment by emaunot** [comment]
try to put in about:config (or config file)
dom.keyboardevent.dispatch_during_composition  ->  false

OK for us . No more double char in password or code writing
Defaut value is tru since recent (Quantum ... ) versions

**Comment by vinaysalian** [comment]
Sorry for opening this issue again, We are facing   the double typing issue in firefox, But strange is that we are facing this issue only in popups . Normal firefox window  the touch keyboard  works fine. But on popups it types double. It works fine in Edge browser . Please advise. Thanks in adavnce . Operating system Windows 7 Pro.

**Comment by vinaysalian** [comment]
Sorry for opening this issue again, We are facing the double typing issue in firefox, But strange is that we are facing this issue only in popups . Normal firefox window the touch keyboard works fine. But on popups it types double. It works fine in Edge browser . Please advise. Thanks in adavnce . Operating system Windows 7 Pro.

**Comment by vinaysalian** [comment]
Sorry for opening this issue again, We are facing the double typing issue in firefox, But strange is that we are facing this issue only in popups . Normal firefox window the touch keyboard works fine. But on popups it types double. It works fine in Edge browser . Please advise. Thanks in adavnce . Operating system Windows 7 Pro.
