### ISSUE TITLE
hebrew layout

### ISSUE THREAD

**Issue by cristianaivan** [Mottie/Keyboard#185]
When using European characters (punctuation characters, brackets, parentheses, etc ) from default Hebrew keyboard the text is written from left to right and not for right to left. In case that an European character is written in the middle of text, initial it is wrong displayed at the end of text (written from left to right) but when selecting another Hebrew character, it will be moved on the left side (as any Hebrew character).  
Also the Backspace key doesn't work correctly if the text contains Hebrew and European characters.

It is possible to fix these problems?

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.
