### ISSUE TITLE
the virtual keyboard renders slowly because of the hardware, and how can I accelerate it?

### ISSUE THREAD

**Issue by webgldawn** [Mottie/Keyboard#217]
a text box binds the keyboard event,when focusing on the text box, the responsing time is very long. I think because of the allocation of my computer hardware is low, the rendering of virtual keyboard is slow. Now I want to konw that, could I render the virtual keyboard in the initialization of the page,not when focusing on the text box? and how can i do it?
thanks!

**Comment by pixelfreak** [comment]
Hi @Mottie 

My use case is somewhat different and I'm wondering if there is a workaround.

I have multiple inputs and I want the keyboard to always be visible even if the focus is no longer on the inputs. If I use alwaysOpen or stayOpen, I'll see multiple keyboards.

Is this doable?

Thanks!

**Comment by Mottie** [comment]
Hi @pixelfreak!

The way the plugin is set up, it makes an instance of the keyboard for each input/textarea. So, you can't attach one keyboard to multiple elements.

What might work is if you stack the keyboard so it looks like there is only one.

**Comment by pixelfreak** [comment]
I've stacked them and it works fine, the only thing missing is when focus is gone from any of the textbox, the keyboard disappears. I guess it's a limitation I'll have to deal with. Thanks

**Comment by Mottie** [comment]
It should not disappear when `alwaysOpen` is set.
