### ISSUE TITLE
Textarea jumps around

### ISSUE THREAD

**Issue by jasonfreed** [Mottie/Keyboard#23]
Open keyboard to show a textarea (I tested with the "Alphabetical" item from the demo:  http://mottie.github.com/Keyboard/)

Paste in the text below and then start typing after you paste.  You'll notice that the box scrolls/jumps around as you type.

Sample text:
The arrival of the super-dreadnought is commonly believed to have started with the British Orion class. What made them 'super' was the unprecedented 2,000-ton jump in displacement

*I've verified this on Firefox 6 and Chrome 14.*

**Comment by Mottie** [comment]
Hey @jasonfreed!

Sorry for taking so long to fix this.. it took quite a bit of code to make this behave, but I think I got it working for the most part. There are a few minor annoyances that I may work on fixing the future.

Anyway, you can now paste a long string into either a textarea or input and click to position the caret. It will come into view when you start typing (virtually or physically) .

The biggest change is to the input... paste a long string into the "locked" [keyboard demo](http://mottie.github.io/Keyboard/)... then use the virtual keyboard arrow keys to move the caret. A new option `scrollAdjustment` allows you to tweak how far the caret stays from the edge of the input while scrolling. Set this option to `"center"` to center it.

The annoyances I mentioned is in the input. If you mouse click to move the caret, then start typing or use the arrow keys to move the caret, the scroll position jumps to where it would be if you were scrolling right or left.

Anyway, other than that, I'm pretty happy with this fix - other than adding a bunch of lines of code to the core :wink:
