### ISSUE TITLE
Close/hide keyboard when input no longer on focus (iFrame)

### ISSUE THREAD

**Issue by shodaburp** [Mottie/Keyboard#232]
Hi Mottie,

I've been trying to figure out how to close the keyboard when the input field is no longer on focus. The thing is that the input is actually located inside an iFrame. Clicking anywhere outside the iFrame will close it but not when I click anywhere within the iFrame area. 

Switching multiple times between the different inputs inside the iFrame doesn't seem to bring up the right keyboard either. To test this, click the fields in this order: Username > Password > Username. At the end of the third sequence, the keyboard will still be stuck on Password even though Username is on focus.

Here's the URL to the test site: http://dev.shodaburp.com/kiosk/

Please kindly help to solve the above issues. Thank you.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.
