### ISSUE TITLE
The key press event can be seen in IE6,7 & 8 but not in IE9, firefox. Why?

### ISSUE THREAD

**Issue by RashmiSR** [Mottie/Keyboard#236]
Hi Mottie,

The look and feel of virtual keyboard in IE6,7 and 8 is different from IE9 and other browsers. The visual feedback on keypress is highlighted in IE6,7&8 but not in IE9, chrome, firefox. This means that in IE6,7 and 8, when a key is pressed, the key press event can be seen i.e. the button goes in and comes out. So the user comes to know which key is pressed. But the same is not the case in IE9, Chrome and firefox. Is it a browser behaviour?  Please help me to remove or disable visual feedback on keypress in affected browsers?Please help me to achieve the same behaviour as in IE9

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved since older versions of IE are barely in use now, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.
