### ISSUE TITLE
Google Maps Places won't update on .keyboard() input

### ISSUE THREAD

**Issue by carlo-m** [Mottie/Keyboard#242]
Hi Mottie,

I'm building an app that includes Google Maps functionality. I'm using the Places API so autocomplete addresses users are searching. I had it all working perfectly, then I tried to add the .keyboard() and the page doesn't show the results.

Here is a jsfiddle with an example:
http://jsfiddle.net/3jk8e/1/

The element that contains the result is .pac-container, I've done some testing and found that several properties are triggered on various events but can't figure out why the .keyboard() is preventing all these things from happening, or how to connect the two via the change event in .keyboard().

Thanks in advance!

**Comment by lryalamati9** [comment]
Wow! This worked for me. Thanks a lot.
