### ISSUE TITLE
Caret goes to the beginning in at least Firefox 25 when the input value is not empty.

### ISSUE THREAD

**Issue by agamemnus** [Mottie/Keyboard#262]
It should be at the end... At least Firefox 25 through 28, I believe.

You can see it in your calculator example.

There's also a problem with the cursor not being seen at all depending on where you are in the input box and what your CSS transform:scale value is, but that one might be a Firefox problem...

**Comment by jaiminmoslake7020** [comment]
I have the same problem in google chrome ...  issue #330  just see it..!!!

**Comment by Mottie** [comment]
This should be fixed in the master branch along with issue #343.
