### ISSUE TITLE
JQuery Dialog - Modal - Display Errors

### ISSUE THREAD

**Issue by UnclePew** [Mottie/Keyboard#284]
When using multiple keyboards in a jQuery Dialog that is set as modal the popup keyboard has very strange behaviour and only the first popup keyboard will display even when the second keyboard is triggered.

This seems to happen with nearly every style set and if the Dialog is NOT modal then the keyboards behave as expected.

Here is a fiddle demonstrating the strange behaviour: http://jsfiddle.net/cLcJH/9/

**Comment by Mottie** [comment]
Sorry for taking so long to look at this issue... but it seems to be fixed in this latest version. I tried your demo again and it still appeared to have issues.

Then I changed jQuery UI to v1.11.4 (from v1.10.3) and that fixed it: http://jsfiddle.net/Mottie/cLcJH/18/
