### ISSUE TITLE
[ASP.NET] Postback after every click on the keyboard button

### ISSUE THREAD

**Issue by wojtasjz** [Mottie/Keyboard#290]
Hi
I'm using your virtual keyboard (BTW. great job) inside my ASP.NET project, and when I bind it to the textbox with AutoPostBack property set to true, every click on the keyboard button causes postback. Even if it is a 'shift' or 'alt' button. Furthermore, after writing something using the virtual keyboard and change focus, it doesn't fire jquery change event.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.

**Comment by sylkorelan** [comment]
Hi, I've got the same problem. Could you explain me, what should I do with namespaces?
```
.bind('change change.keyboard', function(e){
    console.log(e.type + ' ' + e.namespace);
})
```
returns "change keyboard" for me...

**Comment by Mottie** [comment]
Hi @sylkorelan!

In the latest version, the event names have changed. To bind to a change with the virtual keyboard, use "keyboardChange", to bind to when the original input value changes, use "change".

If you want to rename these events, simply add this script before initializing the plugin:

```js
$.keyboard.events.kbChange = 'keyboardChange';
$.keyboard.events.inputChange = 'change';
```

Namespaces are no longer used on triggered events.
