### ISSUE TITLE
Google Map Search doesn't work with accept or enter

### ISSUE THREAD

**Issue by dp4818** [Mottie/Keyboard#300]
Hi Mottie,
I'm working with Google map, and I found this interesting issue. Thanks.
https://github.com/Mottie/Keyboard/issues/242

it's almost what i need, but after typing i can't search with the virtual keyboard, 
both enter and accept don't work, but it works when i press enter with physical keyboard.

I've tried to set autoAccept to true and enterNavigation to false, but it still doesn't work.
How can I make it work?

Thanks!

**Comment by tauseefjanjua** [comment]
I am having same issue but with dataTables.
The Search is not accepting input from (Mottie virtual keyboard). What is the possible solution?

Here is the fiddle see this issue in actual. 
[fiddle](https://jsfiddle.net/TauseefJanjua/yrv30f94/17/)
I tried to use:

`change: function (e, keyboard, el) {
                    dataTable.search().event.trigger(el, 'focus', {});
                }`

but doesn't work.

Any suggestions?

**Comment by Mottie** [comment]
Hi @tauseefjanjua!

I also put this answer in your SO question](https://stackoverflow.com/q/56182172/145346):

[Demo](https://jsfiddle.net/Mottie/fLv6ywz2/)

```js
$(function() {
  var table = $('#example')
    .on('init.dt', function() {
      $('input[type="search"]').keyboard({
        usePreview: false,
        change: function(e, kb) {
          table.search(kb.el.value).draw();
        }
      });
    })
    .DataTable();
});
```
