### ISSUE TITLE
Adding an arrow to keyboard

### ISSUE THREAD

**Issue by afattahi54** [Mottie/Keyboard#304]
Hi,

Is it possible to configure to show an arrow next to itself and the input, like attached image ?!
I know I can change the keyboard.css file  but as the keyboard position may change, I think it need more than that?! 

![arrow](https://cloud.githubusercontent.com/assets/5003703/4058520/02756416-2dd7-11e4-8e78-6af5ae2112ed.png)

**Comment by Mottie** [comment]
Ok, your long wait is over (I hope :stuck_out_tongue_winking_eye:)

I created a new repository named [Pointy](https://github.com/Mottie/Pointy). You can see the [keyboard specific demo here](http://mottie.github.io/Pointy/docs/keyboard.html). 

There might still be a few kinks still left to work out, but I think it's usable :smiley_cat: 

I would appreciate any feedback!

**Comment by afattahi54** [comment]
Thanks !! It is what what I have been looking for !
