### ISSUE TITLE
Bug in Chrome on Ios

### ISSUE THREAD

**Issue by apod42** [Mottie/Keyboard#312]
Using the latest version of Chrome on the lastest version of mobile Ios (8.0.2), open this page:

http://jsfiddle.net/Em8sG/3024/show/

The page contains three text inputs, with an image next to each input, which triggers the virtual keyboard.  When the page is first loaded, Chrome opens and closes the Ios keyboard three times (takes only a fraction of a second). If I refresh the page this happens again.

This does not happen in Safari, on Ios. Only Chrome. This bug is new with Ios 8, before upgrading the problem was not present.

**Comment by Mottie** [comment]
Hi @apod42!

Actually after reading this again... sorry it's been so long... I think the problem might be that the inputs are getting focused somehow. Maybe try setting the [`initialFocus` option](https://github.com/Mottie/Keyboard/wiki/Usability#initialfocus) to `false` and see if that fixes this issue.

**Comment by apod42** [comment]
Hello,

Thank you! Can no longer reproduce the problem in more recent versions 
of Chrome for Ios / Ios. They did something right at some point in time...

On 15-08-2015 00:20, Rob G wrote:
>
> Hi @apod42 <https://github.com/apod42>!
>
> Actually after reading this again... sorry it's been so long... I 
> think the problem might be that the inputs are getting focused 
> somehow. Maybe try setting the |initialFocus| option 
> <https://github.com/Mottie/Keyboard/wiki/Usability#initialfocus> to 
> |false| and see if that fixes this issue.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Mottie/Keyboard/issues/312#issuecomment-131241542>.
>

gain... sorry it's been so long...
        I think the problem might be that the inputs are getting focused
        somehow. Maybe try setting the <a moz-do-not-send="true"
          href="https://github.com/Mottie/Keyboard/wiki/Usability#initialfocus"><code>initialFocus</code>
          option</a> to <code>false</code> and see if that fixes this
        issue.</p>
      <p
        style="font-size:small;-webkit-text-size-adjust:none;color:#666;">—<br>
        Reply to this email directly or <a moz-do-not-send="true"
href="https://github.com/Mottie/Keyboard/issues/312#issuecomment-131241542">view
          it on GitHub</a>.<img moz-do-not-send="true" alt=""
src="https://github.com/notifications/beacon/AH_kS-I0sDwN9FPKRAxmaEFjEhfDn1FHks5onlM6gaJpZM4Cqyi7.gif"
          height="1" width="1"></p>
      <div itemscope="" itemtype="http://schema.org/EmailMessage">
        <div itemprop="action" itemscope=""
          itemtype="http://schema.org/ViewAction">
          <link itemprop="url"
href="https://github.com/Mottie/Keyboard/issues/312#issuecomment-131241542">
          <meta itemprop="name" content="View Issue">
        </div>
        <meta itemprop="description" content="View this Issue on GitHub">
      </div>
    </blockquote>
    <br>
  </body>
</html>
