### ISSUE TITLE
Question: apply CSS

### ISSUE THREAD

**Issue by apod42** [Mottie/Keyboard#314]
Hello,

Just a question, no bug here :) In the script I have this:

css: {
input: 'css_formular_mesaj'
 }

It allows me to apply my own css class to the active input, overwriting the class applied by jqueryUI.

Can I also style a random div here? For example <div id="my_div" class="my_div_css">

Tried this, does not work:

css: {
input: 'css_formular_mesaj',
my_div: 'my_div_css'
 }

Using css: { } can I add a style only to the active input?

**Comment by Mottie** [comment]
Hey, I added a new option named `autoAcceptOnEsc`. Set it to `true` to force the content to be auto-accepted even if the user presses escape.

I don't think this is a desired behavior, but since that is based on what a developer needs, I decided a new option would be the best solution :grin:

**Comment by apod42** [comment]
Thank you! Will update my code!
