### ISSUE TITLE
pinyin support?

### ISSUE THREAD

**Issue by Nevergonnachange** [Mottie/Keyboard#322]
Hi,

I've set up a website using this keypad. I want the user to be able to use pinyin to input chinise.

Now once i've got the keypad up and runing the following happens:
1) i press a key on my real keyboard windows recognizes that i'm using pinyin
2) i press a key on the virtual keypad windows doesnt recognize that i'm using pinyin 

It appers windows doesnt notice that i pressed a button on the virtual keypad (no keypress gets simulated??). Is there a way i can "let windows know" that a key got pressed? Such as simulating a real keypress?

Thank in advance
Robin

**Comment by Mottie** [comment]
In the last update, I added the converted keyboard layouts from greywyvern.com ([demo](http://mottie.github.io/Keyboard/layouts2.html)) which includes the pinyin keyboard layout.

**Comment by aravindG92** [comment]
Will the pinyin keypad show suggestions similar to this example : https://www.branah.com/chinese

**Comment by Mottie** [comment]
Hi @aravindG92!

It's unlikely since it would require altering the layout dynamically and someone who knows the language to help write an extension to do it.

**Comment by alanzhaonys** [comment]
@Mottie The English keyboard layout worked out great for me. Unfortunately, for any of the Chinese layouts, without having character suggestions of combined of keys, the keyboard is pretty much useless. https://www.branah.com/chinese seems to have a great implementation around this. You're right, extension is needed to convert input methods to Chinese characters and provide suggestions. I really like this keyboard and would try to find solutions if possible.

**Comment by Mottie** [comment]
I don't know Chinese, so it would be difficult and very time consuming for me to build an extension to make character suggestions. Maybe I could build an internal system to make changing keys to provide suggestions easier... I'll put it on my to-do list for version 2.

**Comment by alanzhaonys** [comment]
That would be awesome. I believe there is way to map PinYin to Chinese characters. For example, user types "ABC", a list of suggestions will show on top, also providing scrolling functionality if list gets long. User keeps type, the list will refresh.

Thank you!
