### ISSUE TITLE
Flexible layout

### ISSUE THREAD

**Issue by brandflugan** [Mottie/Keyboard#326]
Hi! I've added motties keyboard to a site that I've made within Tumult Hype and put it within a input-field so it opens up when you click it. The input-field is using flexible layout so it changes position when you drag the side of the browser, however the keyboard is not. Is there a way to make it follow the same path? By the way, thank you Mottie for this awesome plugin

**Comment by brandflugan** [comment]
Ok this is really weird. For some reason, when you load the page and the keyboard pops up, flexible layout is not working with the keyboard. However, if I press the 'accept' button and then pressing mouse 1 in the middle of the keyboard and drag it to the sides, it suddenly changes position slightly and it's now interacting with the flexible layout. It's so hard to find where the problem is for me, any idea?

**Comment by Mottie** [comment]
Hi @brandflugan!

The keyboard uses the jQuery UI Position utility. It is set up to dynamically update the keyboard position when the browser window resizes.

If you're not using the position utility then you'll need to reposition the keyboard yourself.

As for the issue you're describing, I think I could better help if I a demo of the issue were shared. Maybe you can modify [this demo](http://jsfiddle.net/Mottie/MK947/) to duplicated it?

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.
