### ISSUE TITLE
Initializing Keyboard scrolls page to keyboard input location

### ISSUE THREAD

**Issue by vreynolds** [Mottie/Keyboard#327]
When we load a page with a keyboard input that is located at the bottom, the page scrolls to the bottom when keyboard is initialized. Demo: http://jsfiddle.net/MK947/3663/

It seems related to issue #213 . We had to disable line 'base.temp.find('input').caret(3,3)' to prevent this behavior.

**Comment by Mottie** [comment]
Hi @vreynolds!

Thanks for reporting this issue. I will look into it soon!

**Comment by Mottie** [comment]
All fixed :)

**Comment by vreynolds** [comment]
Wow, that was lightning fast! Thank you kindly!
