### ISSUE TITLE
Problem with Bootstrap3 popups

### ISSUE THREAD

**Issue by Miloslawky** [Mottie/Keyboard#329]
When using the virtual keyboard with bootstrap 3 popup when trying to accept or cancel the entered value popup closes. To fix the bug to rename the event. instead Of:
      kbHidden: 'hidden',
need to write:
      kbHidden: 'keyboard_hidden',

ps. Sorry for my bad english. I hope you understand me...

**Comment by Mottie** [comment]
Hi @Miloslawky!

In the newest version, you can change the event names before initializing the plugin ([ref](https://github.com/Mottie/Keyboard/wiki/Methods#event-names)):

```js
$.extend($.keyboard.events, {
    kbHidden: 'keyboard_hidden'
});

$('#keyboard').keyboard();
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.

**Comment by Miloslawky** [comment]
Problem was resolved. Thanks.
