### ISSUE TITLE
Cursor do not get value of previously written text ... =>  base.$preview.caret()  's value evertime remains same event if it has value.  Object {begin: 0, end: 0}

### ISSUE THREAD

**Issue by jaiminmoslake7020** [Mottie/Keyboard#330]
/*! jQuery UI Virtual Keyboard v1.20.0 *//*

base.$preview.val( base.$preview.caret().replace(t2) );   line number 903 ..  base.$preview.caret() do not have replace method as it only have begin end ...  Despite of there is value inside text input ... It stick to the start of the input...  any solution .. It works on some pages but its is not on some pages...  does it have any conflict with any other pluggin ?

![keybo
![keyboard issue 1](https://cloud.githubusercontent.com/assets/4865636/6425236/7306f31a-bf46-11e4-83b3-5c4cdbcfc918.png)
ard issue 1](https://cloud.githubusercontent.com/assets/4865636/6425234/6874b45a-bf46-11e4-84ec-12a49f94564f.png)

**Comment by Mottie** [comment]
Hi @jaiminmoslake7020!

I cannot duplicate this behavior [in the demos](http://mottie.github.io/Keyboard/), in neither Chrome nor Firefox.

Yes, there would be a conflict if another caret positioning plugin were in use, like a mask plugin - I made a comment about this and possibly a better alternative plugin in [issue #201](https://github.com/Mottie/Keyboard/issues/201#issuecomment-71089647).

If that is not the case, what other plugins are being used?

**Comment by jaiminmoslake7020** [comment]
Hello and thanks for  reply @Mottie  and yes i solved the problem by removing MaskPluggin i was using... abnd removed thgose pluggin after reading issue #201
