### ISSUE TITLE
Select() selects all text but when I start typing the data is not replaced.

### ISSUE THREAD

**Issue by drodmaster** [Mottie/Keyboard#331]
Hi,

I have set up the following in my custom keyboard. No preview pane:

$('#keyboard').keyboard({
    usePreview : false,
    visible: function(e, keyboard, el) {
        keyboard.$preview[0].select();
    }
});

The text is selected when I click on the field but when I start to click on the keyboard keys the characters are inserted into the current text instead of overwriting the characters.

This happens in your selectText fiddle: http://jsfiddle.net/Em8sG/3406/

Any ideas how to fix this?

**Comment by Mottie** [comment]
Hi @drodmaster!

I'm not seeing this behavior in Chrome, what browser are you seeing this issue in?

**Comment by Mottie** [comment]
Hmm, never mind, I am seeing that happen in Firefox, but only when `usePreview` is `false`. I'll investigate.

**Comment by drodmaster** [comment]
I'm using IE 10 and it fails when usePreview is true also.

**Comment by Mottie** [comment]
Ok, all fixed in the master branch!

I tried to update [the demo](http://jsfiddle.net/Em8sG/3409/) and point to the raw master file, but it doesn't seem to be updating :crying_cat_face:

**Comment by drodmaster** [comment]
@Mottie,

Thanks for the quick fix. I see that it is working in the demo now (in IE).

**Comment by ageblade** [comment]
If anyone still comes here, this feature didn't work for my because my input was of type 'number'.
Changed it to 'text' and it's working like a charm.

**Comment by Mottie** [comment]
@ageblade that is due to browsers adhering to the [HTML Standards](https://html.spec.whatwg.org/multipage/forms.html#do-not-apply) that establish that only specific input types are allowed to have text selection. See #241 for other problems with caret positioning.
