### ISSUE TITLE
destroying a keyboard while it is visible doesn't fully remove it

### ISSUE THREAD

**Issue by patriciavandermeer** [Mottie/Keyboard#337]
First off: Great plugin, thanks for maintaining it!!

I am making a page where the user can choose if they want to show the keyboard for the inputs or not.  

Basically, they check a checkbox, it sets the keyboards up, they uncheck it, it removes them.

If they have it checked, and click in the input, it shows the keyboard perfectly,  then they check the checkbox (before clicking anywhere else). The keyboard will hide, but when you click back into the input, it comes back.  Once this has happened, the keyboard no longer hides when you click outside of it either.

If they have clicked away from the input, before they uncheck the box,  it behaves as expected and goes away until they re-check the box.

I've created a very basic fiddle of this behaviour:
http://jsfiddle.net/n2yh4ym9/

I've tried adding .close()  and triggering blur on the input before the destroy call with no luck.  

Any ideas on what i'm doing wrong, or how to tweak this to work?
Thanks!

**Comment by Mottie** [comment]
Hi @patriciavandermeer!

The demo is the standard playground demo, but I set up a different one and noticed that this was a problem. I'll work on a fix asap!

**Comment by patriciavandermeer** [comment]
Oh no!

I must have no saved my fork of it properly.  I'm sorry!! I had a little demo all built up (i used the playground as a base and stripped everything out).

Sorry about that, I'll pay more attention to my fiddle saving in the future!

**Comment by Mottie** [comment]
LOL no worries ;)

**Comment by Mottie** [comment]
Ok, it should be all fixed now.

Here is the demo I was working with: http://jsfiddle.net/Mottie/n2yh4ym9/1/ (you might need to give it a few minutes for the demo files to update)

**Comment by Mottie** [comment]
Grr, ok I don't know why the demo isn't working... but I have it working perfectly locally.

**Comment by Mottie** [comment]
Well, it started working when I copied the code exactly from my local demo:

http://jsfiddle.net/Mottie/n2yh4ym9/2/ 

Sooo odd. But now it works :smile_cat:

**Comment by patriciavandermeer** [comment]
awesome thanks for fixing this so quickly!!
