### ISSUE TITLE
how to type without input object id

### ISSUE THREAD

**Issue by yianni** [Mottie/Keyboard#340]
From all the [examples](http://mottie.github.io/Keyboard/index.html) there is always the id of the textbox. Is it possible to use mottie "universally" without passing an associated id for it?

**Comment by Mottie** [comment]
Hi @yianni!

All you had to do was try :wink: 

http://jsfiddle.net/Mottie/egb3a1sk/194/

**Comment by yianni** [comment]
Thanks :).
