### ISSUE TITLE
Question - Display the keyboard

### ISSUE THREAD

**Issue by YanMagale** [Mottie/Keyboard#343]
How to display the keyboard on click the image and keeping the cursor at the end

**Comment by Mottie** [comment]
Hi @YanMagale!

I set up [this demo](http://jsfiddle.net/Mottie/egb3a1sk/219/) to show how to use the [`caretToEnd` option](https://github.com/Mottie/Keyboard/wiki/Usability#carettoend), but it looks like it's not working properly.

I'll see if I can get it fixed by this weekend.

**Comment by YanMagale** [comment]
Hi @Mottie , thanks by feedback.

It's ok, I will look for the end of the implementation.

**Comment by Mottie** [comment]
Ok, the `caretToEnd` option is working again.

The above demo won't work until the next version bump; the updated code is only in the master branch.

**Comment by YanMagale** [comment]
Thanks @Mottie
