### ISSUE TITLE
Question - Changue language

### ISSUE THREAD

**Issue by YanMagale** [Mottie/Keyboard#344]
How to set only the language, without changing layout css

**Comment by Mottie** [comment]
Hi @YanMagale!

It's all in the documentation:

* [Options: language](https://github.com/Mottie/Keyboard/wiki/Options#language)
* [Language](https://github.com/Mottie/Keyboard/wiki/Language)
* [Example/playground](http://jsfiddle.net/Mottie/egb3a1sk/)

There are a minimal amount of actual defined languages in the included layouts, so you may need to define the `jQuery.keyboard.language` yourself.

Or you can skip the language definition and just define only the text of the language in the [`display` option](https://github.com/Mottie/Keyboard/wiki/Language#display---object).

**Comment by HughP** [comment]
If you are looking for a specific language tag from the IANA Language Subtag Registry, you can use this tool: http://r12a.github.io/apps/subtags/

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.
