### ISSUE TITLE
Support for Additional Special Characters in Language Layouts

### ISSUE THREAD

**Issue by dwhiting10** [Mottie/Keyboard#346]
I really like how easy you have made it to add additional language layouts/custom language layouts to your keyboard.  One additional thing that would be nice to have  would be the ability to hold down a key and for several variations of that key to popup to choose from.  

For many keyboard layouts, just having a Alt key to bring up a list of character variations works just fine (although it might be slightly confusing for some users).   Some languages however have multiple variations for multiple character and this gets much more confusing for the users plus not having enough room for the necessary alt and meta keys.  Of course combos can be used but that isn't intuitive for most users and requires having to train users to know how to use this feature.  

Any users who is familiar with soft keyboards on mobile devices expects that pressing and holding down on a key will bring up any variations of the character.  So if you would think about the feasibility of adding this feature that would be great.

Thanks :smile:

**Comment by Mottie** [comment]
Hi @dwhiting10!

Yeah, I know that is a feature of mobile devices. I guess I never got around to adding something like that. It's a good idea for an extension.

My time is presently limited, so I don't know when I'll be able to work on this enhancement.

**Comment by dwhiting10** [comment]
Yep I understand.  This isn't exactly a small change :wink:

**Comment by HughP** [comment]
@dwhiting10 just to be sure, does the image illustrate what you are talking about? or are you talking about how greek has two versions of sigma, one for word final and one for word medial < ς > and < 𝛔 >?�  Arabic also has shape changes for each "letter" depending on the location in the word it occurs. These sorts of alterations should be handled by the font not a keyboard...

![accents-on-iphone](https://cloud.githubusercontent.com/assets/40230/7122388/ee8069ee-e1cf-11e4-846a-21a58672c4c5.png)

**Comment by Mottie** [comment]
I understood it as he wanted the popup seen in the images... I would make it so the buttons inside the popup would be customizable.

**Comment by dwhiting10** [comment]
@HughP  @Mottie Yes just like the above images illustrate is what I was thinking.  Thanks for clarifying.

**Comment by Mottie** [comment]
Ok, it turned out to not be as difficult as I thought... check out the new [altKeysPopup demo](http://mottie.github.io/Keyboard/docs/altkeys-popup.html). Click/press and hold the keys mentioned in the text at the bottom of the page to see the popup.

I hope [the documentation](https://github.com/Mottie/Keyboard/wiki/Setup#altkeyspopup) is clear enough to make it easy to add more alternate keys.

**Comment by dwhiting10** [comment]
Thanks.  This looks really nice.  I will have to play with it and run it through its paces :wink:
