### ISSUE TITLE
AMD Loading with require.js

### ISSUE THREAD

**Issue by danhorner** [Mottie/Keyboard#348]
I haven't been able to load the keyboard plugin via AMD. I'm a little new at this but have encountered a couple of issues: 

- There are two define() blocks in jquery.keyboard.js. One for the keyboard and one for the caret plugin. Keyboard has an undeclared dependency on the caret plugin but is first in the source order.
- Keyboard invokes caret plugin on domReady:
```javascript
    $( function(){
        $keyboard.checkCaretSupport();
    });
```
- But when loading via AMD, the DOM is ready before keyboard.js loads, so the call is not properly deferred.  Changing the order of the two plugins in the source fixes the immediate problem, but the two define()'d modules confuse require.js

Trying to figure out how to postpone dom ready and/or declare the dependency. Thoughts?

**Comment by danhorner** [comment]
Update:  I inlined the jQuery.caret plugin inside the Keyboard module and everthing works great.  This is probably correct for AMD and doesn't break the examples. Change here: 
danhorner@a39f4eabb3deef337b980b1267fdafec013ac65b

**Comment by Mottie** [comment]
Thanks @danhorner!

Hopefully this last update fixes this issue.

**Comment by Mottie** [comment]
Opps, I didn't address the DOM ready event.  I'll take a look at it.

**Comment by danhorner** [comment]
Thank you! Works great. The DOM ready event is incidental. The intent was obviously "Wait until the caret plugin is available", which thanks to the inlining, it now is.

**Comment by danhorner** [comment]
Sorry. My mistake: domReady is too soon if Keyboard is injected later with eg. with setTimeout.

**Comment by Mottie** [comment]
Ok, it should work properly now ;)

**Comment by danhorner** [comment]
Brilliant. Thanks.
