### ISSUE TITLE
Issue with ReactJS

### ISSUE THREAD

**Issue by bazzooka** [Mottie/Keyboard#351]
It copies all the data attributes and the data-reactid that must be uniq. Ouch !

**Comment by Mottie** [comment]
Hi @bazzooka!

I've never used ReactJS so I didn't know about it requiring unique data-attributes. You could set the [`usePreview` option](https://github.com/Mottie/Keyboard/wiki/Usability#usepreview) to `false` to get around this issue.

I will look at the code again and see if there really is a need to clone the original element.

**Comment by bazzooka** [comment]
Perfect workaround with this option.
Thank a lot ! No other library like this one with such options.
