### ISSUE TITLE
Removing characters using Backspace does not work fine

### ISSUE THREAD

**Issue by tiagompb** [Mottie/Keyboard#352]
Hi!
I've a small bug issue in the Virtual Keyboard when I'm trying to remove the characters in a TextArea by clicking in the BackSpace button (Bksp). After loading the page, if I already have some text in the TextArea like "tt", for example, when using the Bksp key the first "t" is not removed. It won't let me.  This only happens using chrome. In IE11 works fine! If the TextArea begins empty like the examples in the page demo, this problem does not happen.

![textarea](https://cloud.githubusercontent.com/assets/12599665/7800808/1c20fba2-0313-11e5-9b84-3aeafe3ac27e.PNG)

I've found out that the issue is here (line 1034 - version v1.22.5):

// add combo back
base.$preview.val( $keyboard.caret( base.$preview ).replaceStr(t2) );
val = base.$preview.val();

If I comment these 2 lines, the bug is fixed, but then the accents don't work anymore like é or ã.

Another strange behavior that I found out in this last version is that the usePreview in a TextArea is not working fine. It does not take the initial text to the preview TextArea. It's blank!

![textarea2](https://cloud.githubusercontent.com/assets/12599665/7800809/21b68b40-0313-11e5-8a5b-ee0dd30504c0.PNG)

Sometimes, If I write a new character, the text is written in the beginning of the TextArea and then the initial text appears again. But sometimes it doesn't. The result is that the initial text is lost, which is quite bad... You can replicate this issue in the page demo.

Thank you so much for your support.

Best regards,
Tiago

**Comment by Mottie** [comment]
Hi @tiagompb!

Sorry for not responding earlier. I have confirmed this issue and I'll try to work on it this weekend.
