### ISSUE TITLE
Problem when using destroy method

### ISSUE THREAD

**Issue by jokytam168** [Mottie/Keyboard#358]
Dear Mottie, 
Thank you for your great work, I am very appreciated with this fancy script.

I have a problem, when I call destroy method, I always get from the console
```javascript
Uncaught TypeError: Cannot read property 'el' of null
```
What I want is user click open keyboard, and still could key in normally.
Although it still works as I wish, any suggestion to fix? Here is the html & code I use 
```javascript
<form>
<a id="ekeyboard" href="#">show keyboard</a>
<input type="text" id="txtPassword" name="txtPassword">
</form>

<script>
$("#ekeyboard").on('click',function(){
   $('#txtPassword').keyboard({
      beforeClose: function(event, keyboard, el) {
         keyboard.destroy();
      }
   });
   $('#txtPassword').focus();
});
</script>

```

**Comment by Mottie** [comment]
Hi @jokytam168!

The issue here is that the destroy method shouldn't be called in the `beforeClose` callback. Instead destroy the keyboard in the `hidden` callback.

I did find a problem even when destroying the keyboard in the hidden callback, so I'll provide a fix for that in the master branch.

**Comment by jokytam168** [comment]
Thank you for your quick reply!! Look forward to hearing from you. ^^

**Comment by jokytam168** [comment]
Thank you for your quickly update. All errors fixed!!
