### ISSUE TITLE
add Event Listener

### ISSUE THREAD

**Issue by ExtremelySeriousChicken** [Mottie/Keyboard#359]
Hi, I am trying to trigger a function when a key in the keyboard is pressed. Is there a way to do it?

**Comment by Mottie** [comment]
Hi @ExtremelySeriousChicken!

You can bind to the [`keyboardChange` event](https://github.com/Mottie/Keyboard/wiki/Methods#events) ([demo](http://jsfiddle.net/Mottie/egb3a1sk/459/)) as follows:

```js
$('#keyboard')
    .on('keyboardChange', function(e, keyboard, el){
        console.log('keyboard button pressed = ' + keyboard.last.key);
    })
    .keyboard({
        layout: 'qwerty'
    }) 
    // activate the typing extension
    .addTyping({
        showTyping : true,
        delay      : 50
    });
```

**Comment by ExtremelySeriousChicken** [comment]
@Mottie Hey Mottie. Do you need the addTyping extension?

**Comment by Mottie** [comment]
Nope, it's completely optional. The main reason I use it is because it highlights the keys pressed on the virtual keyboard while typing on the physical keyboard.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.
