### ISSUE TITLE
How to enable inputs only through virtual keyboard??

### ISSUE THREAD

**Issue by AjayPathak009** [Mottie/Keyboard#360]
How to enable inputs only through virtual keyboard??

Currently, I can enter there with both ie my keypad and virtual keypad.

How I can achieve , inputs only from virtual keypad ?

**Comment by Mottie** [comment]
Hi @AjayPathak009!

Set the [`lockInput` option](https://github.com/Mottie/Keyboard/wiki/Usability#lockinput---boolean) to `true`. Essentially it enables the [`readonly` attribute[(https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-readonly) to prevent physical keyboard input.

**Comment by AjayPathak009** [comment]
Thanks Rob.

This helps!!

Regards,
Ajay

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.

**Comment by AjayPathak009** [comment]
Yes Rob.

You can go ahead and close it.
Thanks again for help!!

Regards,
Ajay
