### ISSUE TITLE
Custom function upon input change

### ISSUE THREAD

**Issue by SaeX** [Mottie/Keyboard#364]
Thanks for the great virtual/on-screen keyboard.

I'm struggling though with something I think would be basic.
I'd like to perform a custom action whenever my (non-previewed) input field is changed. Whenever a new character is added, I want my function to be performed.

Initially I thought of using jQuery events (http://api.jquery.com/category/events/), but that won't work since the "change" event is only detected when the input field loses focus. Similarly, `$('#keyboard').on('input', function()` doesn't work.

Then I noticed https://github.com/Mottie/Keyboard/wiki/Methods, which according to the documentation should work for my use case, but it doesn't:

> keyboardChange - Event called with every change in the virtual keyboard input (key clicked or manual input) (changed v1.21.0)

Whenever a change is performed in the input field (either by clicking a character on the virtual keyboard, or on a physical one), nothing happens. I tried other methods such as `initialized` just for testing purposes, and these do work fine (but that's not what I need).

Here's a JSFiddle showing the issue: http://jsfiddle.net/snoodaard/gLvj30d7/1/.

I'm using the latest version v1.23.1.
Any idea what I'm doing wrong? Thanks!

**Comment by Mottie** [comment]
Hi @SaeX!

Sorry, I should have made the documentation more clear... the "keyboardChange" event is an event that is triggered on the input, not a callback function ([demo](http://jsfiddle.net/Mottie/gLvj30d7/2/)):

```js
$('.keyboard')
    .bind('keyboardChange', function (e, keyboard, el) {
        // alert("A key was pressed!");
        console.log("A key was pressed!");
    })
    .keyboard({
        layout: 'custom',
        customLayout: {
            'default': [
                'a z e r t y u i o p {b}',
                'q s d f g h j k l m',
                'w x c v b n - \' {empty}',
                '{space}'
            ]
        },
        autoAccept: 'true',
        usePreview: false,
        alwaysOpen: true
    });
```

**Comment by SaeX** [comment]
Of course... thanks much! Works like a charm.
