### ISSUE TITLE
openOn option set to null does not work in latest version

### ISSUE THREAD

**Issue by andrely** [Mottie/Keyboard#365]
Setting openOn to null in order to not have the keyboard revealed when the input element gets focus does not have any effect in version 1.23.1.

The issue is demonstrated in this jfiddle (not made by me):

http://jsfiddle.net/Mottie/egb3a1sk/219/

Placing focus on the input box shows the keyboard even if openOn is set to null.

The problem is not present in 1.22.6.

Thanks for creating a very useful piece of software :)

Kind regards

André Lynum

**Comment by Mottie** [comment]
Hi @andrely!

Hmm yeah, that is a problem... it looks like the keyboard is being triggered by the mousdown event. I'll have that fixed ASAP!
