### ISSUE TITLE
Custom button width (single, double, ...)

### ISSUE THREAD

**Issue by Letrab** [Mottie/Keyboard#370]
Hi,

Thank you for this awesome plugin!
I will use it for a custom made cash register for a friend of mine.

But I have a question/suggestion:

Is it possible to give an custom layout key a width?
I am trying to make a numeric keyboard layout, with a 0 (zero) as wide as 2 buttons.
I can probably hack this in, but is there an easy way to do this? (Custom css to 'display' mapping table?)

Thanks in advance!
Kind regards.

**Comment by Letrab** [comment]
Found the most easy way myself:

Add in the css:
.ui-keyboard-48 { width: [single width + 2x margin]em; }

As 48 is the Unicode value of the number 0. Easily to add for other buttons this way.

Other suggestion though:
A checkDecimal(); call when performing a backspace or clear operation.
Added this myself and this way, after a clear, it is possible to directly start with a decimal (. ,) action.

Thanks!

**Comment by Mottie** [comment]
Hi @Letrab!

Yes, all virtual keys have a class name of `ui-keyboard-` followed by a unicode value of the *first-letter* of the text (I might need to change this first-letter thing) or action key name ([ref](https://github.com/Mottie/Keyboard/wiki/Theme)).

I see that using the clear key doesn't check the decimal and it isn't checked until after the user begins typing. The backspace works for me. I'll have a patch for the clear key pushed to the master shortly.
