### ISSUE TITLE
There is no way for me to (give you some money|buy you a beer|polish your moped).

### ISSUE THREAD

**Issue by kphretiq** [Mottie/Keyboard#371]
This lib has made our kiosks way more responsive and intelligent. For our requirements it is excellent, and has saved dev time and is almost certainly better than whatever ugly crap I would have come up with. How can I buy you lunch or whatever?

**Comment by Mottie** [comment]
Hi @kphretiq!

LOL, I'm glad you have found the keyboard useful. I am maintaining this library more as a hobby than a job, so I don't really expect donations. If you really feel the need to donate, then I do have a link to paypal on [my blog](http://wowmotty.blogspot.com/). Thanks :smile_cat:

**Comment by kphretiq** [comment]
9R081542HC492712J

You getcherself something nice with that sawbuck.

**Comment by Mottie** [comment]
Thanks!
