### ISSUE TITLE
How to add a plus sign automatically in between 2 keys that were pressed

### ISSUE THREAD

**Issue by RaduMirsk** [Mottie/Keyboard#372]
I am currently trying to use the virtual keyboard for creating commands  like (F3+T or Ctrl+Shift+R). So far if i want to make such a command i need to press F3 key then '+' key and then T key.

Therefore I was trying to use the `api.lastKey` to detect which key was pressed and add the plus sign dynamically in between the keys. I was using the following code

```js
$('#inter').bind('change.keyboard', function (e, api) {
    if (api) {
        key = api.lastKey;
        console.log(key)
    }
});

Or
  $.extend($.keyboard.events, {
        keyboardChange:function () {
                alert('hello');
               } 
    });
```

where #inter is my keyboard but it seems that my breakpoints are not triggered.

**Comment by Mottie** [comment]
Hi @RaduMirsk!

There is a difference between `change` and `keyboardChange`:

## `change` event
* Trigger inherently by the browser when the input/textarea value changes, which only occurs when the keyboard closes.

## `change` callback
  * In the keyboard plugin this callback is executed whenever the virtual keyboard or physical keyboard changes the content of the input while the virtual keyboard is open.

## `keyboardChange` event
  * This is a triggered only event; there is no associated callback.
  * This event is triggered whenever the content changes, whether it be by the physical or virtual keyboard.
  * This event is fired before the `change` callback is executed.

So, whatever it is you want to do, use either the `change` callback or `keyboardChange` event - see [this demo](http://jsfiddle.net/Mottie/egb3a1sk/560/)

I'm still not 100% sure what it is you're wanting to do. There are a few demos on the [Home Wiki page](https://github.com/Mottie/Keyboard/wiki#manipulating-text) that have code which manipulates the keyboard output, like prevents more than 2 decimal places or include units with the input. Maybe those will help?

If you still need help, please elaborate on what you mean by pressing the <kbd>F3</kbd> key? Do you mean the physical keyboard key or a virtual one on the keyboard? What layout are you using? Can you share the initialization code?

**Comment by RaduMirsk** [comment]
Hi @Mottie ,

Thank you for your quick reply and sorry for my lack of details. Fortunate i have already found a solution for my issue that I will present below:

The user can't type at all, he/she must click the keys. Since the keyboard should help them to define the right commands (they will use this commands further in a speech recognition program) all keys must pressed in a special sequence. 

In our software, a right command is must start with a windows key (Shift,Alt,Enter etc) and  a plus sign and then whatever the user wants. 

![firstkey](https://cloud.githubusercontent.com/assets/13481376/8900568/7223ff90-3441-11e5-90a0-0943c8d01c94.JPG)

What i was looking for was basically a way of making their life a bit easier. So instead of pressing the plus sign whenever they would have press a random key, the plus sign should be generated automatically.

![secondkey](https://cloud.githubusercontent.com/assets/13481376/8900602/ceca076c-3441-11e5-8b62-d2d8eef427f4.JPG)

Now how I solved the problem was basically by checking if the input is empty.If so than print out the whatever the key was meant to print. If the input isn't empty than it means I already pressed a key so I will use " $.extend($.keyboard.keyaction" to alter what they keys should print by adding a plus sign front of them.

var toggleKeysIfEmpty = function (kb) {

    var keyAction; $(this).attr("data-action")
    $('.ui-keyboard-button').on('click', function () {
        console.log($(this).attr("data-action"));
    });

    var toggle = kb.$preview.val() === ' ';
  
    var letters = $(".ui-keyboard-keyset-normal").find(".ui-keyboard-button");
    for (var i = 0; i < letters.length; i++) {
        if ($.isNumeric(letters[i].name) && letters[i].name != "70" && letters[i].name != "alt" && letters[i].name != "ctrl" && letters[i].name != "tab" && letters[i].name != "83") {
            $('.ui-keyboard-button[data-value="F"]')
                .toggleClass('disabled', toggle)
                .prop('disabled', toggle);
            $('.ui-keyboard-button[data-value="S"]')
               .toggleClass('disabled', toggle)
               .prop('disabled', toggle);
            $('.ui-keyboard-button[data-action="shift"]')
              .toggleClass('disabled', toggle)
              .prop('disabled', toggle);
            $('.ui-keyboard-button[data-action="cancel"]')
                .toggleClass('disabled', toggle)
                .prop('disabled', toggle);
            $('.ui-keyboard-button[data-action="accept"]')
                .toggleClass('disabled', toggle)
                .prop('disabled', toggle);
            $('.ui-keyboard-button[data-action="space"]').addClass('disabled')
            kb.$keyboard
                .find(letters[i])
                .toggleClass('disabled', toggle)
                .prop('disabled', toggle);
        }
    };
    if (toggle == false) {
        $.extend($.keyboard.keyaction, {
            A: function (base, el) {
                base.insertText('+'+ el.innerText);
            }

**Comment by Mottie** [comment]
I might have gotten a little carried away LOL... darn CDO (OCD sorted, yeah really :smile_cat: ).

[Here is the demo](http://jsfiddle.net/Mottie/egb3a1sk/565/) I came up with... you'll need to include the `jquery.keyboard.extension-extender.js` file.

```js
$(function(){
		// keys to be assigned an action
	var	keys = 'F1 F2 F3 F4 F5 F6 F7 F8 F9 F10 F11 F12 Ctrl Esc PageUp PageDown Insert Home Delete End Up Left Down Right'.split(' '),
		// keys active when visible
		commandKeys = 'F1 F2 F3 F4 F5 F6 F7 F8 F9 F10 F11 F12 bksp LTab enter LShift RShift Ctrl RAlt',

		// command key class names
		command = '.ui-keyboard-' + commandKeys.split(' ').join( ',.ui-keyboard-' ),

		extend = function( arry, vals ) {
			var indx,
				len = arry.length,
				obj = {};
			for (indx = 0; indx < len; indx++) {
				obj[ arry[indx] ] = vals[ indx ];
			}
			$.extend( $.keyboard.keyaction, obj );
		},

		toggleKeyState = function( keyboard, state ) {
			keyboard.$allKeys
				.not( command )
				.prop('disabled', state)
				.attr('aria-disabled', state);
		};

	extend( keys, keys );

	// Alt, Enter, Shift & Tab keys are handled differently because internally they have special functions
	$.keyboard.keyaction.RAlt = function( base ) {
		base.insertText('Alt');
	};
	// add to beginning of array
	keys.unshift('Alt');
	$.keyboard.keyaction.LShift = $.keyboard.keyaction.RShift = function( base ) {
		base.insertText('Shift');
	};
	// add to beginning of array
	keys.unshift('Shift');

	$.keyboard.keyaction.LTab = function( base ) {
		base.insertText('Tab');
	};
	// add to beginning of array
	keys.unshift('Tab');

	$.keyboard.keyaction.enter = function( base ) {
		base.insertText('Enter');
	};
	// add to beginning of array
	keys.unshift('Enter');

	$.keyboard.layouts.navkeys = {
		'normal': [
			'{F9} {F10} {F11} {F12}',
			'{PageUp} {PageDown}',
			'{Insert} {Home}',
			'{Delete} {End}',
			'{Up}',
			'{Left} {Down} {Right}'
		]
	};

	$('#keyboard').keyboard({
		layout : 'custom',
		customLayout : {
			'normal': [
				'{Esc} {sp:1} {F1} {F2} {F3} {F4} {sp:1} {F5} {F6} {F7} {F8}',
				'1 2 3 4 5 6 7 8 9 0 + ` {b}',
				'{LTab} Q W E R T Y U I O P \u00c5 "',
				'A S D F G H J K L \u00c6 \u00d8 \' {enter}',
				'{LShift} < Z X C V B N M , . - {RShift}',
				'{accept} {Ctrl} {space} {RAlt} {cancel}'
			]
		},
		display : {
			// make the buttons show the spelling we want
			'RAlt'   : 'Alt',
			'LShift' : '\u21e7',
			'RShift' : 'Shift',
			'LTab'   : 'Tab'
		},
		initialized: function( event, keyboard ) {
			keyboard.last.keyCombo = [];
			keyboard.last.keyComboReset = [];
		},
		visible: function( event, keyboard ) {
			console.log( keyboard.last.keyCombo.length === 0 );
			toggleKeyState( keyboard, keyboard.last.keyCombo.length === 0 );
		},
		change : function(event, keyboard) {
			var len,
				$key = keyboard.last.$key,
				$el = keyboard.$preview;
			if ($key.hasClass('ui-keyboard-bksp')) {
				keyboard.last.keyCombo.pop();
			} else if ( /\bui-keyboard-[LR]Shift\b/.test($key[0].className) ) {
				// shift keys get special treatment
				keyboard.last.keyCombo.push( 'Shift' );
			} else {
				keyboard.last.keyCombo.push( keyboard.last.key );
			}
			$el.val( keyboard.last.keyCombo.join('+') );
			toggleKeyState( keyboard, keyboard.last.keyCombo.length === 0 );
			// move caret to end
			len = $el.val().length;
			$.keyboard.caret( $el, len, len );
		},
		canceled: function( event, keyboard ) {
			// extend array otherwise javascript will pass the array by reference
			keyboard.last.keyCombo = $.extend( [], keyboard.last.keyComboReset );
		},
		accepted: function( event, keyboard ) {
			keyboard.last.keyComboReset = $.extend( [], keyboard.last.keyCombo );
		}
	}).addExtender({
		layout     : 'navkeys',
		showing    : true,
		reposition : false
	});
});
```

**Comment by RaduMirsk** [comment]
Awesome! Thank you for your time and solution! Definitely your solution is lighter than mine :P

**Comment by Mottie** [comment]
It can be simplified even more if you use the changes that are in the master branch... essentially the class names now include all the text from the key instead of just the first letter. So now you don't need to make `F1` through `F12` action keys, etc.

[Demo](http://jsfiddle.net/Mottie/egb3a1sk/568/) using `jquery.keyboard.js` from the master branch.

I am also about to push a fix to make `lockInput` include the backspace key and prevent it from working, otherwise this code has issues.
