### ISSUE TITLE
Mapped keys don't work without mousewheel extension

### ISSUE THREAD

**Issue by isfs** [Mottie/Keyboard#373]
This is easy to reproduce using the demo. Remove the jquery.mousewheel.js script from index.html then open it. The "Custom: Mapped Keys" keyboard will then not work properly when you click the keys. Instead of just inserting "α" it will insert "α(a)" and so on. It works correctly if you type using the keyboard, but not when you click the virtual keys.

**Comment by Mottie** [comment]
Hi @isfs!

Thanks for reporting this issue. I'll have it fixed in the master branch shortly.
