### ISSUE TITLE
When Tipsy is included, the typing extension seems to activate when not applied

### ISSUE THREAD

**Issue by isfs** [Mottie/Keyboard#374]
This is evident in the demo. Open the "Custom: Mapped Keys" keyboard and press some letters (a-g and/or shift); you will see the keys activating as if the typing extension is active, but there is no addTyping() call for this keyboard. However, if you remove the jquery.tipsy.min.js script from index.html, it behaves as expected (the typing extension is active only for keyboards where addTyping() is called).

**Comment by isfs** [comment]
Actually, it is only shift that triggers this, not a-g keys. Perhaps Tipsy is fixing something, not breaking it. Whatever is happening, though, I don't think there should be this interaction between Tipsy and the keyboard. It is somewhat confusing.

**Comment by Mottie** [comment]
Hi @isfs!

Actually the typing extension is applied to all inputs/textareas on the main demo page.

I set up [this demo](http://jsfiddle.net/Mottie/egb3a1sk/569/) which loads but does not initialize the typing extension. The typing extension is what changes the keyset while pressing shift on the physical keyboard.
