### ISSUE TITLE
Scrolling the screen

### ISSUE THREAD

**Issue by naveenpatibanda** [Mottie/Keyboard#375]
I have plugged in the Mottie OSK into my application and wanted to find out if there is any option available to pull the screen up when keyboard popups (similar to iOS style, when a field gets focus the screen scrolls up and keyboard shows up). that way user will know in which field he is typing in.

Thanks in advance.

**Comment by Mottie** [comment]
Hi @naveenpatibanda!

When you focus an input, the browser should reposition the input to make it visible. 

On the [home wiki page](https://github.com/Mottie/Keyboard/wiki) is a [donation form demo](http://jsfiddle.net/Mottie/Em8sG/624/) which does actually set the `scrollTop` to ensure the input is visible - use the next & prev buttons to see this method work.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
