### ISSUE TITLE
Multiple keyboard sizes on one page

### ISSUE THREAD

**Issue by 12Arjan** [Mottie/Keyboard#378]
I have a page with multiple inputs.
One is using the numpad layout and the other is using the qwerty layout.
I would like to have the numpad a larger font-size than the querty layout, is that possible? And if yes, how?

**Comment by Mottie** [comment]
Hi @12Arjan!

When the input/textarea has an ID assigned, the keyboard popup will get that same ID plus `"_keyboard"` added to the end ([demo](http://jsfiddle.net/Mottie/egb3a1sk/591/)):

So this input:

```html
<input id="numpad" type="text" />
```

will get a virtual keyboard with an ID of `numpad_keyboard`

```html
<div id="numpad_keyboard" class="ui-keyboard" role="textbox">
   ...
</div>
```

So add css to target the specific keyboard:

```css
#numpad_keyboard {
    font-size: 1.6em;
}
```

**Comment by Mottie** [comment]
Oh, and if you want to change the `_keyboard` id suffix, use the following javascript:

```js
$.keyboard.css.idSuffix = '_virtual_keyboard';
```

**Comment by 12Arjan** [comment]
Hello Mottie,

Thank you very much for your explanation.
Can this also be done by classes?
I want to dynamically add input's with virtual keyboards to the page.
