### ISSUE TITLE
How to trigger the virtual keyboard depending on a dropdown selection

### ISSUE THREAD

**Issue by RaduMirsk** [Mottie/Keyboard#380]
I currently have a select tag with some options and an input. Whenever the user is selecting 'ControlCommand' as an option the next input should be able to trigger the Keyboard. Whenever another option is selected the input should just allow the user to type and hide the keyboard.

![capture](https://cloud.githubusercontent.com/assets/13481376/9248960/db8f49f8-41c0-11e5-8dda-2271e3ef617f.JPG)

I have made a switch based on the selection name and try to remove and add the ID to the text input that triggers the keyboard but the problem is that once I am choosing the ControlCommand, no matter what other option I am choosing afterwards the keyboard will still display when the user clicks the input

        switch (valueSelected) {
            case 'ControlCommand':
                $('#changeInputType').attr('class', 'inter');
                openKeyboard();
                break;
            case 'KeyStrokeCommand':
                $('#changeInputType').removeAttr('class', 'inter');
                removeClass();
                break;
            case 'RunProgramCommand':
                $('#changeInputType').removeAttr('class', 'inter');
                removeClass();
                break;

Any suggestions how i can make the input to show the keyboard based on a previous selection?

**Comment by Mottie** [comment]
Hi @RaduMirsk!

Try this ([demo](http://jsfiddle.net/Mottie/egb3a1sk/596/)):

```html
<input id="keyboard" type="text" />
<select id="mode">
	<option value="kb">Use virtual keyboard</option>
	<option value="nokb">No virtual keyboard</option>
	<option value="console">Output to console</option>
</select>
```

```js
$( function () {
	var mode;
	$( '#keyboard' )
		.keyboard({
			openOn : ''
		})
		.addTyping({
			showTyping : true,
			delay : 250
		})
		.on( 'focus', function() {
			if ( mode === 'kb' ) {
				$( '#keyboard' ).getkeyboard().reveal();
			}
		})
		.on( 'keyup touchend', function( e ) {
			if ( mode === 'console' ) {
				console.log( String.fromCharCode( e.which ) );
			}
		});

	$( '#mode' )
		.on( 'change', function() {
			mode = this.value;
		})
		.change();
});
```

**Comment by RaduMirsk** [comment]
Hi Mottie!

Thanks for your quick answer! I actually just found another way of doing it using

 keyboard = $('#changeInputType').keyboard().getkeyboard();
    keyboard.destroy();

So whenever the option is different that the one I need to trigger the keyboard I will just destroy it. Thanks for your solution!

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Comment by radu-andrei-28** [comment]
Works like charm! Thank you again for your support!
