### ISSUE TITLE
Autocomplete suggestion box hidden after accept

### ISSUE THREAD

**Issue by nemesis538** [Mottie/Keyboard#382]
Hi, there seems to be an issue with the position of the autocomplete suggestion box after the accept button was clicked. The suggestion box pops up on the right side of the keyboard at first which is great. If the users accepts the text and closes the keyboard but reset the focus on the same input, the suggestion box will now appear behind the keyboard instead of beside it.

It seems that the ul element's left and top properties are no longer calculated accurately. (in my case it was 650px and 25.6px respectively and it became 12.5667px and -0.0000610352px respectively)

I can reproduce the issue with your playground demo here: http://jsfiddle.net/Mottie/n6xeoLyp/

![1](https://cloud.githubusercontent.com/assets/5323740/9310073/8b680e88-44db-11e5-8c1e-1ff943b0d2f7.PNG)
![2](https://cloud.githubusercontent.com/assets/5323740/9310074/8b68500a-44db-11e5-931b-ff9be784d9e7.PNG)

**Comment by Mottie** [comment]
Hi @nemesis538!

I didn't realize I had 538 other nemeses :astonished: hehe

Thanks for reporting this problem. I'll have it fixed shortly.
