### ISSUE TITLE
Caret-Extension crashes in older browsers

### ISSUE THREAD

**Issue by JordanGaede** [Mottie/Keyboard#384]
The following line - >`computed = window.getComputedStyle ? getComputedStyle( element ) : element.currentStyle;` crashes older browses.

`window.getComputedStyle` looks to require both parameters for older browsers

i.e `var style = window.getComputedStyle(elem1, null)`

https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle

**Comment by Mottie** [comment]
Hi @JordanGaede!

What browser is having trouble?

That MDN page shows this syntax:

> ```js
var style = window.getComputedStyle(element[, pseudoElt]);
```

but then has a note:

> Note: Prior to Gecko 2.0 (Firefox 4 / Thunderbird 3.3 / SeaMonkey 2.1), the pseudoElt parameter was required. No other major browser required this parameter be specified if null. Gecko has been changed to match the behavior of other browsers.

Leading me to understand that the `null` was only required in older Firefox browsers.

**Comment by JordanGaede** [comment]
Currently its on a test of Firefox v3.0

**Comment by Mottie** [comment]
Do people still use Firefox v3.0? 

And oops, you're right! I did find that IE8 and older need the script to use `element.currentStyle`. I'll work on a fix for that.

**Comment by Mottie** [comment]
Actually... on Wikipedia, it shows [Firefox v3.0 usage at 0%](https://en.wikipedia.org/wiki/Firefox_3#Usage)

**Comment by JordanGaede** [comment]
Have a few people using Firefox 3.0, 3.2, 3.6. 

Thanks for that

**Comment by Mottie** [comment]
Ok, it's fixed in the master branch... I'll look to see what else is pending, I might bump the version for you.

**Comment by Mottie** [comment]
Ok, v1.25.2 is available.
