### ISSUE TITLE
Extension-Caret: Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by JordanGaede** [Mottie/Keyboard#385]
With the flag `tabNavigation: true` turned on for keyboard an exception us thrown when using the physical keyboards `tab` key (not the virtual keyboard) and Uncaught TypeError is thrown on the following line `Line: 103`

`div = base.caret_$div[0];` 

`base_care_$div[0]` returns `null`

**Comment by Mottie** [comment]
Hi @JordanGaede!

Thanks for reporting this problem, I'll have it fixed here shortly.
