### ISSUE TITLE
Shift malfunction after closing keyboard

### ISSUE THREAD

**Issue by ExcellaSeras** [Mottie/Keyboard#387]
1. I opened the International keyboard demo and changed the layout(Alt button). Then I closed the keyboard(focus lost) and opened it again. The layout was default. I pressed Shift and got alternate layout instead of default.
2. I opened the same keyboard, pressed shift and closed the keyboard. Then opened it again and pressed shift again. The letters were still lowcase.

**Comment by Mottie** [comment]
Hi @ExcellaSeras!

Thanks for reporting this problem, I'll get it fixed today!

**Comment by Mottie** [comment]
The patch is currently only available in the master branch. If nothing else comes up, I'll push a new release this weekend.
