### ISSUE TITLE
On key press on the physical keyboard how to give focus to the onscreen keyboard

### ISSUE THREAD

**Issue by mithundebnath** [Mottie/Keyboard#391]
Hello Sir,
In the Keyboard-master/Keyboard-master/layouts.html (unzipped) when I press any key on the physical keyboard I can see the exact key changes its color on the onscreen keyboard.Sir From which part of the project this thing has been handled?I want to implement the same thing in the http://mottie.github.io/Keyboard/docs/layouts3.html

**Comment by Mottie** [comment]
Hi @mithundebnath!

To add the highlighting, you need the typing extension. But, it looks like I changed some things in v1.24.0 that broke it.

I'll have the problem fixed shortly and push a new version.
