### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [Mottie/Keyboard#392]
Hi, im using MeteorJS for development, I placed the dist folder inside client/compatibility... so i'm loading all files as I would normally
the result:
![help](https://cloud.githubusercontent.com/assets/12840136/9994879/ae0d6b64-6055-11e5-9a78-c198c1ab299c.png)

**Comment by Mottie** [comment]
Hi @shactdeveloper!

Are you loading `jquery.keyboard.js` first? The `jquery.keyboard.extension-all.js` contains all the extensions & the mousewheel plugin, but not the core program.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
