### ISSUE TITLE
Text area scrolls to beginning after clicking a key on the virtual keyboard

### ISSUE THREAD

**Issue by abacuswl** [Mottie/Keyboard#397]
Here are the steps to reproduce the issue:
1. Use a text area that contains a lot of initial text so that there are scrollbars.
2. Open the virtual keyboard without a preview window.
3. Scroll to the bottom of the text area and position the cursor at the end of the text with the mouse.
4. Click a key on the virtual keyboard.
5. The character is appended to the end of the text, but the text area scrolls back to the beginning of the text.
This is happening in IE 11 and the latest Chrome (Version 46.0.2490.80).  It's okay in Firefox.

**Comment by Mottie** [comment]
Hi @abacuswl!

Thanks for reporting this issue. I'll try to look into it this weekend.

**Comment by abacuswl** [comment]
Not sure if this is the right way to handle the issue, but it seems to work.  I forked the project and sent a pull request.
