### ISSUE TITLE
restricted function doesn't work after updating to new release

### ISSUE THREAD

**Issue by simasalmani** [Mottie/Keyboard#399]
Hi @Mottie ,
I just updated the JQuery.keyboard to release 1.25.6 and restricted function doesn't work correctly anymore.
It fires every time I type in my input, even when the keyboard doesn't reject the user entered key.
thank you in advance

**Comment by Mottie** [comment]
Hi @simasalmani!

Thanks, I'll try to look into this today.

**Comment by afattahi54** [comment]
I used it correctly in 1.19.3 but in new version I face same issue !

**Comment by Mottie** [comment]
Ok, this issue has been fixed in the master branch. Try out [this demo](http://jsfiddle.net/Mottie/egb3a1sk/893/).

**Comment by simasalmani** [comment]
@Mottie thank you
