### ISSUE TITLE
How would I make typing the enter key trigger the "accept" key

### ISSUE THREAD

**Issue by patriciavandermeer** [Mottie/Keyboard#401]
I've got some senarios in my implementation where the on screen keyboard exists on places that have a real keyboard.  Normally, the users can figure out to click the accept, but I've had more then a few reports of "Pressing Enter doesn't make the keyboard go away".

I know they shouldn't be using it in this case, I've got things in place to avoid it, but you know how clients can be sometimes. 

My first guess was to try to tie something into the initialize call back, but I don't seem to have a reference to the input box that the keyboard focuses on from there.  Is the ID, or a class or something to get to that input available in the keyboard object at that point?

i was looking through the object at one point and thought I saw a "preview" reference that seemed to be what I needed, but then I couldn't find it back :(  

this was my idea for implementation:

```
initialized: function (e, keyboard, el) {
                    keyboard.preview.onEnter(function () {
                        keyboard.accept();
                    });
                }
```
any ideas or guidance or pointing in the general direction would be amazing!

Thanks for building a solid plugin!

**Comment by Mottie** [comment]
Hi @patriciavandermeer!

The easiest method would be to [redefine the <kbd>Enter</kbd> keyaction](https://github.com/Mottie/Keyboard/wiki/Actions). You can add the following code before initializing the keyboard:

```js
$.keyboard.keyaction.enter = function( kb ) {
  // same as $.keyboard.keyaction.accept();
  kb.close( true );
  return false;     // return false prevents further processing
};
```

If you want to use the [`autoAccept` option](https://github.com/Mottie/Keyboard/wiki/Usability#autoaccept), then change the first line to:

```js
  kb.close( kb.options.autoAccept ? 'true' : false );
```

**Comment by patriciavandermeer** [comment]
Thanks for getting back to me so quickly!   I'll try to work this into my implementation and see if it'll do the trick!

**Comment by patriciavandermeer** [comment]
perfect! thanks :)

**Comment by ha0x7c7** [comment]
I used this approach, but if there is a submit button and I want the form to be submitted on pressing the enter, by using this approach, pressing the enter does not submit the form.

**Comment by Mottie** [comment]
In that case, target the form and submit:

```js
$.keyboard.keyaction.enter = function( kb ) {
  // same as $.keyboard.keyaction.accept();
  kb.close( true );
  $('#myform').submit();
  return false;     // return false prevents further processing
};
```

**Comment by ha0x7c7** [comment]
is this code applied globally ?

**Comment by Mottie** [comment]
It's a jQuery method, and it applies to the targeted form ([ref](http://api.jquery.com/submit/)).
