### ISSUE TITLE
custom layout spacer placed after the endrow

### ISSUE THREAD

**Issue by a1bert01** [Mottie/Keyboard#402]
spacer placed at the end of the row is rendered after it (&lt;br class="ui-keyboard-button-endrow"&gt;):

http://jsfiddle.net/egb3a1sk/922/

**Comment by Mottie** [comment]
Hi @a1bert01!

Thanks for the demo & for reporting this problem. I'll try to get it fixed ASAP.

**Comment by Mottie** [comment]
Ok, this is now fixed in the master branch ([demo](http://jsfiddle.net/egb3a1sk/925/)).
