### ISSUE TITLE
keyboard.last.start and keyboard.last.end are the same

### ISSUE THREAD

**Issue by knod** [Mottie/Keyboard#404]
Inside the change event I `console.log(keyboard)` and `keyboard.last.start` and `keyboard.last.end` always appear to be the same, no matter the length of the key's value.

**Comment by Mottie** [comment]
Hi @knod!

As I described in #403, the `start` and `end` will only differ if there is text selected inside the input/textarea.

**Comment by knod** [comment]
Understood, that completely clarifies it. `start` and `end` are about the caret position. If there's a selection, they're different, otherwise they're the same.
