### ISSUE TITLE
createTextRange() is not function

### ISSUE THREAD

**Issue by phuongntit** [Mottie/Keyboard#406]
![capture](https://cloud.githubusercontent.com/assets/15976159/11356652/52c0345c-9292-11e5-8ee6-7c0bf132a92b.PNG)

**Comment by Mottie** [comment]
Hi @phuongntit!

What version are you using? In the current version `$.fn.caret` is on line 2421.

Also, would you share the HTML of the element (is it a textarea or input? what type of input?) and the initialization code.

Is this related to #309? It is no longer possible to get the caret position of inputs of type email and number ([ref](https://html.spec.whatwg.org/multipage/forms.html#do-not-apply)).

**Comment by phuongntit** [comment]
Hi @Mottie 
I use version 1.18.12: http://plugins.jquery.com/keyboard/
I use span (or div) elements with css allow edit (mathquill-editable) to can input and display math operators.

**Comment by Mottie** [comment]
Sorry, contenteditable elements are not currently supported. See #208 &amp; #258.

**Comment by phuongntit** [comment]
Oh! Thanks for your comments.

**Comment by Mottie** [comment]
I'll update #208 when this gets implemented.
