### ISSUE TITLE
Text triggered on mouse down/touch down, not up

### ISSUE THREAD

**Issue by knod** [Mottie/Keyboard#407]
This means that if a user wants to abort their current key by dragging off of the element before releasing their mouse or touch contact, there's no way to do that. Is there a specific reason for this? Is there a way to work around this?

**Comment by Mottie** [comment]
Hi @knod!

The virtual keyboard is meant to act like a physical keyboard. When you press a key down, a character is added. If you continue to hold that key down, the key repeats. Only once you let the key up will the repeating stop.

If you want to change that behavior, then set the [`keybinding` option](https://github.com/Mottie/Keyboard/wiki/Usability#keybinding) to use `mouseup`.

If the mousedown repeater starts too quickly for you, then set the [`repeatDelay` option](https://github.com/Mottie/Keyboard/wiki/Usability#repeatdelay) to some number greater than `500` (default).

### [Demo](http://jsfiddle.net/Mottie/egb3a1sk/937/)

```js
$('#keyboard').keyboard({
    // Event (namepaced) for when the character is added to the
    // input (clicking on the keyboard)
    keyBinding: 'mouseup touchstart',
    // Mouse repeat delay - when clicking/touching a virtual keyboard
    // key, after this delay the key will start repeating
    repeatDelay: 1000
})
```

**Comment by knod** [comment]
Thanks, that's great!
