### ISSUE TITLE
How to display pointer until lockInput is true

### ISSUE THREAD

**Issue by phuongntit** [Mottie/Keyboard#408]
I want display pointer when lock input. Please help me to do this.
![capture](https://cloud.githubusercontent.com/assets/15976159/11388366/ff72ea8e-9367-11e5-9f07-2d972fcad9c0.PNG)
![capture2](https://cloud.githubusercontent.com/assets/15976159/11388365/ff72aaa6-9367-11e5-9f44-e4ae1fb5cecd.PNG)

**Comment by Mottie** [comment]
Hi @phuongntit!

Try the [caret extension](http://mottie.github.io/Keyboard/#caret).

![2015-11-25 09_04_07-virtual keyboard](https://cloud.githubusercontent.com/assets/136959/11400561/9bc28940-9353-11e5-91b8-598a16f96da9.png)

Click on the "QWERTY (mod) Text Area" title, then scroll to the bottom of the page for the code, or check out [the documentation](https://github.com/Mottie/Keyboard/wiki/Setup#caret).
