### ISSUE TITLE
Large Num Pad...

### ISSUE THREAD

**Issue by KevinChanK** [Mottie/Keyboard#409]
Hi,

I would like to have large num pad (enlarge around 200%)...
How can I do...

Thanks a lot...

**Comment by Mottie** [comment]
Hi @KevinChanK!

I hope you found your answer! Just in case anyone else searches, a detailed answer is in [the FAQ](https://github.com/Mottie/Keyboard/wiki/FAQ#q-is-there-an-easy-way-to-change-the-size-of-the-keyboard).

**Comment by KevinChanK** [comment]
thanks a lot!
