### ISSUE TITLE
Readme is unclear that this is a client-side library, no server needed

### ISSUE THREAD

**Issue by knod** [Mottie/Keyboard#410]
To beginners with this stuff, it's not clear from the README on the front page of the repo that no server is needed to use Keyboard. It's an issue a lot of repos have. This one is especially confusing because the README describes installing it with node, which is often an indication that stuff will be happening with a server. You can actually just download the zip file.

The setup page helps if someone goes to the wiki and then knows what they're looking for, but it'd be great to have it stated clearly up front.

**Comment by Mottie** [comment]
Hi @knod!

Yeah, I've been neglecting the main readme. I'll work on updating it. Thanks!

**Comment by knod** [comment]
Thanks @Mottie!
