### ISSUE TITLE
Ipad Safari - key pressed always lags behind

### ISSUE THREAD

**Issue by dan937** [Mottie/Keyboard#411]
Using your demo page, or my own creation, if I start typing ...   1 2 3 4 5 etc...   It doesn't show the current key I press.. it displays the previous key I pressed.  So it is always one behind.  Doesn't matter what keyboard configuration/example I use.

This is on safari ipad (9.1).  I only have one ios device so I couldn't test anywhere else.

**Comment by Mottie** [comment]
Hi @dan937!

Please try removing the mousewheel plugin when using this plugin on mobile devices - see #379.

**Comment by dan937** [comment]
Yes that resolved the issue.  Thanks!
`useWheel : false`

**Comment by Mottie** [comment]
I believe I found and fixed the issue causing the previous key to be entered. So no more need to be extra vigilant and ensure the mousewheel plugin isn't being loaded, or to set the `useWheel` option.

**Comment by dan937** [comment]
Super.. thanks for the vigilance.
