### ISSUE TITLE
npm distribution not packaged well for easy import

### ISSUE THREAD

**Issue by bjyurkovich** [Mottie/Keyboard#414]
Currently, the `package.json` looks like this (important for npm):

```json
{
  "name": "virtual-keyboard",
  "title": "Keyboard",
  "description": "Virtual Keyboard using jQuery UI",
  "version": "1.25.9",
  "author": {
    "name": "Jeremy Satterfield",
    "url": "https://github.com/jsatt"
  },
...
```

A line should be added in the root object of `package.json` that looks like this:

```json
  "main": "dist/js/jquery.keyboard.min.js",
````

It is usable as it is now, but in order to use npm directly with an `import` or `requires`, this should be added.

**Comment by Mottie** [comment]
Hi @bjyurkovich!

I would appreciate a PR with this change.

And how would you include the css file? Could you set the main value like this?

```js
"main" : "dist/*"
```
