### ISSUE TITLE
Set up keyboard with non-input elements

### ISSUE THREAD

**Issue by faboudib** [Mottie/Keyboard#417]
First thanks for sharing your work. My request might be very specific as I'm using your plugin on a TV platform. My platform doesn't allow me to disable the native keyboard which pops up automatically on input fields (tried setting lockInput to true but it also doesn't work). Would it be possible to use your plugin on a div instead of an input somehow? This would allow me to override the native keyboard.

**Comment by Mottie** [comment]
Hi @faboudib!

To make the keyboard work you'll need a way to position a caret to allow inserting, deleting or text selection. That is only possible by using an input, textarea or content editable element. Sadly, this project does not currently support adding a keyboard to a content editable element (see #208 to follow progress on this enhancement). Anyway, I believe a div set as content editable will still open the native keyboard.

If you are using the latest version, try adding a `readonly` attribute to the input and see if the native keyboard still opens.

```html
<input type="text" readonly="readonly">
```
