### ISSUE TITLE
Backspace on wide keys jumbles input

### ISSUE THREAD

**Issue by freemaths** [Mottie/Keyboard#419]
With a key such as "sin" backspace jumbles the characters of the preceding string. E.g. pressing:

sin sin {b}

result in 

nsi

http://jsfiddle.net/edarnell/pqvkbckd/21/

**Comment by Mottie** [comment]
Hi @freemaths!

Wow that is odd... to be 100% honest I had no idea that `restrictInput` would remove blocks of letters like that LOL. And I think that is where the problem is located. I'll try to dig into the code more tonight. Thanks!

**Comment by Mottie** [comment]
I found the problem! The fix is now available in the master branch.

I updated the demo so you can test it, but rawgit is taking a while to catch up so don't think it's broken just yet :wink: 

http://jsfiddle.net/Mottie/pqvkbckd/22/

**Comment by Mottie** [comment]
Ok, now it's working... I think it's sort of a bonus that if the caret is in the middle of a word like. `c|os` and you press `sin`, the `cos` gets replaced with `sin`.

**Comment by freemaths** [comment]
Works perfectly - many thanks.
