### ISSUE TITLE
How to not inherit the jquery theme on the target input

### ISSUE THREAD

**Issue by mdsteenb** [Mottie/Keyboard#420]
Love the keyboard - however the theme applied to the keyboard seems to apply it to the input component that is launching the keyboard (aka the target of the keyboard) - anyway to decouple that?

**Comment by Mottie** [comment]
Hi @mdsteenb!

Change the [`css` options](https://github.com/Mottie/Keyboard/wiki/Layout#css) to match whatever layout you want. The default settings use jQuery UI class names, but you can add [custom style](http://jsfiddle.net/Mottie/jsh0377k/) (using jQuery UI class names) or [bootstrap classes](http://jsfiddle.net/Mottie/MK947/1837/).

**Comment by Mottie** [comment]
Oh, also if the input has an id, the virtual keyboard popup will get an id that starts with that same id and ends with `"_keyboard"` - see [this demo](http://jsfiddle.net/Mottie/egb3a1sk/591/).

**Comment by mdsteenb** [comment]
Awesome - thank you!!!

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
