### ISSUE TITLE
Want to add a label for the input field

### ISSUE THREAD

**Issue by mdsteenb** [Mottie/Keyboard#421]
As I try to understand buildKeyboard() - it should be obvious to me where I might be able to add a label - so I can have a label that reminds the user what they are entering i.e. First name: <Input>, where the default behavior is simply the input field....any hints on where to inject a label?

**Comment by Mottie** [comment]
Hi @mdsteenb!

You could either set the `usePreview` option to `false` and have only the keyboard (no preview input) pop up under the input/label, or use the following code to add a label ([demo](http://jsfiddle.net/Mottie/egb3a1sk/1086/)):

CSS

```css
.ui-keyboard label, .ui-keyboard-preview {
  float: left;
}
```

Code

```js
$(function() {

  $('#keyboard').keyboard({
      visible: function(e, keyboard, el) {
      	keyboard.$keyboard.prepend('<label>Test:</label>');
      }
    })
    // activate the typing extension
    .addTyping({
      showTyping: true,
      delay: 250
    });

});
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Comment by mdsteenb** [comment]
Thank you Rob - yes you were extremely helpful
