### ISSUE TITLE
Make unminified version available in NPM module

### ISSUE THREAD

**Issue by omasback** [Mottie/Keyboard#422]
It would be nice to be able to use the unminified library when loading via NPM in dev. Currently struggling with some focus/placeholder bugs and I'm unable to set breakpoints in the library, even after using Chrome's code expander tool.

**Comment by Mottie** [comment]
Hi @omasback!

Ok, I'll update the build, but I don't plan on pushing a new release until I isolate a few bugs associated with #416.

**Comment by omasback** [comment]
cool thanks!

**Comment by Mottie** [comment]
New release now available.
