### ISSUE TITLE
Keyboard width

### ISSUE THREAD

**Issue by apod42** [Mottie/Keyboard#424]
Hello,

Updated my core code to the latest version of your virtual keyboard. Before, I was using core code from 2014 with minor modifications by me. 

I am facing a weird behavior now: the width of the virtual keyboard is 100-percent the screen width, with a margin on the left edge of the screen, which causes a horizontal scroll bar to appear in the browser window.

Problem is fixed if in the css class .ui-widget-content I add a "width: 500px;" (or whatever). 

I am just wondering why is this occuring? Using the old core code I never had to declare a width for the virtual keyboard.

**Comment by apod42** [comment]
This is my css file:

/*-------------------------------------------------- Virtual keyboard -------------------------------------------------- */

.ui-widget {
  font-family:Georgia,"Times New Roman",Times,serif;
  font-size:1em
}
.ui-widget input,.ui-widget select,.ui-widget textarea,.ui-widget button {
  font-family:Georgia,"Times New Roman",Times,serif;
  font-size:1em
}
.ui-widget-content {
  border:#68655d solid 1px;
  border-radius:5px;
  background:#faf7ef url(http://www.example.com/img.png);
  background-repeat:repeat;
  -webkit-background-clip:padding-box;
  -moz-background-clip:padding;
  background-clip:padding-box;
  box-shadow : 2px 2px 8px #68655d;
  -moz-box-shadow : 2px 2px 8px #68655d;
  -webkit-box-shadow : 2px 2px 8px #68655d;  
 
}
.ui-state-default,.ui-widget-content .ui-state-default,.ui-widget-header .ui-state-default {
  border:#554014 solid 1px;
  background:#faf7ef url(http://www.example.com/img2.png);
  background-repeat:repeat;
  font-weight:700;
  color:#732c00;
  box-shadow:2px 2px 8px #68655d;
  -moz-box-shadow:2px 2px 8px #68655d;
  -webkit-box-shadow:2px 2px 8px #68655d;
  -webkit-background-clip:padding-box;
  -moz-background-clip:padding;
  background-clip:padding-box
}
.ui-state-hover,.ui-widget-content .ui-state-hover,.ui-widget-header .ui-state-hover {
  border:#554014 solid 1px;
  background:#fefefc;
  font-weight:700;
  color:#732c00;
  box-shadow:4px 4px 8px #68655d;
  -moz-box-shadow:4px 4px 8px #68655d;
  -webkit-box-shadow:4px 4px 8px #68655d;
  -webkit-background-clip:padding-box;
  -moz-background-clip:padding;
  background-clip:padding-box
}
.ui-corner-all {
  border-radius:5px
}
.ui-keyboard {
  padding:6px
}
.ui-keyboard-button {
  min-height:37px;
  min-width:37px;
  margin:6px;
  cursor:pointer;
  overflow:hidden;
  line-height:0;
  -moz-user-focus:ignore;
}

**Comment by Mottie** [comment]
The keyboard code does not define an overall width, except in older versions of IE, so everything is essentially styled using CSS and the font.

In the css that was shared, a font size of `1em` is defined for the buttons & keyboard. Setting the font size on the keyboard, `.ui-widget` as defined in the above css, or `.ui-keyboard div` from the [FAQ](https://github.com/Mottie/Keyboard/wiki/FAQ#changesize), is what determines the actual keyboard width. Along with the key `.ui-keyboard-button` size & margins.

So if you modify the `6px` margin and set the `.ui-widget` font size smaller, the keyboard width should be more manageable ([demo](http://jsfiddle.net/Mottie/egb3a1sk/1104/))

```css
/* css used to override the definitions above */
div.ui-widget {
  font-size: .8em;
}
button.ui-keyboard-button {
  margin: 2px;
}
```

Also, check out the [themes](https://github.com/Mottie/Keyboard#themes) section in the main readme. There are other theme options which may give you some ideas.

**Comment by apod42** [comment]
Thank you!
