### ISSUE TITLE
":" key on physical keyboard not getting mapped to respective representation on virtual keyboard

### ISSUE THREAD

**Issue by avantikadwivedi** [Mottie/Keyboard#425]
I am able to map all the keys to virtual keyboard in normal and shift mode. But shift mode of key ";" i.e. ":" is not getting mapped also the unicode character for the shift-mode is getting appended with an extra "(".
This problem is occurring for Devanagari and Bengali layouts, and possibly in all the non-english layouts.

**Comment by avantikadwivedi** [comment]
Also this problem wasn't there in version 1.22.5, which i have been using.

**Comment by Mottie** [comment]
Hi @avantikadwivedi!

So are you saying the issue is in the latest version? I did have to change how the `:` key was handled because it is a special case. I'll try to look at this more when I get some time.

**Comment by avantikadwivedi** [comment]
Yes it is with the latest version. Since i have using v1.22.5 and it did not have any such issue. 
The older version is doing the mapping well but i also need to use the readonly property and this property has not been supported in the older version (if i make the input property readonly then keyboard doesn't appear at all). If it's possible to enable the older version(1.22.5) to be work with readonly property, then that problem will be solved.

**Comment by Mottie** [comment]
For the older version don't add a `readonly` property to the input, instead set the [`lockInput` option](https://github.com/Mottie/Keyboard/wiki/Usability#lockinput) to `true`. It adds a `readonly` property after it initializes.

**Comment by mithundebnath** [comment]
Sir Please Look into this issue as It plays very important role while mapping indian languages in inscript layout.

**Comment by Mottie** [comment]
Ok, this issue has been fixed in v1.25.13!

**Comment by mithundebnath** [comment]
Thank you sir.
