### ISSUE TITLE
Prevent key presses until keyboard is shown

### ISSUE THREAD

**Issue by Saiberion** [Mottie/Keyboard#426]
Is it possible to prevent key presses until the keyboard is shown?

I have problems with the keyboard on a touch screen. If I tap a textbox to open the keyboard it can happen that the key that will appear on that position is pressed and added to the input text.

**Comment by Mottie** [comment]
Hi @Saiberion!

Why is the keyboard appearing over the input?

Anyway, you can disable the keyboard before it becomes visible, then enable it after a certain number of milliseconds ([demo](http://jsfiddle.net/Mottie/egb3a1sk/1118/)):

```js
$(function() {

	$('#keyboard').keyboard({
		beforeVisible: function(e, keyboard, el) {
			keyboard.enabled = false;
		},
		visible: function(e, keyboard, el) {
			setTimeout(function(){
				keyboard.enabled = true;
				keyboard.toggle();
			}, 200);
		}
	})
	// activate the typing extension
	.addTyping({
		showTyping: true,
		delay: 250
	});

});
```

**Comment by Saiberion** [comment]
The keyboard can be over the input because the display is only 800x480 und the displayed wabsite is limited to this size. So If I click a textbox on the bottom of the screen the keyboard expands to the top right.

Anyway the approach with enabled seems like what I need but for some reason my keyboard ignores this attribute and the key stay active even if enabled is set to false in beforeVisible and visible.

**Comment by Saiberion** [comment]
The not working enable probably was caused bei version 1.18.12 I used until now.

Now I have to find out why so much white space is added my my custom layout after updating the jquery.keyboard.js.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
