### ISSUE TITLE
Auto upper/lower case

### ISSUE THREAD

**Issue by ZLoG83** [Mottie/Keyboard#428]
I have used this keyboard in a webapp now. The absolutely topping issue from people is about the keyboard.
It lacks a really nice feature which I hope you will consider to implement.
It would be really nice for a parameter which would enable auto upper-case of the first letter of a word/name.
Just like on iPhone og Android devices. It seems super intuitive.
It should uppercase the first letter - and switch keyboard from from SHIFT to normal state - just like on previously mentioned devices.
If it uppercases a word/name which you manually want to have small - like "Ulrich von Doom" - then you should have the option to manually overwrite and go to "normal".

I am sure that multiple users of this nice keyboard would appreciate this update! :) I know I would.
Thanks for all the time you guys have out in to making this, It's a really nice piece of code :D

**Comment by Mottie** [comment]
Hi @ZLoG83!

It isn't build-in but you can add a little extra code to customize how the keyboard behaves. 

If you look on the home wiki page under ["Manipulating text"](https://github.com/Mottie/Keyboard/wiki#manipulating-text) you'll find [this demo](http://jsfiddle.net/Mottie/Em8sG/1246/) which switches the keyboard to the shifted keyset at the beginning and after the user enters period + a space.

```js
$('#keyboard').keyboard({
	visible: function(e, kb, el) {
		if (kb.$preview.caret().start === 0) {
			kb.shiftActive = true;
			kb.showKeySet(el);
		}
	},
	change: function(e, kb, el) {
		var caret = kb.$preview.caret(),
			end = caret.end - 2 >= 0 ? caret.end - 2 : caret.end,
			str = kb.$preview.val().substring(end, caret.end);
		kb.shiftActive = (caret.start === 0 || str.indexOf('. ') >= 0);
		kb.showKeySet(el);
	}
});
```

If you want it to type in title case, then tweak the code to only look for spaces.

**Comment by ZLoG83** [comment]
That's just wonderful! I will try this ASAP, thanks! :)

**Comment by ZLoG83** [comment]
This works like a charm with spaces... Simply changed the shiftactive criteria to str.indexOf(' ') == 1
The only thing I really miss now is the ability for the user to force the keyboard to lowercase..
When this keyboard activates, it toggles the shift key - which is great.. but if "Victor von Doom" comes to visit, I would like the ability for him to switch to lowercase manually when he wants to type "von".. makes sense? Is that possible?

**Comment by ZLoG83** [comment]
actually it seems that activating this keyboard renders the shift key useless :(

**Comment by Mottie** [comment]
Oops, sorry about that! I guess I never thoroughly tested that demo :disappointed: 

Anyway, try [this updated demo](http://jsfiddle.net/Mottie/Em8sG/3767/).

```js
$(function(){
  $('#keyboard').keyboard({

    visible: function(e, kb) {
      if ($.keyboard.caret(kb.$preview).start === 0) {
        kb.showKeySet('shift');
      }
    },
    change: function(e, kb) {
      var caret = $.keyboard.caret(kb.$preview),
        end = caret.end - 2 >= 0 ? caret.end - 2 : caret.end;
      str = kb.$preview.val().substring(end, caret.end);
      if (!/shift|lock/i.test(kb.last.key)) {
        kb.shiftActive = (caret.start === 0 || str.indexOf('. ') >= 0);
        kb.showKeySet();
      }
    }

  })
  // activate the typing extension
  .addTyping();
});
```

**Comment by ZLoG83** [comment]
My god that is sexy.. it works 100% as I intended and dreamt of now.. Thank you so much! :D
If you in Denmark some day.. stop by for a cup of cofee and watch the keyboard in real use! :D

**Comment by Mottie** [comment]
:smiley_cat:

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
