### ISSUE TITLE
Unwanted scramble on mouseover

### ISSUE THREAD

**Issue by bevrard** [Mottie/Keyboard#430]
Hi,

I have the following configuration:
http://jsfiddle.net/bevrard/94L89hzL/4/

When I move the cursor over the first keyboard, it scrambles once again...  Could you tell me why?

I can't find a solution.

Thanks in advance for your aswner.

Kind regards,

bevrard

**Comment by Mottie** [comment]
Hi @bevrard!

Interesting... I'll try to look at this when I get some time today.

**Comment by bevrard** [comment]
Hi @Mottie ,

Did you have time to look at this bug?

Thanks,

Benjamin

**Comment by Mottie** [comment]
Sorry, I'll try to dig into the code soon.

**Comment by Mottie** [comment]
Please verify that the scramble extension is working as expected... sorry, it took a while to isolate the problem.

**Comment by bevrard** [comment]
Thanks for your answer!
I'm checking this tomorrow morning!

**Comment by bevrard** [comment]
It's working as expected :-) !

Thanks a lot!

**Comment by bevrard** [comment]
Hi,

It seems that there is still a bug on mouseover.  If we use the same fiddle:
http://jsfiddle.net/bevrard/94L89hzL/7/

It's pointing on the last version of your keyboard.
Issue:
- write code in first input
- same in the second one.
- put your mouse on the first keyboard => the first input will be empty.
- do the same for the second keyboard => second input empty.

I've tried with the "noFocus" option, but it doesn't resolve the issue.

Do you have an idea?

Thanks

Benjamin

**Comment by Mottie** [comment]
Hi Benjamin!

This problem should be all fixed in the latest update. Thanks again for reporting the problem.
