### ISSUE TITLE
visible method not invoked if usePreview: false

### ISSUE THREAD

**Issue by traumatic** [Mottie/Keyboard#432]
Hi,

Based on Mottie's [example](http://jsfiddle.net/Mottie/egb3a1sk/1161/) I introduced
`usePreview: false`
which leads to the method _visible_ not being executed. See [here](http://jsfiddle.net/qsvsr5ok/). I would have expected that once the keyboard is shown, keys like _space_, _accept_, etc. are disabled.

Why does usePreview has an influence on the _visible_ method?

**Comment by Mottie** [comment]
Hi @traumatic!

Hmm, thanks for reporting this problem... it looks like bug in that when `usePreview` is `false`, the callback bindings are removed because of name-spacing. I'll have that patch available in the master branch here shortly.

Alternatively, binding to the visible event would have worked either way ([demo](http://jsfiddle.net/Mottie/qsvsr5ok/2/))

```js
$('#keyboard')
  .on('visible change', function(e, keyboard) {
    // do something
  })
  .keyboard({
    usePreview: false
  });
```

**Comment by traumatic** [comment]
Thanks for the demo Mottie. But in this one toggling back the keys from disable to enable mode don't seem to work any more ...

**Comment by Mottie** [comment]
Oh, sorry... I should have bound to "keyboardChange" which is an event that is fired with any change to the content versus "change" which is only fired, on the original element, when the content has been accepted or canceled ([docs](https://github.com/Mottie/Keyboard/wiki/Methods#events) & [demo](http://jsfiddle.net/Mottie/qsvsr5ok/4/)).

```js
$('#keyboard')
  .on('visible keyboardChange', function(e, keyboard) {
    // do something
  })
  .keyboard({
    usePreview: false
  });
```

**Comment by traumatic** [comment]
No worries Mottie. Could realised myself. Thanks for your help!
