### ISSUE TITLE
how do i attach and detach numpad  or keybaord on textbox based on data.

### ISSUE THREAD

**Issue by aatifbandey** [Mottie/Keyboard#437]
i am using react and flux and as soon as i update my store based on my data the library should attach  custom keyboard or virtual keyboard on my textbox.

     data.map(function(mydata, index) {

    if(mydata === 'Integer'){
       var inputBox = (<input className="center-block" type="text" onClick=   {attachNumpad.bind(this,        checklist_field'+index1+ "-" + index)} />)
    }
    else if(mydata =='Date'){
     var inputBox = (<input className="center-block" type="text" onClick={attachCalendar.bind(this,     checklist_field'+index1+ "-" + index)} />)
    }
    else if(mydata == 'String'){
     var inputBox = (<input className="center-block" type="text" onClick={attachKeybaord.bind(this, checklist_field'+index1+ "-" + index)} />)
      }
     })(); 

Function to attach numpad or keyabord etc

    function attachNumpad(id, toggleTime){   
      $('#'+id).numpad();  
    }

    function attachKeybaord(id, toggleTime){   
       $('#'+id).keyboard();  
     }

**Comment by Mottie** [comment]
Hi @aatifbandey!

I haven't used react, but you could always attach the keyboard, then set the layout based on the data. Something like this:

```js
data.map(function(mydata, index) {
  // the original code doesn't appear valid, so only add in a data-type attribute.
  var inputBox = ('<input data-type="' + mydata + '" className="center-block"...')
})(); 
```

Then when you attach the keyboard, do something like this:

```js
function attachKeybaord(id, toggleTime){
	var layout,
		$el = $('#'+id);
	switch($el.attr('data-type')) {
		case "Integer":
			layout = "num";
			break;
		case "Calendar":
			layout = "calendar";
			break;
		default:
			layout = "qwerty";
	}
	$el.keyboard({
		layout: layout
	});
}
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
