### ISSUE TITLE
Bind keyboard to input elements after the page load (Asynchrounous HTML loading)

### ISSUE THREAD

**Issue by Experiment8** [Mottie/Keyboard#438]
Hi,

I tried today to insert your keyboard for a test, everything works fine until i try to bind the keyboard in a moment that is not the page load, for example:

i have this code:
```
$('input[type="text"]').keyboard();
$('input[type="email"]').keyboard();
$('input[type="password"]').keyboard();
```

The keyboard renders fine and everything works, but when i try to bind it to some Dynamic generated modals, it says me:

$(...).keyboard is not a function

For an easy example of the error, i tryed to include the previous three functions in a timeout, it wont work:

`
setTimeout(
function(){
   $('input[type="text"]').keyboard();
   $('input[type="email"]').keyboard();
   $('input[type="password"]').keyboard();
}, 
5000)
`

This gives:

$(...).keyboard is not a function

Is there something i can do about it?

Thanks

**Comment by Mottie** [comment]
Hi @Experiment8!

I tested the code you shared in [this demo](http://jsfiddle.net/egb3a1sk/1210/), and it does work... but really it sounds to me like jQuery might be loaded more than once on that page.

Would you share the code being used to target the modals?

Also the initialization code can include all the selectors at once:

```js
$('input[type="text"], input[type="email"], input[type="password"]').keyboard();
```

**Comment by Experiment8** [comment]
Hi @Mottie,

Yeah that was the problem, is not my code so i didn't see the JQuery loaded via Require.js, by loading everything in require.js directly it works fine.

Thanks for help and the tip! Great Keyboard tho!

Regards

**Comment by Mottie** [comment]
Awesome! I'm glad you solved it! <img title="powerwoot" src="https://cloud.githubusercontent.com/assets/136959/12740993/30434756-c93e-11e5-8990-9432e28169b3.gif">

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
