### ISSUE TITLE
"Draggable" | After Shift or Alt its Draggable permanent

### ISSUE THREAD

**Issue by flakesnow** [Mottie/Keyboard#439]
Hey,
somebody tried already to make it draggable? 

I made the "element_keyboard" draggable. Everything works fine when i'm typing letters.

If i'm click the shift or alt key, the element is permanent draggable. 
I alrealdy looked into "showSet()" but i didnt found some issues for the draggable.

Any solutions? Its really strange beause nothing changes on the main element when i use shift or alt.

Its on Firefox and Chrome on Win 7.
On Android Chrome and other Android browsers everythings fine too.

Thanks and good night :)

**Comment by Mottie** [comment]
Hi @flakesnow!

On the Home wiki page under ["Layout"](https://github.com/Mottie/Keyboard/wiki#layout) you'll find [this draggable demo](http://jsfiddle.net/Mottie/MK947/2383/) which adds a draggable div &amp; jQuery UI to allow moving the keyboard around.  I am not seeing the issue described here.

If you would modify that demo to show me the problem, it would make it easier for me to help fix it :grin: 

CSS

```css
.ui-keyboard h2 {
    height: 10px;
    margin: 3px;
    background: #eee;
    cursor: move;
}
```

Script

```js
$(function () {

    /*
     Make keyboard draggable
    */

    $('#keyboard').keyboard({
        visible: function (e, keyboard, el) {
            keyboard.$keyboard.prepend('<h2/>')
                .draggable({
                handle: "h2",
                containment: "window"
            });
        }
    })
    // activate the typing extension
    .addTyping({
        showTyping: true,
        delay: 50
    });

});
```

**Comment by flakesnow** [comment]
Hey, i found the issue now. Im including the metro.js CSS Ui. 
And this dont like your draggable Part.  So not really your fault :) and not really something to fix for you.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
