### ISSUE TITLE
Keybord can't show on button click when prewiev window is disable

### ISSUE THREAD

**Issue by VitBr** [Mottie/Keyboard#442]
Hi All!
I need a numeric keypad without a preview window that show only at the click on a button. Not when you focus the input.
I found a problem. The keyboard is displayed only once when you first click. Other clicks keyboard can not show

My code is:

```js
$(function() {
  $('#keyboard').keyboard({
      layout: 'num',
      restrictInput: true,
      openOn: null,
      usePreview: false,      
      display: {
        'a': 'Acept',
        'c': 'Cancel'
      }
    });

  $('#icon').click(function() {
    var kb = $('#keyboard').getkeyboard();
    if (kb.isOpen) { kb.close(); } else { kb.reveal(); };
  });
});
```

[See demo](http://jsfiddle.net/vttsfL2z/11/)

With parameter usePreview = true everything works correctly and the keyboard appears whenever you click on the icon

**Comment by Mottie** [comment]
Hi @VitBr!

Thanks for reporting this problem! I'll have it fixed shortly.

**Comment by Mottie** [comment]
Ok, try your same demo, it will work now!
<img title=":_tuzki_yesss:" src="https://cloud.githubusercontent.com/assets/136959/13203738/b38f2810-d883-11e5-9c8f-51e79116d133.gif">

**Comment by VitBr** [comment]
Amazing. Thank you very much for the quick response. It work!
