### ISSUE TITLE
Clear input text through external event

### ISSUE THREAD

**Issue by traumatic** [Mottie/Keyboard#443]
Hi,

Let's assume I have the following [code](http://jsfiddle.net/q7sou4n8/).
I now want that via an external event (e.g. the click onto a button and not through the keyboard's 'clear' button) the input text is cleared.

Anyone can help out?
Thanks!

**Comment by Mottie** [comment]
Hi @traumatic!

Get the keyboard object, then either directly clear the preview element ([demo](http://jsfiddle.net/Mottie/q7sou4n8/1/)):

```js
$('button').click(function(){
  var kb = $('#keyboard').getkeyboard();
  kb.$preview.val('').focus();
});
```

 or call the clear action key code

```js
$('button').click(function(){
  var kb = $('#keyboard').getkeyboard();
  $.keyboard.keyaction.clear(kb);
  kb.$preview.focus();
});
```

The difference between the two methods is that the `keyaction` also checks the decimal button (`{dec}`) and re-enables it, if it exists on the keyboard.

```js
// clear keyaction code
clear: function (base) {
	base.$preview.val('');
	if (base.$decBtn.length) {
		base.checkDecimal();
	}
}
```

**Comment by Mottie** [comment]
Oh, and even if the `usePreview` option is `false`, `kb.$preview` will then point to the original input, so it will be the same element as in `kb.$el`.

**Comment by traumatic** [comment]
Works great! Thanks Mottie!
