### ISSUE TITLE
Dynamically assign keyboard layout

### ISSUE THREAD

**Issue by traumatic** [Mottie/Keyboard#445]
Hi,

I want to load a different layout once a generic button is clicked.
Similar example [here](http://jsfiddle.net/Mottie/egb3a1sk/123/)
But instead of pre-defining custom1 and custom2 on global scope, I would like to assign a specific layout to the keyboard as part of the onClick event method of a button.

Is that doable?
Thanks

**Comment by Mottie** [comment]
Hi @traumatic!

All keyboards layouts need to be defined in a globally.

Can you explain what you mean by assigning a specific layout to a key... like show a different layout on click versus double click? or right click?

**Comment by traumatic** [comment]
Ah, I see. Yes, that makes sense.
I further played around with the [example](http://jsfiddle.net/zymwcbzx/) and change the keyboard settings. Unfortunately, now I cannot switch between the layouts any more.

**Comment by Mottie** [comment]
Instead of using `reveal`, use the new [`redraw` method](https://github.com/Mottie/Keyboard/wiki/Methods#redraw) ([demo](http://jsfiddle.net/Mottie/zymwcbzx/1/))

```js
$('#keyboard-a, #keyboard-b').click(function () {
    var kb = $('#searchField').getkeyboard();
    // change layout based on link ID
    kb.options.layout = this.id === 'keyboard-a' ? 'custom1' : 'custom2';
    // open keyboard if layout is different, or time from it last closing is > 200 ms
    if (kb.last.layout !== kb.options.layout || (new Date().getTime() - kb.last.eventTime) > 200) {
        kb.redraw();
    }
});
```

**Comment by traumatic** [comment]
Thanks Mottie. That works perfect!
