### ISSUE TITLE
Problem on readonly fields when the page is postbacked

### ISSUE THREAD

**Issue by gilcrespo** [Mottie/Keyboard#447]
Hi Mottie,
I'm facing a problem with the plugin when the page is postbacked.

This is how i started the plugin:
```
$('.numerico').not(':input[readonly]').keyboard({
                usePreview: false, restrictInput: true, initialFocus: false, preventPaste: true, 
                autoAccept: true, layout: 'custom', customLayout: {
                    'default': [
                        '7 8 9',
                        '4 5 6',
                        '1 2 3',
                        '0 {b} {a}'
                    ]
                }
            });
```

But when i postback, i turn into readonly the field wich has the virtual keyboard.
And execute the same code above again.

The problem:
The virtual keyboard auto opens and shows this error:
Unhandled exception at line 1330, column 5 in http://localhost:1305/javascript/jquery.keyboard.js
This object doesn't support this method or property 'replaceStr'

It only stops if i press ESC to hide the keyboard.

Could you please help on it?

**Comment by Mottie** [comment]
Hi @gilcrespo!

Hmm, I'm not sure why that error is popping up, but if you set the `useCombos` option to `false`, it should skip that block of code that is showing that error.

What input type is being used?

**Comment by gilcrespo** [comment]
The input type is set as "text"
For temporary solution i just hide the "ui-keyboard", since the error does'nt persist anymore, after to set the useCombos to false.
But my language is portuguese and combos are very usual. I'll check if i have any other situation that the same problem happebs and isn't possible to set this property to false.

By the way, thanks a lot for your support and your magnifc solution for virtual keyboard.

**Comment by Mottie** [comment]
Well, I would like to fix the error instead of using a temporary solution.

Would you modify [this demo](http://jsfiddle.net/egb3a1sk/1357/) so that the error shows up? It will make it easier for me to find the source of the problem.

**Comment by gilcrespo** [comment]
I guess this problem is very specific and hard to reproduce outsite my system. It's on aspx page and i set readonly to the fields from C# and then reload the page by code (postback). I'm not sure if my code is setting focus to this field right after the postback and before I set it to readonly...
I'll verify if it happens in another page. Otherwise i'll understand the problem is how my page was coded is contributing to this error.
