### ISSUE TITLE
How to implement with ajax loaded input fields

### ISSUE THREAD

**Issue by tezpur4u** [Mottie/Keyboard#451]
How to implement with ajax loaded

i have tried on ajax load

**Comment by Mottie** [comment]
Hi @tezpur4u!

Initialize the keyboard plugin inside the ajax success callback. I don't know what the code looks like, so here is a basic example:

```js
$.ajax({
   url: 'http://example.com',
   data: {
      format: 'json'
   },
   error: function() {
      alert('Ajax error');
   },
   dataType: 'jsonp',
   success: function(data) {
      // do something with data, and add to DOM
      // then, initialize keyboard
      $('#target').keyboard();
   },
   type: 'GET'
});
```

**Comment by tezpur4u** [comment]
without jquery ???

My Code is 

`var bustcachevar=1 //bust potential caching of external pages after initial request? (1=yes, 0=no)
var loadedobjects=""
var rootdomain="http://"+window.location.hostname
var bustcacheparameter=""

function MRRaja(url, containerid){
var page_request = false
if (window.XMLHttpRequest) // if Mozilla, Safari etc
page_request = new XMLHttpRequest()
else if (window.ActiveXObject){ // if IE
try {
page_request = new ActiveXObject("Msxml2.XMLHTTP")
} 
catch (e){
try{
page_request = new ActiveXObject("Microsoft.XMLHTTP")
}
catch (e){}
}
}
else
return false
page_request.onreadystatechange=function(){
loadpage(page_request, containerid)
}
if (bustcachevar) //if bust caching of external page
bustcacheparameter=(url.indexOf("?")!=-1)? "&"+new Date().getTime() : "?"+new Date().getTime()
page_request.open('GET', url+bustcacheparameter, true)
page_request.send(null)
}

function loadpage(page_request, containerid){
if (page_request.readyState == 4 && (page_request.status==200 || window.location.href.indexOf("http")==-1))
document.getElementById(containerid).innerHTML=page_request.responseText
}

function loadobjs(){
if (!document.getElementById)
return
for (i=0; i<arguments.length; i++){
var file=arguments[i]
var fileref=""
if (loadedobjects.indexOf(file)==-1){ //Check to see if this object has not already been added to page before proceeding
if (file.indexOf(".js")!=-1){ //If object is a js file
fileref=document.createElement('script')
fileref.setAttribute("type","text/javascript");
fileref.setAttribute("src", file);
}
else if (file.indexOf(".css")!=-1){ //If object is a css file
fileref=document.createElement("link")
fileref.setAttribute("rel", "stylesheet");
fileref.setAttribute("type", "text/css");
fileref.setAttribute("href", file);
}
}
if (fileref!=""){
document.getElementsByTagName("head").item(0).appendChild(fileref)
loadedobjects+=file+" " //Remember this object as being already added to page
}
}
}`

**Comment by Mottie** [comment]
Add your code inside the `loadpage` function:

```js
function loadpage(page_request, containerid){
  if (page_request.readyState == 4 && (page_request.status==200 || window.location.href.indexOf("http")==-1))
  document.getElementById(containerid).innerHTML=page_request.responseText
  $('#' + containerid).find('input').keyboard({
    /* add keyboard options here */
  });
}
```

**Comment by tezpur4u** [comment]
oh bro... you just saved my life...

here is the working codes

`function loadpage(page_request, containerid){
if (page_request.readyState == 4 && (page_request.status==200 || window.location.href.indexOf("http")==-1))
document.getElementById(containerid).innerHTML=page_request.responseText
$('#' + containerid).find('input').keyboard({	
    layout: 'qwerty',
    autoAccept: 'true',
    usePreview: false,
    visible: function(e, keyboard, el) {
    addNav(keyboard);},	
  });
}`

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
