### ISSUE TITLE
Virtual keyboard and retrict input

### ISSUE THREAD

**Issue by lovetoast** [Mottie/Keyboard#453]
Hi,

Quick query, for the virtual keyboard, I've disabled lockinput so a user can type using their physical keyboard but enabled restrictinput (using a custom layout with doesn't allow special characters) but this is disallowing all keyboard entry, any idea what I'm doing wrong?

Thanks!

**Comment by Mottie** [comment]
Hi @lovetoast!

When `restrictInput` is set, only the characters within the layout are allowed; but some [special keys](https://github.com/Mottie/Keyboard/blob/master/js/jquery.keyboard.js#L99-L111) (navigation, insert, delete, etc) are always allowed.

If you want to allow more keys when `restrictInput` is set, then use the [`restrictInclude` option](https://github.com/Mottie/Keyboard/wiki/Usability#restrictinclude) to include them.

If you can't get it to work, please share some of your code, or modify [this demo](http://jsfiddle.net/Mottie/egb3a1sk/) to show the problem.

**Comment by lovetoast** [comment]
Hi @Mottie 

thanks for the swift response, I'm going to take a look :)

**Comment by lovetoast** [comment]
Hi @Mottie 

Just an update, it appears that it was an issue with a previous version of virtual keyboard, or more likely, I screwed something up? It appears to be working now, so thanks for your help and the script is great btw!

**Comment by lovetoast** [comment]
Hi @Mottie 
Hope you're well!

Quick query, is it possible, after accepting the input in virtual keyboard, to focus back on the input field and reopen the keyboard? I've tried .focus() from javascript, but that doesn't seem to work, any words of wisdom you can impart?

thanks!

**Comment by lovetoast** [comment]
Or alternatively, just keep virtual keyboard open upon clicking accept? I've also tried .click()

**Comment by Mottie** [comment]
Hi @lovetoast!

You'll need to redefine the "accept" action key and set the `userClosed` option to `true`.... as follows ([demo](http://jsfiddle.net/Mottie/egb3a1sk/1433/)):

```js
$(function() {
  $.keyboard.keyaction.accept = function(keyboard) {
    // passing "true" instead of a boolean true here - related to issue #66
    keyboard.close('true');
    return false;
  };
  $('#keyboard').keyboard({
      userClosed: true
    })
    // activate the typing extension
    .addTyping({
      showTyping: true,
      delay: 250
    });
});
```

**Comment by lovetoast** [comment]
Wow, brilliant work! Might I point out one subsequent issue? This appears to have slowed down your keyboard, when it is clearing the input field there is a 0.25-0.5 second delay (btw, I haven't enabled addtyping, I don't know if this would alleviate the issue?)

**Comment by lovetoast** [comment]
And as always, thanks!

**Comment by Mottie** [comment]
Hiya @lovetoast!

Sorry for the looong delay in responding.

The .5 second delay is due to an internal `setTimeout` that is needed because clicking on a keyboard key takes focus away from the input, and therefore the script needs to add focus back to the input; but it also needs to check that the loss of focus wasn't the user actually switching to a different input or closing the keyboard.

Is there anything else, or can we call this issue resolved?

**Comment by lovetoast** [comment]
Thanks, that's fine, we've just sort of ignored the delay :)

I was wondering if you had any issues, if an input box is at the top of the page, then some of the keyboard disappears of the page?

**Comment by Mottie** [comment]
I'm not sure what you mean. I haven't heard about any issues with the keyboard disappearing.

**Comment by lovetoast** [comment]
Sorry should clarify, I mean it moves beyond the viewable area of the 
screen, I can't see the top part?

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by Mottie** [comment]
The keyboard is positioned by the optional [jQuery UI position utility](https://github.com/Mottie/Keyboard/wiki/Layout#position). If that script isn't loaded, then you would need to position the keyboard manually using CSS, or within the [`visible` callback function](https://github.com/Mottie/Keyboard/wiki/Methods#callbacks).

As an example, [this demo](https://jsfiddle.net/Mottie/qnoga7vj/) is using a jQuery UI theme but not the javascript and positions the keyboard at the bottom of the screen using css. There is also a [light](https://jsfiddle.net/Mottie/jsh0377k/) and [dark theme](https://jsfiddle.net/Mottie/6dmqhLvh/) which includes css to position the keyboard at the bottom of the screen.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
