### ISSUE TITLE
.on('change'..) triggers when closing the keyboard

### ISSUE THREAD

**Issue by softelos** [Mottie/Keyboard#457]
.on('change'...) event triggers when closing the keyboard after leaving an input field no matter if its content has changed or not. I would like this event to trigger only if the content of the widget has changed like it is supposed to be normally when not using this plugin.

**Comment by Mottie** [comment]
Hi @softelos!

You can redefine the change event, then use the `beforeClose` callback to check if the content changed, like this ([demo](http://jsfiddle.net/Mottie/egb3a1sk/1455/)):

```js
$(function() {

  // change event definition (default = "change")
  $.keyboard.events.inputChange = "";

  $('#keyboard').keyboard({
      beforeClose: function(e, keyboard, el) {
        if (keyboard.originalContent === el.value) {
          $(el).trigger('nochange');
        } else {
          $(el).trigger('change');
        }
      }
    });

  // show message if content did or did not change
  $('#keyboard').on('change nochange', function(e) {
    var msg = e.type === 'change' ? 'changed' : 'did not change';
    $('.message').html('content ' + msg);
  });

});
```

**Comment by softelos** [comment]
Thanks! this solved the problem.
