### ISSUE TITLE
Disable Mottie keyboard completely, programatically

### ISSUE THREAD

**Issue by andycampbell92** [Mottie/Keyboard#458]
Hi,

Really love the library. I would like the ability to enable and disable the virtual keyboard programatically so that we only show on the platforms that need it.

At the moment I have managed this by making a small modification to the angular wrapper.
```
			if (window.on_screen_keyboard_enabled) {			
				var newConfig = clone(VKI_CONFIG);
				config = config || {};

				for (var attr in config) {
					if (config.hasOwnProperty(attr)) {
						newConfig[attr] = config[attr];
					}
				}
				newConfig.accepted = config.accepted || inputCallback;
				var keyboard = $(element).keyboard(newConfig);

				if (keyboard && newConfig.extensions) {
					for (var extension in newConfig.extensions) {
						var extConfig = newConfig.extensions[extension];
						if (extConfig) {
							keyboard[extension](extConfig);
						} else {
							keyboard[extension]();
						}
					}
				}
			}
```

by adding the if statement I can enable and disable the keyboard on certain platforms by setting the `window.on_screen_keyboard_enabled` variable before the library is initialised. Is there a way without modifying any libraries to do this?

**Comment by Mottie** [comment]
Hi @andycampbell92!

You can use the [`toggle` method](https://github.com/Mottie/Keyboard/wiki/Methods#toggle) to enable or disable the keyboard.

```js
var keyboard = $('#myinput').data('keyboard');
// toggle the state of keyboard
keyboard.enabled = !keyboard.enabled;
// update the keyboard UI (based on keyboard.enabled)
keyboard.toggle();
if (keyboard.enabled) {
  alert('keyboard enabled');
} else {
  alert('keyboard disabled');
}
```

**Comment by andycampbell92** [comment]
Hi @Mottie,

Thanks for the quick response. My understanding of this function was that it would disable and enable keys on a keyboard. What I would like to do is disable all onscreen keyboards completely so that they do not appear on input select, as if the library was not loaded in the first place.

But then on other platforms I would like to show the keyboards. Have I misunderstood toggle?

Andy.

**Comment by Mottie** [comment]
Hmm, you're right. The `toggle` method does only enable/disable the keyboard keys and does not prevent it from showing. I guess you could always use the [`destroy` method](https://github.com/Mottie/Keyboard/wiki/Methods#destroy).

I haven't used angular that much, so I'm not sure why the modification to the angular wrapper is an issue. Or what you mean by modifying the library... the keyboard library shouldn't need to be modified.

Is there something I could add to the library to make this easier?

**Comment by andycampbell92** [comment]
Hmm perhaps I filed this issue in the wrong place, in the angular wrapper you just put a reference to the keyboard in the template e.g. `ng-virtual-keyboard="searchKeyboardConfig" id="searchKeyboard">`

The problem with this is that it will show the keyboard when the user puts their cursor in the input box regardless of platform.

I think it would be nice to have a param which can be set like so `$.keyboard.enabled = false;` which would prevent all the onscreen keyboards from showing. This would make it really simple to enable and disable on screen keyboards on certain platforms without having to change logic in each input box where a keyboard is used.

RE modifying the library it is not really a problem in itself but I use bower so it just means using my fork instead which means I won't automatically get updates (not a huge deal).

**Comment by Mottie** [comment]
Well you could set the [`openOn` option](https://github.com/Mottie/Keyboard/wiki/Usability#openon) to an empty string (default is `"focus"`), then add a keyboard icon to open the keyboard. Much like the "QWERTY Password" demo on the [main demo page](http://mottie.github.io/Keyboard/).

Otherwise, maybe @antonio-spinelli who created the [angular wrapper](https://github.com/antonio-spinelli/ng-virtual-keyboard) for this plugin might be able to help you better.

**Comment by andycampbell92** [comment]
This is the perfect solution!!!! I now do not need to modify the angular wrapper at all. For anyone else wanting to do something similar please see my code bellow:
```
        var openOnEvents = $window.on_screen_keyboard_enabled ? ['focus'] : null;
        var config = {
            layout: 'qwerty-compact',
            display: {
                'shift'   : 'caps',
                'bksp'    : 'del',
                'accept'  : 'ok',
                'meta1'   : '123',
                'normal'  : 'abc'
            },
            'openOn': openOnEvents
        };
```

By simply passing the `openOnEvents` variable to each keyboard config I can ensure that the keyboards only open when `$window.on_screen_keyboard_enabled` (the `$window` is an angular wrapper for `window`)
