### ISSUE TITLE
altkeyspopup extension and userPreview:false = problem

### ISSUE THREAD

**Issue by arius28** [Mottie/Keyboard#460]
Hey Mottie,

I just came upon the following issue.

When using the altkeyspopup extension with the option `usePreview: false` the extension popup will show up fine the first time, but after you accept and reopen the keyboard the extension popup never comes up again. If I set the keyboard to `usePreview: true` then the popup with the extra characters comes up every time.

Here's a fiddle:
http://jsfiddle.net/8cej0pn6/

**Comment by Mottie** [comment]
Hi @arius28!

Thanks for reporting this problem! I'll look into it when I get some free time.

**Comment by Mottie** [comment]
Wow, sorry, I totally forgot about this issue :disappointed:.. I'll make sure to include a fix in the next update.

**Comment by Mottie** [comment]
Sorry it took so long!
