### ISSUE TITLE
Using the keyboard on dynamically created elements?

### ISSUE THREAD

**Issue by asevims** [Mottie/Keyboard#461]
Hello,

Thank you very much for this great work!

I need to use this keyboard on dynamically created elements. Though I didn't have success on it. I always get the following error: 
.keyboard is not a function. keyboard' is undefined) at ...

 "Could you help me please?

Thanks in advance.

**Comment by Mottie** [comment]
Hi @asevims!

Please initialize the keyboard after the element has been generated. I may be able to help if the code used to create and initialize the keyboard were shared.

**Comment by asevims** [comment]
Thank you very much for your fast response! 

Here is the part of my code:

$("#frameID").append('<textarea class="tastatur"></textarea>');

$("#frameID").on("click", ".tastatur", function() {
	$(".tastatur").keyboard();
});

**Comment by asevims** [comment]
Thank you very much for your fast response!

Here is the part of my code:

```
$("#frameID").append('');

$("#frameID").on("click", ".tastatur", function() {
$(".tastatur").keyboard();
});
```

**Comment by asevims** [comment]
Sorry, inside the append I'd a textarea element with the class name "tastatur". I disappeared by copying the code.

**Comment by Mottie** [comment]
Oh, is the input being added inside an iframe?

**Comment by asevims** [comment]
No, does it make a difference? I'm using dojox framework and want to use the keyboard on the dojox canvas.

**Comment by Mottie** [comment]
Please check the following:

* Is jQuery being loaded more than once?
* How is the script loaded? Make sure it is loaded by checking if `$.keyboard` is defined.

**Comment by asevims** [comment]
Yes, jQuery is beeing loaded once. 

All right. I'll try it. Thank you very much!

**Comment by asevims** [comment]
Somehow the jquery.keyboard.js couldn't be loaded. Now I figured out how to load it correctly. Many thanks for your efforts!
