### ISSUE TITLE
Keyboard doesn't show for widgets in Bootstrap modal dialogs

### ISSUE THREAD

**Issue by softelos** [Mottie/Keyboard#462]
The dialog box is enabled from the same javascript that binds the keyboard to all inputs. The keyboard works perfectly for all inputs in the visible HTML but not for the invisible one that gets enabled when needed (pop up dialog box).

**Comment by Mottie** [comment]
Hi @softelos!

Please modify [this demo](http://jsfiddle.net/Mottie/MK947/1837/) to help me understand the problem.

**Comment by softelos** [comment]
Thanks for the response @Mottie !

I've update the [fiddle](http://jsfiddle.net/MK947/4326/) . As you can see when you press the button, the keyboard doesn't work for the input elements in the modal dialog.

**Comment by Mottie** [comment]
Because the dialog is being created using `message: $('div#wrap').html()`, you'll need to use a delegated bind on the `document` so the script knows when the modal is open and that the keyboard plugin needs to be initialized ([demo](http://jsfiddle.net/Mottie/MK947/4328/)):

```js
$(document).on('shown.bs.modal', '.modal', function() {
  $('.modal input').keyboard({
      layout: 'qwerty',
      css: {
        // input & preview
        input: 'form-control input-sm',
        // keyboard container
        container: 'center-block dropdown-menu', // jumbotron
        // default state
        buttonDefault: 'btn btn-default',
        // hovered button
        buttonHover: 'btn-primary',
        // Action keys (e.g. Accept, Cancel, Tab, etc);
        // this replaces "actionClass" option
        buttonAction: 'active',
        // used when disabling the decimal button {dec}
        // when a decimal exists in the input area
        buttonDisabled: 'disabled'
      },
      usePreview: false
    })
    // activate the typing extension
    .addTyping({
      showTyping: true,
      delay: 50
    });
}).on('hide.bs.modal', '.modal', function() {
  // remove keyboards to free up memory
  $('.modal input').each(function() {
    $(this).data('keyboard').destroy();
  });
});

$('button#dialogButton').on('click', function() {
  bootbox.dialog({
    title: 'User Registration',
    message: $('div#wrap').html(),
    buttons: {
      save: {
        label: 'Save',
        class: 'btn-success'
      },
      cancel: {
        label: 'Cance',
        class: 'btn-default'
      }
    }
  });
});
```

And you'll need this css to override bootstrap's definition:

```css
div.ui-keyboard {
  z-index: 2000;
}
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
