### ISSUE TITLE
Prototype.js error: Uncaught TypeError: eventName.include is not a function

### ISSUE THREAD

**Issue by dgunwin** [Mottie/Keyboard#463]
I experienced a bug when using the Keyboard plugin alongside Prototype.js.  I thought I would put my solution here, in case anyone else has the same problem in the future.

Prototype was giving the following error:
**"Uncaught TypeError: eventName.include is not a function"**

I tracked the error down to following line of code inside the 'base.close' method of the Keyboard plugin:
**.trigger((o.alwaysOpen) ? '' : kbevents.kbBeforeClose, [base, base.el, (accepted || false)])**

The reason Prototype was throwing the error was because of the empty string event (the error only happens when alwaysOpen is set to true).

To fix the error I just added another event called 'nullEvent' to the $keyboard.events object.

Then I modified your line of code like this:
**.trigger((o.alwaysOpen) ? kbevents.nullEvent : kbevents.kbBeforeClose, [base, base.el, (accepted || false)])**

There might be a better solution, but this seemed to work for me.  The main point is the Prototype does not like the event being an empty string.

Hope it helps someone in the future.

**Comment by Mottie** [comment]
Hi @dgunwin!

Thanks for reporting this issue. I'll have a fix applied to the master branch here shortly. If you are using a package system, it won't be available until the next release.

**Comment by Mottie** [comment]
Wow, GitHub is experience some update delays. I think I'll go ahead and push the next release. Hopefully GitHub will catch up.

**Comment by dgunwin** [comment]
Thanks a lot for your quick response Mottie, and for the update.

And thanks a lot for your Keyboard plugin - it's really good, and saved me a lot of time.  Really appreciate it.
