### ISSUE TITLE
keyboard cannot be init in IE 11

### ISSUE THREAD

**Issue by alau731** [Mottie/Keyboard#465]
If the document mode of IE 11 is set to IE 8, the error is occurred.
i tested on the demo page http://mottie.github.io/Keyboard/, it still get the same result.

I opened the developer tools of IE, the error of demo.js is following:
{exception}	Object doesn't support property or method 'keyboard'

In the console, it shows another error File: jquery.keyboard.js, Line: 110, Column: 6

**Comment by Mottie** [comment]
Hi @alau731!

Well, IE8 shouldn't be an issue any longer. [Microsoft has dropped support](http://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support) for IE8, IE9 and IE10, so you shouldn't need to worry about it anymore.

If you *must* support it, I don't see where the error actually is occurring as [line 110](https://github.com/Mottie/Keyboard/blob/master/js/jquery.keyboard.js#L110) of the file is in the middle of an array.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
