### ISSUE TITLE
composer package

### ISSUE THREAD

**Issue by str** [Mottie/Keyboard#466]
Hi. First of all, thank you for this great library.

I was importing your library in a project, using cloudflare CDN. I don't like to download libraries because they get updated online and then nobody remembers to update the  downloaded library. That's why I was using the CDN, but now the project will be used in a computer with no internet connection. 

I was looking for an easy way to get your library and still be able to update to the latest version very easy. I found I was able to do that with [composer](https://getcomposer.org/).  I was able to find most of the libraries there (jquery, jqueryUI, bootstrap, and others I use in that project), but not yours.

Can you please add your package to https://packagist.org/

Thank you.

**Comment by Mottie** [comment]
Hi @str!

Thanks for letting me know. I'll look into adding a `composer.json` file. I just need to make sure I'm adding all the required information.

**Comment by Mottie** [comment]
Ok, now I just need to figure out how to get the autoupdate working...

https://packagist.org/packages/mottie/keyboard

**Comment by str** [comment]
GREAT!

**Comment by Mottie** [comment]
New release is available! Please verify that it's all working as expected. Thanks!

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
