### ISSUE TITLE
Using destroy() will remove every class associated to the element.

### ISSUE THREAD

**Issue by geppos** [Mottie/Keyboard#469]
Hello,
is it normal that when using destroy() all the classes of the input element are removed?
Thanks a lot

**Comment by Mottie** [comment]
Hi @geppos!

It should only be removing classes added by the keyboard plugin - see [this demo](http://jsfiddle.net/Mottie/egb3a1sk/1672/).

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
