### ISSUE TITLE
Catch the users input from his physical keyboard

### ISSUE THREAD

**Issue by Brotzka** [Mottie/Keyboard#470]
Hey hey!

Is it possible, to catch the input, the user does over his physical keyboard? For example my physical keyboard is english and the the virtual is swedish. So the key "[" on my physical keyboard is "å" on the virtual keyboard. So if I hit "[" on my keyboard, in my textarea should appear a "å". Is that possible? That's the way it works on Google Translate and it would be excellent if your package would support this!! 😃

**Comment by Mottie** [comment]
Hi @Brotzka!

If you look at the ["Custom: Mapped Keys" demo](https://mottie.github.io/Keyboard/#map) on the main demo page. You'll see that you can remap physical keyboard keys to the virtual keyboard. Click on the title of that keyboard, then scroll to the bottom of the page to see the example code.

**Comment by Brotzka** [comment]
Great, thank you! But is it possible to pass in a whole language so I don't have to hard code every single letter?

**Comment by Mottie** [comment]
There isn't a current method; but I am open to ideas on how to implement something like that. Either way I would think that every single letter would still need to be defined.

**Comment by Mottie** [comment]
In the latest release I added a [`beforeInsert` callback function](https://github.com/Mottie/Keyboard/wiki/Methods#beforeinsert). With it you can essentially map the entire keyboard to whatever characters you want.

For example, [here is a simple demo](https://jsfiddle.net/Mottie/xkk95vf6/) remapping a qwerty layout to enter a Greek alphabet:

```js
$(function() {

  var remapGreek = {
    "A": "Α",
    "B": "Β",
    "D": "Δ",
    "E": "Ε",
    "H": "Η",
    "I": "Ι",
    "K": "Κ",
    "L": "Λ",
    "M": "Μ",
    "N": "Ν",
    "O": "Ο",
    "P": "Π",
    "R": "Ρ",
    "S": "Σ",
    "T": "Τ",
    "X": "Χ",
    "Y": "Υ",
    "Z": "Ζ",
    "F": "Φ",
    "G": "Γ",
    "J": "Ξ",
    "C": "Ψ",
    "V": "Ω",
    "U": "Θ",

    "a": "α",
    "b": "β",
    "d": "δ",
    "e": "ε",
    "h": "η",
    "i": "ι",
    "k": "κ",
    "l": "λ",
    "m": "μ",
    "n": "ν",
    "o": "ο",
    "p": "π",
    "r": "ρ",
    "s": "σ",
    "t": "τ",
    "x": "χ",
    "y": "υ",
    "z": "ζ",
    "f": "φ",
    "g": "γ",
    "j": "ξ",
    "c": "ψ",
    "v": "ω",
    "u": "θ"
  };

  $('#keyboard').keyboard({
      layout: 'qwerty',
      beforeInsert: function(e, keyboard, el, textToAdd) {
        return remapGreek[textToAdd] || textToAdd;
      }
    });
});

```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
