### ISSUE TITLE
General usage of on-screen keyboard when keypress

### ISSUE THREAD

**Issue by Bobeta** [Mottie/Keyboard#475]
Hi folks and thanks for this great library, amazing work!

I have been playing around with it a bit and was thinking of a use case scenario where the user presses a key and the virtual keyboard pops up. Instead of it being bound to a specific form element (like #keyboard in the examples), I'd like to have use it as a general virtual keyboard on the body or window in js. I was thinking something along the line if someone presses k then it should pop up and can be used overall on the page. This is what I've tried so far:

$(document).ready(function($) {
					$('body').on('keypress', function(e) {
						console.log(e);
						if(e.keyCode == 107) {
							$('.keyboard').keyboard(options);
						}
					})
				});

However, I can't seem to get this approach to work. Could someone guide me in the right direction? Thanks!

**Comment by Mottie** [comment]
Hi @Bobeta!

The keyboard currently *must* be associated with either an input or textarea. You'll need to include one even if it's hidden.

The `keyCode` for the Numpad <kbd>+</kbd> is actually `43`. The value of `107` is the value you get from converting it to a character code:

```js
String.fromCharCode(43);
// 107
```

Or am I mistaken as to which key you wanted to use?

Anyway, [here is a demo I set up](https://jsfiddle.net/Mottie/egb3a1sk/1742/). It is essentially the same as the "Custom: Hidden" demo on the [main demo page](https://mottie.github.io/Keyboard/).

HTML

```html
<h3 class="target">Press Numpad + to open keyboard</h3>
<!-- IE doesn't work with <input type="hidden"> -->
<input id="keyboard" type="text" />
```

CSS

```css
#keyboard {
  display: none;
}
```

JS

```js
$(function() {
  // initialize the keyboard first
  var $kb = $('#keyboard').keyboard({
      layout: 'qwerty',
      position: {
        of: $('.target'),
        my: 'center top',
        at: 'center top+20'
      }
    })
    // activate the typing extension
    .addTyping({
      showTyping: true,
      delay: 250
    });

  $('body').on('keypress', function(e) {
    // 43 = e.which code for numpad +
    // 107 = String.fromCharCode(43);
    if (e.which === 43) {
      $kb.getkeyboard().reveal();
    }
  });
});
```

**Comment by Bobeta** [comment]
Thanks for the detailed answer and the great examples! That's really interesting, what is the reason that it needs to be associate with an input or textarea? Does that mean that the key entries are only entered in that input/textarea? 

I would like to have an overall on screen keyboard, lets say for navigation purposes of the site, so it shouldn't be tied to a specific input.

**Comment by Mottie** [comment]
That's just the way it is written right now. In the future, if I ever get time to rewrite the plugin, I'll get it working with contenteditable elements and binding to the document (see #208).

**Comment by Bobeta** [comment]
Alright, thanks for the explanation and kind help! Does that mean that the on screen keyboard will only enter keystrokes to the input that it's bind to?

**Comment by Mottie** [comment]
Yes

**Comment by Bobeta** [comment]
I figured, thanks for the help! :)
