### ISSUE TITLE
Can't move caret position when input is of type email

### ISSUE THREAD

**Issue by Stenvdb** [Mottie/Keyboard#479]
I have tested this in the playground provided on the website and made a fork of it:
https://jsfiddle.net/7zzszb1e/1/

**Comment by Mottie** [comment]
Hi @Stenvdb!

Please see #241.

**Comment by Stenvdb** [comment]
@Mottie This can be closed, I have made a workaround for this by using a dummy input with type=text instead of email (or number) since they don't support the selectionStart property.
