### ISSUE TITLE
Bug with virtual keyboard in an EPUB

### ISSUE THREAD

**Issue by BenMantalo** [Mottie/Keyboard#483]
Hello,
I am developping an application (JS/HTML/CSS) in an EPUB. I'm using your library and (almost) all is ok !
Just one problem : 
I use the virtual keyboard in an input, then I use the real keyboard and it doesn't write in the input.
If I use the real keyboard first, it works ...
Any ideas ??
My code : 

``` js
$('.BlocCompletion input').keyboard({
    language: 'fr',
    layout: 'custom',
    customLayout: {
      'default' : touches
    },
    autoAccept: true,
    autoAcceptOnEsc: true,
    usePreview: false,
    beforeVisible: function(event, keyboard, el){
      $('<span class="close_keyboard">x</span>').prependTo('.ui-keyboard');
      $('.close_keyboard').click(function(){
        $('.ui-keyboard').getkeyboard().close();
      });
    },
});

```

Thanks,
Best regards.

**Comment by Mottie** [comment]
Hi @BenMantalo!

Are there any other scripts binding to the input? Does clicking inside the input open the keyboard?

Hmm, I'm not sure what else to ask you to check. If there is any way you can duplicate the problem in a [jsFiddle](http://jsfiddle.net/Mottie/egb3a1sk/), I would be able to better help you.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
