### ISSUE TITLE
Bug in keyboard with maxlenght option set to a value

### ISSUE THREAD

**Issue by apod42** [Mottie/Keyboard#485]
Steps to reproduce this:

1. Use Custom:Hex keyboard on demo page
2. Enter C D E F 8 9. At this point no more text can be entered, normal behaviour
3. Using left arrow key move the text caret after the first letter C
4. Enter 0 0 0 0 0
5. See how D E F 8 9 is replaced with 0 0 0 0 0

Is this normal behaviour? Looks like a bug. On step 4 I think when I try to enter 0 0 0 0 0 nothing should happen. My original text should not get replaced.

**Comment by Mottie** [comment]
Hi @apod42!

There is a [`maxInsert` option](https://github.com/Mottie/Keyboard/wiki/Usability#maxinsert) that is set to `true` by default. If you set it to `false`, the user will not be allowed to insert characters. They would have to use the backspace key to remove a character before being allowed to enter another - [demo](http://jsfiddle.net/Mottie/egb3a1sk/1910/).

**Comment by apod42** [comment]
Thank you! I should have read the doc more carefully..

**Comment by Mottie** [comment]
No problem, I know the documentation could use some improvement.
