### ISSUE TITLE
how to add extra keys

### ISSUE THREAD

**Issue by jlariza** [Mottie/Keyboard#487]
Hello,

I need to know if there is a way to add extra keys that are mapped to a custom value.

For example, add a key "username" that when I click it ,it adds "jariza" to the input text field. (and it is no mapped to the real keyboard)

Thank you

**Comment by Mottie** [comment]
Hi @jlariza!

First you'll need to set the [`layout` option](https://github.com/Mottie/Keyboard/wiki/Layout#layout) to `"custom"`, then add a layout with your custom key(s) into the [`customLayout` option](https://github.com/Mottie/Keyboard/wiki/Layout#customLayout).

Next you'll need to [add an action key](https://github.com/Mottie/Keyboard/wiki/Actions#addaction).

I set up [this demo](http://jsfiddle.net/Mottie/egb3a1sk/1926/) with a `{username}` key that grabs the user name from a data-attribute of a div with the class name "login-name". It can get the value from anywhere.

**Comment by jlariza** [comment]
@Mottie wow! Thank you very much. It is just what I was looking for. Thank you again :)

**Comment by Mottie** [comment]
You're welcome!

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
