### ISSUE TITLE
TabNavigation issue on  Select(dropdown) control from Input keyboard control

### ISSUE THREAD

**Issue by maharazhar** [Mottie/Keyboard#489]
/_! jQuery UI Virtual Keyboard v1.26.4 *//_
When you press tab button from input which has instance of keyboard, the focus get to next control, that is working good, but in case the next control is drop down, it ignores that dropdown, and navigate to next button or input or textarea or a tag control.
I found that fix by changing code at line # 1476 `all = $('button, input, textarea, a')`
to `all = $('button, input, textarea, select, a')`

Is it good fix?

**Comment by Mottie** [comment]
Hi @maharazhar!

Sorry it has taken me so long to respond! Yes, adding "select" to that binding would be a good fix. I'll have it available in the next update!
