### ISSUE TITLE
Remove keys & Open keyboard automatically

### ISSUE THREAD

**Issue by pilonscv** [Mottie/Keyboard#49]
Hello,

It is possible remove some keys?  how?

It is possible have the keyboard open... everytime open... when we go to the page see the keyboard without click.

**Comment by pagodzik** [comment]
So, to hide ONE key I have to do all keyboard layout?
There is no option in display like:
'tab':false
?

**Comment by Mottie** [comment]
Sorry, no... but I will consider including something like that once I get around to updating this library.
