### ISSUE TITLE
 scramble with 2 custom keyboards 

### ISSUE THREAD

**Issue by ohohyeah** [Mottie/Keyboard#493]
hello, 

I had 2 custom keyboards need to implement, but there is some problem :
For the first time to click one of them , it will show a keyboard  correctly,
but when you click the another one, it  will show the previous keyboard.

there is the scenario of it 
https://jsfiddle.net/2egko5wt/

thank you for reading this.

**Comment by Mottie** [comment]
Hi @ohohyeah!

Thanks again! I'll push a new release very soon!
