### ISSUE TITLE
Input locked when keyboard is closed

### ISSUE THREAD

**Issue by mysiki** [Mottie/Keyboard#495]
Hello,

First, thanks for this great job. :D 

I have a issue (?), with my setup, when I close the keyboard the input (from hardware keyboard) don't work... It's seems to be link with the Preview (false). 

I use a button for open the visual keyboard. 

When I load the page, I can write with the physical keyboard. After I open the visual keyboard, all keep ok (hard and visual keyboard). Then I close the visual keyboard and I cannot write anything more... I can write again only when the visual keyboard is open ... 

I have try with the lockinput:false option, but no change. 

Nota : Just testing, when I enable the preview I have no issue ... 

If you can help me please :D 

My code : 

$("#cab").keyboard({ 
    layout : "custom",
    customLayout: {
      "normal" : ["1 2 3", "4 5 6", "7 8 9", "0 {b} {a}"],
    },
    position : {
      // null (attach to input/textarea) or a jQuery object (attach elsewhere)
      of : $("#tablehaut"),
      my : "right bottom",
      at : "right top",
      // at2 is used when "usePreview" is false (centers keyboard at the bottom
      // of the input/textarea)
      at2 : "right top"
    },
    //caretToEnd : true,
    **usePreview : false,
    autoAccept : true,
    openOn : null,**
});

//Keyboard button
$("#keyboardimg").click(function() {  
    var kb = $("#cab").getkeyboard();
    kb.reveal();
});

**Comment by mysiki** [comment]
Good, your change work with my setup. Thanks.

**Comment by emondora** [comment]
same issue...
