### ISSUE TITLE
Custom layouts and keyboard set change on start.

### ISSUE THREAD

**Issue by darkgnostic** [Mottie/Keyboard#498]
After initializing keyboard with custom layouts, is it possible to show keyboard with specific custom set?

Like in iPad keyboard layout on your example site, can the keyboard be shown initially with 'meta1' set  instead of 'normal' set.

**Comment by Mottie** [comment]
Hi @darkgnostic!

You can use the [`beforeVisible` callback](https://github.com/Mottie/Keyboard/wiki/Methods#beforevisible) to use the [`showKeySet` method](https://github.com/Mottie/Keyboard/wiki/Methods#showkeysetmeta) to set the initial keyset - [demo](http://jsfiddle.net/Mottie/egb3a1sk/2064/).

**Comment by darkgnostic** [comment]
Incredibly fast response 👍  Thank you

**Comment by darkgnostic** [comment]
If I define keyboard like this:

`/* VIRTUAL KEYBOARD DEMO - https://github.com/Mottie/Keyboard */
$(function() {

  $('#keyboard').keyboard({
      layout: 'international',
      alwaysOpen: true,
      usePreview: false,
      beforeVisible: function(e, keyboard, el) {
        keyboard.showKeySet('shift+alt');
      }
    })
    // activate the typing extension
    .addTyping({
      showTyping: true,
      delay: 250
    });

		$('#keyboard').getkeyboard().reveal();
});
`

then it isn't working.

**Comment by Mottie** [comment]
Don't include `$('#keyboard').getkeyboard().reveal();`, it is already done when `alwaysOpen` is `true`.

**Comment by darkgnostic** [comment]
I had some issues with visibility of the built keyboard, that's why I have included reveal(), but don't remember exact nature of the problem. Ok, I will remove reveal. 

Thank you.

**Comment by darkgnostic** [comment]
Still wont work, :(

```js

$('#keyboard').keyboard({
  		alwaysOpen: true,
      layout: 'custom',
      customLayout: {
        'normal': [
          'q w e r t z u i o p {bksp}',
          'a s d f g h j k l {enter}',
          'y x c v b n m . ö ä ü ß',
          '{s} {space} _ - {s}'
        ],
        'shift': [
          'Q W E R T Z U I O P {bksp}',
          'A S D F G H J K L {enter}',
          'Y X C V B N M . Ö Ä Ü ß',
          '{s} {space} _ - {s}'
        ],
        'nummer': [
          '7 8 9',
          '4 5 6',
          '1 2 3',
          '0 {bksp} {enter}'
        ]
      },
                
      beforeVisible: function(e, keyboard, el) {
        keyboard.showKeySet('nummer');
      }
    });
```

although shift set will appear, but nummer will not. Am I missing something else?

**Comment by darkgnostic** [comment]
Ah, if I change nummer to meta1 and it will work.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
