### ISSUE TITLE
Closing keyboard (accept/cancel/or clicking outside) closes bootstrap modal

### ISSUE THREAD

**Issue by dustinbolton** [Mottie/Keyboard#501]
I am using the keyboard inside a Bootstrap modal. Everything displays and works properly EXCEPT whenever the keyboard closes it also closes my modal. The dimming background stays around but the modal container in my body is destroyed.  Is this is a bug?

**Comment by Mottie** [comment]
Hi @dustinbolton!

It sounds like it might be an issue! It would make it easier for me to troubleshoot if you would provide me a demo. Please [modify this demo](http://jsfiddle.net/Mottie/egb3a1sk/) to duplicate the problem.

**Comment by dustinbolton** [comment]
@Mottie It seems the problem is that closing the keyboard is triggering the hidden.bs.modal event which I use to destroy generated modals from my DOM. So the modal closing is a side effect in my code of that event being unexpectedly triggered. See http://jsfiddle.net/egb3a1sk/2143/

Is this intentional or do you know a way to prevent that from being triggered when closing the keyboard? Thanks so much!

**Comment by Mottie** [comment]
Ok, I found the problem.

When the keyboard is closed, a "hidden" event is triggered on the input. Bootstrap sees this and fires off the `hidden.bs.modal` event.

To fix this, change the keyboard default triggered "hidden" event as follows ([demo](http://jsfiddle.net/Mottie/egb3a1sk/2144/))

```js
/* prevent keyboard from closing Bootstrap modal */
$.keyboard.events.kbHidden = "keyboardHidden";
```

I'll rename all the triggered events once I get some time to rewrite this plugin in plain JS... hopefully soon.

**Comment by dustinbolton** [comment]
Thanks so much, it's working perfectly for me now. Best wishes and thanks for the hard work on this great library!

**Comment by AnReZa** [comment]
I'm still having this issue with the most recent version. The workaround provided by @Mottie still works, though. Hasn't it been fixed yet?

**Comment by Mottie** [comment]
What is there to fix? I think the problem is with Bootstrap performing an action when a `hidden` event, versus a `hidden.bs.modal` event occurs.

**Comment by AnReZa** [comment]
Haven't you announced, that you are going to rename all the triggered events back in late 2016?

**Comment by Mottie** [comment]
I might have; but doing so would require a major release to indicate that the change is not backwards compatible.  And my plan for the next major release is to rewrite this library in plain JS. I've been terribly busy, so I haven't had much time to continue work on it.

And I was incorrect in blaming bootstrap. The problem is actually jQuery and how it uses periods in the event to name space. So yes, changing the event to `keyboardHidden` would be the best solution.

**Comment by AnReZa** [comment]
Thank you very much. I just changed it according to your workaround and it works just fine. I just thought, that you would already have renamed it, when you closed this ticket.

Thank you again for all your good work. Your keyboard plugin works perfectly for my project (Raspberry Pi with Raspian + touch monitor).
