### ISSUE TITLE
Switch layout vs show keyset

### ISSUE THREAD

**Issue by tobiasvandriessel** [Mottie/Keyboard#502]
It's probably a strange question, but performance-wise, what is faster considering a layout of 10 rows and 17 columns, Switching the Layout or Showing a different KeySet? And please do tell me if there's a better way to ask such questions.

**Comment by Mottie** [comment]
Hi @tobiasvandriessel!

I haven't done any performance testing, but switching keysets is going to be faster since the HTML is already present in the DOM and only the display setting is modified.

When you switch a layout, it needs to build the HTML, if not already built. If the layout has been built, it clones the stored keyboard and makes any necessary additions like adding a preview and adding a hidden element to measure scroll position.

Have you encountered an issue where one is much slower than the other?

**Comment by tobiasvandriessel** [comment]
Hi @Mottie, again thanks for your quick reply! My expectations were indeed that you handled the switching of keysets in a smarter way than just rebuilding the whole keyboard, but I had no way of confirming as a lot of your JavaScript code looks like a big soup to me haha.

I was asking because I need to handle some mobile or simply low-powered devices and wouldn't like wasting precious client's time :p

Consider the issue closed :)

**Comment by Mottie** [comment]
LOL yeah, it is a mess. I plan on rewriting the code soon-ish...

**Comment by tobiasvandriessel** [comment]
Oh sorry, it was in no way meant as a negative remark, I'm just to C# and thus a JavaScript noob :p Nonetheless, if you as well think it's a mess and you have the time, it might just be beneficial. The next question will be very off topic, so feel free not answer. You seem quite experienced with JavaScript and JQuery, how do you view TypeScript and its types? Do you plan on using it in your next project?

**Comment by Mottie** [comment]
I've never used TypeScript, so probably not LOL! Do you think it's worth learning?

**Comment by tobiasvandriessel** [comment]
Haha me neither, but for me it's a nice wrapper around Javascript, with the types making programming and debugging more manageable. I truly wouldn't know whether learning it is worth it, but recently there was quite some momentum behind it, so I was very curious about your view on the introduction of types given your experience.

**Comment by Mottie** [comment]
FYI, in v1.26.8, I added a new parameter to the `redraw` function that allows quick layout switching for the main keyboard:

```js
keyboard.redraw("new_layout");
```

The `keyboard` object is provided within callback functions and action key functions; or you can access it any time using:

```js
var keyboard = $("#keyboard").data("keyboard");
```

**Comment by tobiasvandriessel** [comment]
Ah very nice, compacter code! 
Thanks! I'm starting to figure it all out xD
