### ISSUE TITLE
Getting current KeySet

### ISSUE THREAD

**Issue by tobiasvandriessel** [Mottie/Keyboard#504]
Hi @Mottie,

One last question: Is it possible to get the current active keyset?

**Comment by Mottie** [comment]
Hi @tobiasvandriessel!

Yes, it's not built in, maybe it should be, but you can use the "keysetChange" event to check ([demo](http://jsfiddle.net/egb3a1sk/2153/)):

```js
$(function() {

  $('#keyboard')
    .keyboard({
    	layout: "international"
    })
    .on('keysetChange', function(event, keyboard, element) {
      // keyset changes before keyboard is visible
      if (keyboard.isVisible()) {
        var keyset = keyboard.$keyboard.find('.ui-keyboard-keyset:visible');
        console.log("current keyset = " + keyset.attr('name'));
      }
    });

});
```

**Comment by tobiasvandriessel** [comment]
Ah thanks! That's exactly what I needed! :) Btw, can there be any more customLayouts and can the alternative keysets have names different from shift and metaX? Right now I use 3 layouts (probably going to trim that using the keysets, so using natural names instead of metaX might just come in handy) using `$.keyboard.layouts.NAME = {"default" : []}', which you strongly advise against haha.

**Comment by Mottie** [comment]
The `meta1`, `meta2`, .... `metaN` naming are only used internally by the plugin. You can change what is displayed using the `display` option... see the [docs](https://github.com/Mottie/Keyboard/wiki/Layout#meta) on how to define meta keys.

**Comment by Mottie** [comment]
Actually, the way the code is set up, you could add a underscore in the meta key name to describe it... something like `meta0_symbols` or `meta1_greek_alphabet` - see http://jsfiddle.net/egb3a1sk/2158/

**Comment by tobiasvandriessel** [comment]
Ah nice, that's really useful! I didn't realize that this was the way to go as I used the different layouts initially. Thanks again! :)

**Comment by Mottie** [comment]
I just released v1.26.8, and you can now name the meta keys as follows:

* `meta0` (still allowed), `metakeys`, `meta_symbols`, `meta-greek`.
* The name **must** always start with `meta` followed by any of the following characters `A-Za-z0-9_-`.

Sadly, I was going to add a new `getKeySet` function which would return the current keyset, but I forgot <img title=":_drunk:" src="https://cloud.githubusercontent.com/assets/136959/13512352/ab7bd68e-e15f-11e5-8475-64f2678be28e.gif">

**Comment by tobiasvandriessel** [comment]
Ah very nice! More freedom :)

Haha, don't worry about it, it's a small thing really :p

**Comment by Mottie** [comment]
Done!

<img title=":_badger:" src="https://cloud.githubusercontent.com/assets/136959/13512240/15d31412-e15f-11e5-8577-06cff0976977.gif">

**Comment by tobiasvandriessel** [comment]
Aw yeah! :D
