### ISSUE TITLE
Can't open the keyboard progamatically

### ISSUE THREAD

**Issue by willrbaar** [Mottie/Keyboard#509]
I've been trying to use your keyboard.  I have been able to set up the basic scenario where I have the element  

`*"<textarea type="hidden" id="keyboard" placeholder="Enter Text..."></textarea>"*
`
 `set up and I click on it and the keyboard appears.

I am having a hard time getting beyond this point.  I have tried to use your example code under your usage section to open the keyboard programmatically.  I have used your example and included
`<button class="open">Open Keyboard</button> `
in  a division,

 and the following code under script:
```
$('button.open').click(function(){
  $('#keyboard').getkeyboard().reveal();
});

```
I even did a:  
  "  ` var keyboard = $('#keyboard').getkeyboard()`;     
[MottieKeyboardProblem.txt](https://github.com/Mottie/Keyboard/files/692448/MottieKeyboardProblem.txt)

to  make sure I had an object to work with.

The problem I am having is that the DOM tells me that  the:    "Object doesn't support property or method 'getkeyboard'".  I have tried a lot of stuff, but nothing works.  I am new to working in javascript and I must be doing something wrong.  I've attached a copy of my code.

**Comment by Mottie** [comment]
Hi @willrbaar!

It sounds like the keyboard hasn't been initialized yet... make sure to use this code before attempting to programmically open the keyboard:

```js
$(function() {
  $('#keyboard').keyboard();

  // now this code should work
  $('button.open').click(function(){
    $('#keyboard').getkeyboard().reveal();
  });
});

**Comment by willrbaar** [comment]
Rob:  Thanks for the quick response.  I’m not very familiar with JavaScript and I appreciate your help.  One of the things I was wondering is if I am getting an empty object back when we try to initialize?
  I used your code as is, and got the following response from the browser
 
.....”jQuery.Deferred exception: Object doesn't support property or method 'keyboard' TypeError: Object doesn't support property or method 'keyboard' at Anonymous function”.
 
I modified your code as follows to try to get away from an anonymous function, but it comes back with...”Unable to get property 'getkeyboard' of undefined or null reference”
 
<script >
     
        var keyboard= function () {
            $('#keyboard').keyboard();};
 
    
    $('button.open').click(function () {
        $('#keyboard').keyboard.getkeyboard().reveal();
    });
.........
Thanks for your help.

**Comment by Mottie** [comment]
Oh, that isn't an anonymous function, it is a callback on jQuery's document ready function... Now it sounds like jQuery isn't being loaded.

Please make sure you are using jQuery v1.4.3 or newer (preferred), and that it is loading before the keyboard plugin.

**Comment by Mottie** [comment]
Oh, I guess I missed the `txt` file you included... I use the HTML from there to create the following demo that doesn't appear to have any issues:

http://jsbin.com/siboyakaki/edit?html,output

**Comment by willrbaar** [comment]
Rob:  I wanted to let you know that the problem was probably on my side.  I finally got it working.  The problem appears to be some form of conflict with jquerry on my system.  I’m using Visual Studio 2015 and Microsoft uses jquerry in other spots on my application.  I had made the changes on my software you had done in your HTML file, and the problem was still there.  So after much Googling and attempted fixes, I found a fix.  It is relatively simple.  Just need to making sure that the $ sign is strictly complied to.  Just assign ‘use strict’ to an anonymous function.  See below for the fix.  Thanks again for your help.  
 
(function ($) {
        'use strict';
 
        $(function () {
            var keyboard = $('#keyboard').getkeyboard();
 
        });
        $('#getkeys').click(function () {
            var keyboard = $('#keyboard').getkeyboard();
 
            keyboard
            .reveal()
            .insertText('Anybody want a peanut?')
            // added in v1.26.8; insertText returns the keyboard object
            // this will trigger the change event on the original input
            .$el.trigger('change');
        });
    })(jQuery);

**Comment by Mottie** [comment]
The code can be simplified into:

```js
jQuery(function ($) {

  var keyboard = $('#keyboard').getkeyboard();

  $('#getkeys').click(function () {
    var keyboard = $('#keyboard').getkeyboard();

    keyboard
    .reveal()
    .insertText('Anybody want a peanut?')
    // added in v1.26.8; insertText returns the keyboard object
    // this will trigger the change event on the original input
    .$el.trigger('change');
  });

});
```

**Comment by willrbaar** [comment]
Rob:  Is there an easy way to clear the contents of the Preview area after hitting the accept button, or cancel button?  I would have thought there would be.  I tried using the jquery .empty() function, but that didn’t work.  I tried a lot of things and looked over the documentation, but didn’t find anything.  Also, if I wanted to keep track of the cursor, how would I go about doing that.  Thanks

By the way, the below code works well and I have been expanding on it.

**Comment by Mottie** [comment]
>  jquery .empty() function

This jQuery function empties a DOM element... e.g. `$('div').empty()` results in empty div(s) (`<div></div>`).

To clear an input, use `$('input').val("");` which sets a the input's value to an empty string.

> Is there an easy way to clear the contents of the Preview area after hitting the accept button, or cancel button

There is an [`accepted` callback](https://github.com/Mottie/Keyboard/wiki/Methods#accepted) function which is called when the contents are accepted and a [`canceled` callback](https://github.com/Mottie/Keyboard/wiki/Methods#canceled) function called when the changes are canceled.

I'm not quite sure why you would clear the preview with these content changes as the keyboard should close immediately after the above callback is executed. That is unless you have the [`alwaysOpen` option](https://github.com/Mottie/Keyboard/wiki/Usability#alwaysopen) set as `true`.

If you mean you want to empty the original input (not the preview), then you can use the [`hidden` callback](https://github.com/Mottie/Keyboard/wiki/Methods#hidden) function to clear the input

```js
$('#keyboard').keyboard({
  hidden : function(event, keyboard, el) {
    // same as $(el).val("")
    // and $("#keyboard").val("");
    el.value = "";
  }
});
```

> I wanted to keep track of the cursor

If you use the [`change` callback](https://github.com/Mottie/Keyboard/wiki/Methods#change) function, you can access the [`last` variable](https://github.com/Mottie/Keyboard/wiki/Methods#values) to get the `start` and `end` caret position:

```js
$('#keyboard').keyboard({
  change: function(event, keyboard, el) {
    console.log('cursor start: ' + keyboard.last.start);
    console.log('cursor end: ' + keyboard.last.end);
  }
});
```

You can access the [caret](https://github.com/Mottie/Keyboard/wiki/Methods#caret) position at any time by using this code:

```js
var keyboard = $("#keyboard").data("keyboard");
var caret = $.keyboard.caret( keyboard.$preview );
/*
/* returned object = {
  // caret starting position
  start: 0,
  // caret ending position
  end:   0,
  // the selected text; is an empty string if start & end are the same
  text:  "",
  // replace string function. The selected text is replaced by the
  // value in the "str" parameter
  replaceStr: function(str) {}
} */
*/
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
