### ISSUE TITLE
autocomplete jquery

### ISSUE THREAD

**Issue by 0kkult0** [Mottie/Keyboard#512]
jquery autocomplete in text input not work?

**Comment by Mottie** [comment]
Hi @0kkult0!

It works for me - [demo](https://jsfiddle.net/Mottie/n6xeoLyp/).

**Comment by 0kkult0** [comment]
Hi, thi is my code

`$('#txinput').keyboard({
        language: ['it'],
        keyBinding: 'mousedown touchstart',
        layout: 'qwerty',
        caretToEnd: true,
        autoAccept: true,
        usePreview: false,
        appendLocally: true,
        autoAcceptOnValid: true,
        container: { theme: 'b', cssClass: 'ui-body' },
        change: function (event, keyboard, el)
            {
                AttachAutocomplete();
            }`

`function AttachAutocomplete()
{
    $.ajax({
        type: "POST",
        url: "insauto.aspx/GetMarche",
        cache: false,
        contentType: "application/json;charset=UTF-8",
        data: "{'marca':'" + document.getElementById('txinput').value + "'}",
        dataType: "json",
        crossDomain: true,
        async: true,
        success: readstate,
        error: errorstate,
    });
}

function readstate(data, status) {
    if (data.d === "") { return; }

    var listall = data.d;

    $("#txinput").autocomplete({
        source: listall
    });
function errorstate(xmlRequest) { }
`
if I write from the physical keyboard works, but if I write on the virtual keyboard does not work

**Comment by Mottie** [comment]
Oh, you're not using the [autocomplete extension](https://github.com/Mottie/Keyboard/blob/master/js/jquery.keyboard.extension-autocomplete.js)?

[Here is the documentation](https://github.com/Mottie/Keyboard/wiki/Setup#autocomplete) on how to set it up

I think I'll add a section on what scripts need to be loaded in the page header.

**Comment by Mottie** [comment]
Actually, the [page head section](https://github.com/Mottie/Keyboard/wiki/Setup#pagehead) is at the top of that setup page.

**Comment by Mottie** [comment]
I've moved the details for each extension into separate wiki pages. Here is the new [autocomplete extension documentation](https://github.com/Mottie/Keyboard/wiki/Extension-Autocomplete).

Other than that, I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
