### ISSUE TITLE
Problem with mouse enter and click firing at the same time

### ISSUE THREAD

**Issue by Suka1215** [Mottie/Keyboard#514]
When mouse enter is triggered it fires and click fires resulting in the keyboard not entering the correct values. Help?

**Comment by Mottie** [comment]
Hi @Suka1215!

Please provide a bit more information:

* What OS & browser?
* Is there an existing demo where this issue occurs, or would you be able to provide a demo of this problem?
* What settings are being used?
* Did you try modifying the [`keyBinding` option](https://github.com/Mottie/Keyboard/wiki/Usability#keybinding)?

**Comment by Suka1215** [comment]
Thank Mottie

It is chromium 52
I don't have a demo 
The only thing I removed was mouseenter and it worked the problem is if I did that I would have to include your code in certification. 
Is there a reason for watching for mouseenter as apposed to click as default?

I will say that your 1.12 build did work but the autoTextEnter did not. For instance if I type something it shows up in the input but the accept button does not becaome clickable because it's not registering that there was anything entered.   

Thanks Again

**Comment by Suka1215** [comment]
So on touchstart I am getting cannot read property key of undefined when I hit a key.

**Comment by Mottie** [comment]
> I would have to include your code in certification.

I have no idea what you mean... it's an option that can be set upon initialization of the keyboard

> Is there a reason for watching for mouseenter

Mouseenter is bound to give focus to the keyboard. This is needed for when keyboards are set as always open. Giving the keyboard focus also sets the input caret position so typing would continue from where it was left off.

> I will say that your 1.12 build did work but the autoTextEnter did not

Are we still discussing this library? Version 1.12 was released on July 24, 2012. And there is no `autoTextEnter` option.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
