### ISSUE TITLE
Autocomplete not work with usePreview: true

### ISSUE THREAD

**Issue by bigfox** [Mottie/Keyboard#517]
Hi @Mottie,

on my project, i previously use **Keyboard v1.26.6** and **Autocomplete extension v1.11.0** and all works fine. After update to **v1.26.15** with **v1.11.2**, autocomplete extension do nothing, even no error.

I tried to play with the options and i found that Autocomplete extension v1.11.2 does not work when Keyboard option `usePreview` is set to `true`.

See this demo https://jsfiddle.net/bigfox/o1ft1tmk/ .

**Comment by Mottie** [comment]
Hi @bigfox!

Thanks for reporting this problem! I will investigate and get this fixed ASAP!

**Comment by Mottie** [comment]
All fixed! Sorry about that.
