### ISSUE TITLE
Problem when clicking on Select fields

### ISSUE THREAD

**Issue by kor86** [Mottie/Keyboard#518]
Hello,
when i click on a select field and choosing an option the mouseclick is issued somewhere else on the screen with an offset and another link is pressed. This only happens when the keyboard js files are included in the website. Im using the newest version v1.26.16.
If I comment out the JS files of the keyboard the problem does not appear.

The problem only appears on Windows with touchscreen. It seems like the mouse click has an offset.

Has someone else ran into this issue?

**Comment by Mottie** [comment]
Hi @kor86!

Would you please modify [this demo](http://jsfiddle.net/Mottie/egb3a1sk/) to duplicate the problems you're reporting. Also which browser are you using, and does it only happen in that one browser or all the ones you tested?

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
