### ISSUE TITLE
Keyboard is opening automatically even if i set openOn=""

### ISSUE THREAD

**Issue by kubili** [Mottie/Keyboard#519]
I set openOn to "" and when I click input filed the keyboard opens. I use latest version of keyboard and chrome (and edge). This does not happen in IE.

I have traced the problem to this block of code:

```
if (kb === base && !kb.$el.hasClass(kbcss.isCurrent)) {
	kb.focusOn();
}
```

**Comment by Mottie** [comment]
Hi @kubili!

The latest version (v1.26.16) does not include that exact code... See [line 1653](https://github.com/Mottie/Keyboard/blob/master/js/jquery.keyboard.js#L1653):

```js
if (kb !== base && !kb.$el.hasClass(kbcss.isCurrent)) {
  kb.focusOn();
}
```

And [this demo](http://jsfiddle.net/Mottie/egb3a1sk/2334/) is also working as expected.

Please make sure the latest version is being used. If the problem persists, please modify the demo to duplicate the problem. Thanks!

**Comment by kubili** [comment]
Sorry for my mistake (I have copied wrong code, but I use the latest). Please try [this fiddle ](http://jsfiddle.net/4bw344ne/). I have the same problem as it appears here.

**Comment by Mottie** [comment]
Ahh, ok... I just pushed a fix to the master branch - [demo](http://jsfiddle.net/Mottie/4bw344ne/1/) - it should fix the problem. I just want to make sure no other issues arise from this change before releasing it. Thanks for reporting the problem!
