### ISSUE TITLE
Question: Open keyboard in a new page

### ISSUE THREAD

**Issue by exyoris** [Mottie/Keyboard#525]
Hello! I know it's a bit strange request and it might not look like it'll actually be of any help implementing that, but the thing is, that I'm trying to build a calculator for a small, custom touchscreen PC, it's not for regular browsing. 

So, I would like to have the feature of opening the keyboard (numeric) in a new page after clicking on the input, and the OK button to act as a some kind of "submit" button, which returns to the previous page with new input value. 

![image](https://cloud.githubusercontent.com/assets/25562151/23065846/ed06c736-f517-11e6-87e4-f083fbc9d38d.png)

The layout will be better, but that's the general idea. 
Another thing, can I replace the input type with button? Because having text type is a bit pointless in this case, since the value will come from another page. 

Thank you very much in advance, I hope you can help or point me to some solutions.

**Comment by exyoris** [comment]
![image](https://cloud.githubusercontent.com/assets/25562151/23066098/2511c29c-f519-11e6-8880-7ee14ea3d9b7.png)

For now, the values are empty and my idea is to open the numpad in a new page and return with new button value. :)

**Comment by Mottie** [comment]
Hi @exyoris!

Sorry for the long delay in responding... I've been on vacation for the past 3 weeks and I am just not trying to catch up.

I'm not exactly sure what you're trying to accomplish, but in this case it sounds like you might want to use `window.open` and `document.write` to add HTML to a child window - [here is a basic demo](https://jsfiddle.net/Mottie/ct2qkzj0/):

HTML

```html
<button type="button">Open Calculator</button>
```

Script

```js
$(function() {
  $('button').click(function() {
    openPopup();
  });

  function openPopup() {
    var popup = window.open('', 'calculator', 'width=200,height=275');
    popup.document.write(
      '<html><head><title>Calculator</title>' +
      '<link rel="stylesheet" href="https://mottie.github.io/Keyboard/css/keyboard.css">' +
      '<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/ui-lightness/jquery-ui.css">' +
      '<style>#keyboard { width: 20px; } .ui-keyboard div { font-size: 1em; }</style>' +
      '<scr' + 'ipt src="https://code.jquery.com/jquery-1.9.1.js"></scr' + 'ipt>' +
      '<scr' + 'ipt src="https://mottie.github.io/Keyboard/js/jquery.keyboard.js"></scr' + 'ipt>' +
      '<scr' + 'ipt>$(function(){ var kb = $("#keyboard").keyboard({' +
      'layout: "num", hidden: function(){ window.opener.returnValue(kb.val()); window.close(); }' +
      '}); kb.getkeyboard().reveal(); });</scr' + 'ipt>' +
      '</head><body><input id="keyboard" type="text" />' +
      '</body></html>'
    );
    popup.document.close();
  }
});

window.returnValue = function(value) {
  console.log(value);
}
```

It is a basic demo because I'm not sure what you mean by replacing the input type with a button.

**Comment by exyoris** [comment]
Hey, thank you very much, this was a really out-of-logic request and I'm sorry that I made you even think about a solution, lol. It's just that I'm building a calculator for a touchscreen custom PC, which is about 7'' big and I wanted to really separate the keyboard from the inputs. So I thought I'd ask you for this.

Also, I wanted the 'input' fields to actually look like buttons, so it'd be more convenient for the user - you press it, go to another page with the keyboard alone, enter there some values and return to the main page with these values as the button's initial value. 

I think I'll go off with just darkening the background and isolate the keyboard with CSS, which I asked about in here: #534 :)

**Comment by Mottie** [comment]
Is there anything else you need related to this issue?

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
