### ISSUE TITLE
`openOn` does not work as expected if initializing multiple inputs

### ISSUE THREAD

**Issue by claudix** [Mottie/Keyboard#527]
The `openOn` feature works fine as long as **only one input** is initialized with the keyboard. However it stops working if multiple inputs are initialized. I'm using v1.26.17 and here is a demo in which I setup the keyboard with `openOn: 'mouseup'` (see the comment in the Javascript section):

http://jsfiddle.net/c82ae3yz/

**Comment by Mottie** [comment]
Hi @claudix!

Sorry for the delay. This does appear to be a problem, I will look into this issue in more depth soon.
