### ISSUE TITLE
Click on Accept button and going to next input

### ISSUE THREAD

**Issue by grouser** [Mottie/Keyboard#528]
Hello,

I am using the keyboard in a touch screen. I would like to click on the "Accept" button and move the focus to the next field. Would that be possible? I only see the setting when pressing the "Enter" key.

Thanks.

**Comment by exyoris** [comment]
Hi, check out this: https://jsfiddle.net/Mottie/k22Lybw3/

By pressing on prev and next you move the focus to the previous and next input field. With some modifying, you can add the 'next' function to 'accept'.

**Comment by Mottie** [comment]
Thanks @exyoris! I'm on vacation with only my phone, so it is difficult for
me to answer appropriately with code.

**Comment by afattahi54** [comment]
Of Topic :)

I have used lots of projects in github, but rarely found the support which Mottie gives to us compare to other projects.
Thanks dear @Mottie and I wish you the best !

**Comment by grouser** [comment]
Thank you very much @exyoris

**Comment by grouser** [comment]
I have changed $("input") to $(":input:not([type=hidden])") so that it doesn't get the hidden fields if you are using the auto-complete plugin.

**Comment by Mottie** [comment]
I'll take a closer look at this when I get back next week

**Comment by Mottie** [comment]
Issue #524 has [an example](http://jsfiddle.net/Mottie/egb3a1sk/2371/) of multiple inputs allowing you to switch to the previous and next inputs using internal keys. The last input changes the "next" button to "submit".

In [this demo](http://jsfiddle.net/Mottie/egb3a1sk/2505/), the "accept" key action is modified to automatically switch to the next input

```js
$(function() {
	$.keyboard.keyaction.accept = function(kb) {
  	kb.switchInput(true, kb.options.autoAccept);
    return false; // prevents further processing
  };
  $('#wrap input').keyboard({
    usePreview: false,
    autoAccept: true
  });
});
```

**Comment by Mottie** [comment]
In the latest release, you no longer required to include `return false` inside the keyaction to stop further processing & prevent js errors.

**Comment by grouser** [comment]
Wow. It works like a charm. Thanks Mottie!

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
