### ISSUE TITLE
Change keyboard defaults

### ISSUE THREAD

**Issue by afattahi54** [Mottie/Keyboard#530]
I want to change some keyboard defaults css and position.

I test below but didn't work

``````javascript
$.extend($.keyboard.css,{
	input : ''
})
```````

**Comment by Mottie** [comment]
Hi @afattahi54!

You should be modifying the `defaultOptions`:

```js
$.extend($.keyboard.defaultOptions.css, {
  input: ''
});
```

**Comment by afattahi54** [comment]
Thanks! 
I want to change the `position` and `css` so I used:

`````javascript
$.extend($.keyboard.defaultOptions.css, {
		  input: ''
});

$.extend($.keyboard.defaultOptions.position, {
    of: null ,
    my: 'right center',
    at: 'left center',
    at2: 'left center',
    collision:'flipfit'

});
```````

The above works

To reduce some line of codes, I try to merge two extend commands:

`````javascript
$.extend($.keyboard.defaultOptions, {
	css : {
		input: ''
	},
	position:{
		of: null ,
		my: 'right center',
		at: 'left center',
		at2: 'left center',
		collision:'flipfit'
	}
});
```````

Which does not work ! It seems that the `css` property could not be set with this way. 

Is it any way I can set defaults by using one `$.extend`

**Comment by Mottie** [comment]
With jQuery, you'll need to do add a `true` flag to perform a [deep extend](http://api.jquery.com/jQuery.extend/#jQuery-extend-deep-target-object1-objectN) of the position object:

```js
$.extend(true, $.keyboard.defaultOptions, {
	css : {
		input: ''
	},
	position:{
		of: null ,
		my: 'right center',
		at: 'left center',
		at2: 'left center',
		collision:'flipfit'
	}
});
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
