### ISSUE TITLE
Redraw method is reposition the keyboard for custom layout

### ISSUE THREAD

**Issue by Sritharan-racap** [Mottie/Keyboard#531]
Hi Mottie,
Firstly I would like to say this is an awesome library. I have small problem with keyboard design.

I am using multiple custom layout like Greek, Special characters etc. so i have to switch the layout on a constant basis, i am doing the switching using redraw event, but the new layout is repositioning itself below the input box which is annoying. 

I know u have already exposing the position callback for reposition keyboard where I can do the keyboard repositioning beforeVisible.

Is there is shortcut boolean feature to stop the reposition of the keyboard on redraw ???

**Comment by Mottie** [comment]
Hi @Sritharan-racap!

I'm out of the country right now with only my cell... I'm sorry you're having this issue. Sadly I won't be able to test or resolve this issue until I return next week. Thank you for your patience.

**Comment by Mottie** [comment]
The redraw method still uses the reveal function which removes the current keyboard and creates a new keyboard with the new layout, so the keyboard would still need to be repositioned when it is made visible. 

I just created [this demo](http://jsfiddle.net/Mottie/egb3a1sk/2504/) for issue #532 allowing you to switch layouts & language using an action key and the keyboard does not shift. So, it sounds like there might be another cause making the keyboard shift below the input.

**Comment by Sritharan-racap** [comment]
Really, this is not the same behavior in my machine. Probably I am using an older version of the keyboard source code. But this was not a terrible issue. I just called the jquery position function before visible which u are already exposing and the function works like a charm.

Hey Mottie, this is an awesome library u have contributed to the community man. the keyboard looks really beautiful in super big screens in our office.

Kudos have a great day. I am closing this issue.
