### ISSUE TITLE
Always trigger altkeypopup

### ISSUE THREAD

**Issue by tobiasvandriessel** [Mottie/Keyboard#533]
Hi Mottie,

Is it possible to always let the altkeypopup trigger, when it is enabled? I tried setting the holdTime to 0, but there are still times it isn't activated. With my notebook's touchpad it does work, but the left mouse button under it does not always activate it.

I'd like to hear your thoughts when you have the time.

**Comment by Mottie** [comment]
Hi @tobiasvandriessel!

The altkeypopup is set to open on mousedown and touchstart. I could add an option to allow you to modify those settings. In the mean time, you could manually open the popup using this code ([demo](https://jsfiddle.net/Mottie/k7741r7n/13/)):

```js
visible: function(event, kb) {
  kb.$allKeys
    .unbind(kb.altkeypopup_namespace)
    .bind('touchstart mousedown', function() {
      var $key = $(this),
        key = $key.attr('data-value') || '';
      if (key in $.keyboard.altKeys) {
        kb.altKeyPopup_popup(key, $key);
      }
    });
}
```

**Comment by tobiasvandriessel** [comment]
Sorry for the late reply, but this works like a charm! I first tested it and somehow it didn't work back then, but now it does, so thanks a lot!
