### ISSUE TITLE
Autocomplete is not working in jQuery UI version 1.11.4

### ISSUE THREAD

**Issue by bhumiradixweb** [Mottie/Keyboard#535]
Autocomplete is not working in jQuery UI version 1.11.4

**Comment by Mottie** [comment]
Hi @bhumiradixweb!

I modified [this demo](https://jsfiddle.net/Mottie/n6xeoLyp/19/) to use jQuery UI v1.11.4 with jQuery 1.9.1. Please note that "legacy" versions of jQuery UI do not work with jQuery v3.0.0+ - you can change the version of jQuery and see it break in that demo. Check out the console too.

**Comment by bhumiradixweb** [comment]
Hello Mottie,

Thanks for updating demo. It is working.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
