### ISSUE TITLE
JS error when call keyboard.accept() inside any action

### ISSUE THREAD

**Issue by Vick-edit** [Mottie/Keyboard#536]
Linked issue - #168

**_Сonfiguration_**: 
1. Jquery - 1.12.4
2. jquery.keyboard - 1.26.17

**_Action_**:
1. Replace standart "Enter" Action with custom function, that will call keyboard.accept();
2. Click on input to open keyboard
3. Enter data(or not)
4. Press enter key on JS keyboard

**_Alt action_**:
1. Setup default layout
2. Click on input to open keyboard
3. Enter data(or not)
4. Press shift+enter keys

**_Result_**:
Data from keyboard was stored in input and keyboard is closed and there is **error in JS console**: "`base.$keyboard.hasClass is not a function`", source of error- `jquery.keyboard.js:1360:29`:
```
1357	// check for key combos (dead keys)
1358	base.checkCombos = function () {
1359		// return val for close function
1360		if (!(base.isVisible() || base.$keyboard.hasClass($keyboard.css.hasFocus))) {
1361			return base.$preview.val();
1362		}
1363		var r, t, t2,
```

But, like in #168, if I replace:
```
$.keyboard.keyaction.enter = function (base) {
    base.accept();
};
```

with following, will no error:
```
$.keyboard.keyaction.enter = function (base) {
    base.accept();
    return false;
};
```

**_Example_**:
http://jsfiddle.net/VickEdit/2gb4sv8k/

P.S. Thx for really great project! 👍

**Comment by Mottie** [comment]
Hi @Vick-edit!

Yes, you're right, you'll need to `return false` inside the keyaction if you close the keyboard.

I'll add an additional check after the keyaction function to prevent any javascript errors.
