### ISSUE TITLE
Remove overtop keyboard and autocomplete issue

### ISSUE THREAD

**Issue by bhumiradixweb** [Mottie/Keyboard#537]
Hello,

```
$('#keyboardset').keyboard({
		usePreview: false,
		autoAccept:true,
		position: {
			my: 'left bottom',
			at: 'left bottom',
			at2: 'left top' // used when "usePreview" is false
		},
	}).autocomplete({
			//autocomplete code
	}).addAutocomplete({
		position: {
			of: null,
			my: 'left+0 top+100',
			at: 'left bottom',
		}
	});
```

This is my code and I wants to display a keyboard on top and autocomplete on the bottom of the input field. But **my: 'left top'** code overtop the predictive text to the input field. 

so changed **my: 'left+0 top+100'** to add the gap between the keyboard and predictive text and show input field but then it is creating an issue while the keyboard is coming in the bottom. so can fix keyboard or something?

**Comment by Mottie** [comment]
Hi @bhumiradixweb!

I think you might need to set jQuery UI [position utility](http://api.jqueryui.com/position/#position1) `collision` option to `"none none"` ([demo](https://jsfiddle.net/Mottie/n6xeoLyp/21/)), but then you need to make sure you always have enough space above the input:

```js
$('#keyboard')
  .keyboard({
    usePreview: false,
    autoAccept: true,
    position: {
      my: 'center bottom',
      at: 'center top',
      at2: 'center top', // used when "usePreview" is false
      collision: 'none none'
    }
  })
  .autocomplete({
    source: availableTags
  })
  .addAutocomplete({
    // add autocomplete window positioning
    // options here (using position utility)
    position: {
      of: null,
      my: 'center top+20',
      at: 'center bottom'
    }
  });
```

**Comment by bhumiradixweb** [comment]
Thanks @Mottie , it is working.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
