### ISSUE TITLE
Keyboard not working with editable tables (contenteditable="true")

### ISSUE THREAD

**Issue by m-art-in** [Mottie/Keyboard#540]
I tried to use the virtual keyboard in combination with editable tables
`<td contenteditable="true">`
but unfortunaltly in file jquery.keyboard.js line 3001 function createTextRange() is called which is not allowed for `<td>`-elements. 
Is there a work around of fix for this issue?

**Comment by Mottie** [comment]
Hi @m-art-in!

Sorry, the keyboard does not currently work with content editable elements. The problem is integration of the keyboard with caret positioning functions.

Duplicate of #208.

**Comment by m-art-in** [comment]
Thanks for the fast reply! So this could be a feature request ;-)
I'll try to find an other solution

**Comment by Mottie** [comment]
Contenteditable support added in v1.27.0-beta.
