### ISSUE TITLE
Pressing enter doesn't call beforeInsert callback nor accepted callback.

### ISSUE THREAD

**Issue by darkgnostic** [Mottie/Keyboard#543]
I wanted to add simple keyboard with enter, and by pressing the enter button I thought that accepted callback will be called. That wasn't the case, so I tried to catch enter press inside beforeInsert callback, but nothing happens.

Here is the fiddle: https://jsfiddle.net/fnadshqd/1/

Am I missing something? How can I accept entered value by pressing enter?

**Comment by Mottie** [comment]
Hi @darkgnostic!

The enter key as a defined [keyaction](https://github.com/Mottie/Keyboard/wiki/Actions#modifyaction) which can be modified as you desire.

By default, if `enterNavigation` option is `true`, the following occurs:
* On an input, jump to the next form element. If the `enterMod` key is pressed (alt key by default), it jumps to the previous form element.
* On a textarea, the same behavior is preformed, but only if the shift key is active.
* By default, if the last form element on the page has focus, then nothing will happen. When the `stopAtEnd` option is `false`, then focus is given to the first form element on enter navigation.

In either case, make sure to set the `autoAccept` option to `true`, or any input would be lost.

So, it may look like nothing happens in [this demo](https://jsfiddle.net/Mottie/fnadshqd/2/) when pressing enter in the second input, but there is a lot going on.

On the wiki page I linked above, there is code showing how to modify the enter key's action to submit the form... [here is a demo](https://jsfiddle.net/Mottie/fnadshqd/3/) using the same code without including the form submit.

```js
$.keyboard.keyaction.enter = function(base){
  if (base.el.nodeName === "INPUT") {
    base.accept(); // accept the content
  } else {
    base.insertText('\r\n'); // textarea
  }
};
```

**Comment by darkgnostic** [comment]
Thank you for clarification.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
