### ISSUE TITLE
Input inside Keyboard: On keyup event update a texbox

### ISSUE THREAD

**Issue by cristo1985** [Mottie/Keyboard#544]
How can i create keyup event for keyboard and updating an other text with input keyboard value?

**Comment by cristo1985** [comment]
Where is the function when i press any button for updating both display inside keyboard and textbox who keyboarded by $("#idinput").keyboard(). Thanks

**Comment by Mottie** [comment]
Hi @cristo1985!

You can use the [`change` callback](https://github.com/Mottie/Keyboard/wiki/Methods#change) function to update the external element ([demo](http://jsfiddle.net/Mottie/egb3a1sk/2574/)):

```js
$(function() {
	var $result = $('#result');
  $('#keyboard').keyboard({
      change: function(e, keyboard, el) {
      	$result.html(keyboard.$preview.val());
      }
    });
});
```

**Comment by cristo1985** [comment]
Oh thanks very much bro! It's a good plugin!!
