### ISSUE TITLE
Position of autocomplete

### ISSUE THREAD

**Issue by cristo1985** [Mottie/Keyboard#545]
Hi Mottie, 
i've a new question about autocomplete position. How can i made the autocomplete work as normal autocomplete jquery (under textbox that activate the keyboard) instead putting on right of keyboard. Sorry bro for my bad english!
Thanks

**Comment by Mottie** [comment]
Hi @cristo1985!

You can use the autocomplete extension's [`position` option](https://github.com/Mottie/Keyboard/wiki/Extension-Autocomplete#position). You can see a demo of it being used in issue #537.

**Comment by cristo1985** [comment]
Ok. Mottie you are the best!! Thanks!

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
