### ISSUE TITLE
Keyboard doesn't place well when it doesn't fit below a input

### ISSUE THREAD

**Issue by grouser** [Mottie/Keyboard#548]
Hello,

I have an input text almost at the bottom of the page. When you click on the input, the keyboard appears into the top of the page and the input is hidden by the keyboard, so you don't know which information your are typing.

I think it should be placed above the field.

Kind Regards

**Comment by Mottie** [comment]
Hi @grouser!

The keyboard is (usually) positioned by jQuery UI's position utility; this is an optional requirement as the keyboard may be positioned using CSS or other means, e.g. using custom script to position it from within the [`beforeVisible`](https://github.com/Mottie/Keyboard/wiki/Methods#beforevisible) or [`visible`](https://github.com/Mottie/Keyboard/wiki/Methods#visible) callback. Note, the position utility requires that the element be visible before it can be positioned.

Please note that the setting of the [`usePreview` option](https://github.com/Mottie/Keyboard/wiki/Usability#usepreview), will determine if the [`position` option](https://github.com/Mottie/Keyboard/wiki/Layout#position) `at` or `at2` setting is used to position the keyboard.

I set up [this demo](http://jsfiddle.net/Mottie/egb3a1sk/2596/) showing the default [`collision`](http://api.jqueryui.com/position/) option setting which you can change to whatever setting you desire.

**Comment by grouser** [comment]
I have tried with those options but get the same result.
This what I mean. Below you see all the fields.
![image](https://cloud.githubusercontent.com/assets/2338773/25842172/ff85e8e8-349a-11e7-9549-bb483888c383.png)

Now you can think that you are editing the Who are you visiting field, but in fact, you are writing in the vehicle_reg field.

![image](https://cloud.githubusercontent.com/assets/2338773/25842192/174098b6-349b-11e7-98a1-37a42e326d6d.png)

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
