### ISSUE TITLE
beforeInsert insert functional keys as text on firefox

### ISSUE THREAD

**Issue by Vick-edit** [Mottie/Keyboard#549]
**_Сonfiguration_**: 
1. Jquery - 1.12.4
2. jquery.keyboard - 1.26.19
3. browser - firefox 52.0.2 (x86)

**_Action_**:
1. Add handling for `beforeInsert `event, that just return `textToAdd `
2. Start typing from physical keyboard then use arrow keys or _F1_ and etc.

**_Result_**:
Instead navigation by text we get symbols inserted in text.

**_Example_**:
http://jsfiddle.net/VikEdit/z3jtn6wy/

**_Cause_**
Before calling 
[jquery.keyboard.js#L806](https://github.com/Mottie/Keyboard/blob/master/js/jquery.keyboard.js#L806)
```
base.insertText(base.last.key);
e.preventDefault();
```
We need analyze is it text, number key or functional key by `e.keyCode` or `e.key.length`, cause firefox raise keypress event for functional keys too.

I figured out, that when firefox raise `keypress` event for functional keys it put incorrect data in `which` and `charCode` (`charCode` alwayse is zero and `which` zero or keyCode from [table](https://www.cambiaresearch.com/articles/15/javascript-char-codes-key-codes) more often zero)

**Comment by Mottie** [comment]
Hi @Vick-edit!

Sorry for not responding earlier... I had lots of distractions over this weekend.

I'll take a look at this and the PR in more depth later today.

**Comment by Mottie** [comment]
Thanks again, version 1.26.23 is now available.
