### ISSUE TITLE
Not using a visible popup disables physical keyboard

### ISSUE THREAD

**Issue by oz1cz** [Mottie/Keyboard#553]
A problem with Altkeys popups if you open a popup but don't use it:

1. Go to the demonstration page, docs/altkeys-popup.html.
2. Click with your mouse in the text input field. The virtual keyboard appears.
3. Press a key long enough to bring up a popup. (It doesn't matter if you press the physical key or use your mouse to press a virtual key.)
4. DO NOT press any keys in the popup; instead, click with your mouse somewhere outside the virtual keyboard. The virtual keyboard disappears.
5. Click with your mouse in the text input field. The virtual keyboard appears.
6. Now the physical keyboard no longer works.

(Seen in Chrome and Firefox under Linux.)

**Comment by Mottie** [comment]
Hi @oz1cz!

Thanks again for reporting a problem with the Altkeys extension! I'll have it fixed here shortly.

**Comment by Mottie** [comment]
v1.26.21 is now available.

**Comment by oz1cz** [comment]
Both this and the previous problem now works nicely! Thank you.
