### ISSUE TITLE
Keboard Master Not Accept

### ISSUE THREAD

**Issue by muradsofiyev** [Mottie/Keyboard#560]
Typing work but when i click accept destroyed. I use this keyboard in modal

**Comment by Mottie** [comment]
Hi @muradsofiyev!

When the user clicks on accept, they should have completed entering the desired information. Currently, there is no way around not closing the keyboard when a user accepts unless you set the `alwaysOpen` option, which wouldn't be ideal if there are multiple inputs - [demo](https://jsfiddle.net/jLu8ysh0/3/) - and there appears to still be issues with initial focus. Start typing and the last input will get the input.

Alternatively, you could:

* Change the layout to remove the accept key.
* Change the accept key action to save, but not close the keyboard - [here is the documentation on how to change a keyaction](https://github.com/Mottie/Keyboard/wiki/Actions). I'm not exactly sure what you want to happen when a user accepts the content, so if the documentation is confusing, please give me some more details and I will try to help however I can.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
