### ISSUE TITLE
noPreview doesn't trigger keyUp event

### ISSUE THREAD

**Issue by ZeeCoder** [Mottie/Keyboard#561]
While typing with the keyboard in noPreview mode, the input / textarea elements are not triggering keyup events.

I'm using so-called "controlled" inputs in React, which means that on each keyup, I feed the input value back to the state, which then re-renders the new input with the state.

The point is to have the input value incorporated in the state: https://facebook.github.io/react/docs/forms.html#controlled-components

Now, when keyup is not triggered with the right value, then it's not getting fed back to the state.
This means that if anything triggers re-rendering, the whole input gets rerendered empty.

Also: even if I'm done and I click send on the form it will be invalid, since validation is based on the state. (which is supposed to be up to date with the input values)

**Comment by Mottie** [comment]
Hi @ZeeCoder!

I'm still in the process of learning React. I haven't gotten to the part to get it to integrate nicely with third party plugins.... so I'm not sure what the best solution would be here.

Instead of binding to "keyup", bind to the "keyboardChange" event or use the `change` callback ([demo](http://jsfiddle.net/Mottie/egb3a1sk/2646/)):

```js
$('#keyboard')
  .on('keyboardChange', function(e) {
    // do something
  })
  .keyboard({
  	usePreview: false,
    change: function(e, keyboard, el) {
      // do something
    }
  });
```

You don't need to use both.

**Comment by ZeeCoder** [comment]
Is there a particular reason why keyup events are not fired by default?

For the time being I could trigger the event myself on keyboardChange or change I guess.

**Comment by Mottie** [comment]
> Is there a particular reason why keyup events are not fired by default?

Honestly, it didn't even occur to me that it would be needed for interaction with a virtual keyboard.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Comment by ZeeCoder** [comment]
Ah sorry, forgot to report back.
We basically implemented a script which reinitialises the keyboard for all new input that might appear during React mounting.
There were other things to work around, but it's ok for the time being. 👍
