### ISSUE TITLE
issue:: getting copy of first textbox into another in a same div but different ids through keypad  input ??

### ISSUE THREAD

**Issue by naeemh93** [Mottie/Keyboard#563]

**Comment by Mottie** [comment]
Hi @naeemh93!

An additional input/textarea is added when `usePreview` is `true`. This element will not include any ID. If using the caret extension, another element is added to help in calculating an accurate caret position. Both of these additional elements will have a class name of `ui-keyboard-preview` added.

To make sure you're only targeting your original input, use the ID or use

```js
$('input, textarea').filter(':not(.ui-keyboard-preview)');
```

to get the correct elements.

If that doesn't resolve the issue, please modify [this demo](http://jsfiddle.net/Mottie/egb3a1sk/) to show the HTML structure and initialization code being used.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
