### ISSUE TITLE
Backspace does not work in preview element after calling .close() or .accept()

### ISSUE THREAD

**Issue by KCMertens** [Mottie/Keyboard#565]
When calling accept() or close() to hide the keyboard, base.$preview is cleared [here](https://github.com/Mottie/Keyboard/blob/de68263a16b97fc314850a1ca2c144ae4bb4e66c/js/jquery.keyboard.js#L1641).
However, the [keydown event](https://github.com/Mottie/Keyboard/blob/de68263a16b97fc314850a1ca2c144ae4bb4e66c/js/jquery.keyboard.js#L877) on $preview remains bound, and escape appears to be manually handled, eventually the modified text in the internal buffer is copied out to $preview. However since preview has been cleared, the backspace key is swallowed.

**Comment by Mottie** [comment]
Hi @KCMertens!

Would you please [modify this demo](http://jsfiddle.net/egb3a1sk/2721/) to show this issue. I was not able to duplicate the issue with some basic settings (including setting `alwaysOpen` to `true`), so it might be related to your specific settings. Thanks!

**Comment by KCMertens** [comment]
Hey Mottie!

Sorry for not getting back to you quicker, I didn't have access to the code in question at home yesterday.

We're using the keyboard to support simple input of special characters from other languages, so display of the keyboard is explicitly toggled through a button. We're using the reveal() and accept() fuctions to do this. After opening and closing once, the issue occurs while the keyboard is closed. 

I've modified [the fiddle](http://jsfiddle.net/yv13akr5/) to show a minimal repro case by emulating an open and closing of the keyboard.
Type something in the field, then press backspace and observe it being swallowed.

**Comment by Mottie** [comment]
Thanks for the demo, that really helps!

I'll take a look at it later today.
