### ISSUE TITLE
is it possible to replace the top input with a label instead? 

### ISSUE THREAD

**Issue by bboydflo** [Mottie/Keyboard#567]
Hi, and thanks for the plugin!

I would like to trigger a custom keyboard on mobile. I am not sure if it's possible to replace the top keyboard input with a label instead, so that on mobile, the native keyboard won't get triggered because this top input is focused. It would be a nice feature.

So the question is: is it possible to replace the top input with a span element or something else?

**Comment by Mottie** [comment]
Hi @bboydflo!

Currently, this plugin isn't set up to work with contenteditable elements (non-input/textarea elements) (see #208).

The only method I have found so far to prevent the native keyboard popup is to set the [`lockInput` option](https://github.com/Mottie/Keyboard/wiki/Usability#lockinput) to `true`. This sets the `readonly` attribute on the input & preview, so you may need to include the [caret extension](https://github.com/Mottie/Keyboard/wiki/Extension-Caret) with left/right arrows to allow moving the caret - [demo](https://jsfiddle.net/Mottie/24n8wsak/134/). You might want to also try the other suggestions from issue #334.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
