### ISSUE TITLE
Big symbols with Extension Navigation

### ISSUE THREAD

**Issue by bsurai** [Mottie/Keyboard#572]
My actions on this page https://mottie.github.io/Keyboard/docs/navigate.html
1) `shift+F1` Toggle navigation 
2) selected and pressed `shift`. 
3) choose any upper case symbol and pressed Enter key on a laptop.
4) there no selected symbol on the textarea

**Comment by Mottie** [comment]
Hi @bsurai!

Hmm, thanks for letting me know... I'm not sure why it's not working! I'll try to get this fixed ASAP.

**Comment by Mottie** [comment]
Wow, this has been broken since v1.26.12...
