### ISSUE TITLE
Keyboard without input field

### ISSUE THREAD

**Issue by gionapaolini** [Mottie/Keyboard#575]
Hi, first of all nice job with this work, it's super nice!
I' m trying to use it in an application running on a touchscreen display in which different people should be able to write on different parts of the screen. Problem is that to do so I need to avoid input fields, since they require focus to work and you cannot focus on different inputs at the same time.

Question is, is there a way to handle the events coming from the keyboard such that I don't need to bind it to a text field? 

Thanks in advance and have a great day!

**Comment by Mottie** [comment]
Hi @gionapaolini!

Sorry, in the current state of this plugin it is not possible to use the keyboard without it being attached to an input or textarea; sadly it won't work with contenteditable elements either... you could use a hidden input.

There was a prior discussion on how to implement the keyboard for multiple users in #415. Maybe the demo there would help?

I do plan to rewrite this plugin soon (see #559), I've just been so swamped lately that I've had to keep putting it off.

**Comment by gionapaolini** [comment]
@Mottie It seems to be exactly what I need. I'm still not sure if the fastclick library will make it possible to write into multiple inputs without noticing the shift of the focus. I'm gonna try soon. 
Thank you very much!

**Comment by Mottie** [comment]
The keyboard will now work with contenteditable elements, stable as of v1.27.2.
