### ISSUE TITLE
extend specific button size

### ISSUE THREAD

**Issue by almih2m** [Mottie/Keyboard#577]
is there any way to extend specific button width?

I try to extend 0 button .to make a numeric keyboard

**Comment by Mottie** [comment]
Hi @almih2m!

Each key will include a class name that matches the text of the key. So the `0` num key will have a class of `ui-keyboard-0`. Extra unicode characters will get their decimal value equivalent &ndash; you can get more details on the [theme wiki page](https://github.com/Mottie/Keyboard/wiki/Theme).

[Here is a demo with an wide zero button](http://jsfiddle.net/Mottie/egb3a1sk/2825/):

```css
.ui-keyboard-0 {
  width: 6.5em;
}
```

```js
$(function() {
  $('#keyboard').keyboard({
    layout: 'custom',
    customLayout: {
      'normal': [
        '= ( ) {b}',
        '{clear} / * -',
        '7 8 9 +',
        '4 5 6 {sign}',
        '1 2 3 %',
        '0 {dec}'
      ]
    }
  });
});
```

**Comment by Mottie** [comment]
Keys added to the keyboard will have a class name that includes the text  or decimal equivalent value for the key character(s) &ndash; you can get more details on the [theme wiki page](https://github.com/Mottie/Keyboard/wiki/Theme).

For the num `0` key, a class name of `ui-keyboard-0` is added. Use the class to make it wider:

```css
.ui-keyboard-0 {
  width: 6.5em;
}
```

I set up [this demo](http://jsfiddle.net/Mottie/egb3a1sk/2825/) for you:

```js
$(function() {
  $('#keyboard').keyboard({
    layout: 'custom',
    customLayout: {
      'normal': [
        '= ( ) {b}',
        '{clear} / * -',
        '7 8 9 +',
        '4 5 6 {sign}',
        '1 2 3 %',
        '0 {dec}'
      ]
    }
  });
});
```

**Comment by almih2m** [comment]
Also is there any way to extend the size of the button to be on 2 rows?
 

another thing,
in your way, the size of all zeros button will change,

and I have more than keyboard type when I use that way all keyboards will effect

is there any way to solve this problem?

Thank you a lot

**Comment by Mottie** [comment]
You can use the ID of the target element... in the demo I shared, the input ID is "keyboard", so the id on the keyboard that opens ends up being "keyboard_keyboard" (id = target input id + "_keyboard").

if the same keyboard has different layouts, then use the `visible` callback function to modify the ID.

To extend the button to cover two rows, add some height to the button... it's all controlled by CSS. On the main wiki page under [layouts](https://github.com/Mottie/Keyboard/wiki#layout) you'll see [a "Different sized key" demo](https://jsfiddle.net/Mottie/uw7hmL6q/) that uses absolute positioning to make an extra large enter button.

**Comment by almih2m** [comment]
thank you a lot: 👍
