### ISSUE TITLE
Taking input inside Javascript Prompt using Mottie Keyboard

### ISSUE THREAD

**Issue by perumal** [Mottie/Keyboard#578]
Hi Mottie,
 
          Can you please help me on how to take input inside Javascript Prompt using Mottie Virtual Keyboard.

**Comment by Mottie** [comment]
Hi @perumal!

A javascript prompt is created and controlled by the browser, [all javascript processing is halted while it is active](https://developer.mozilla.org/en-US/docs/Web/API/Window/prompt), so there isn't any way to accomplish what you ask.

As an alternative, you could use a custom dialog box like [SweetAlert](http://t4t5.github.io/sweetalert/) or [Noty](http://ned.im/noty/).

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
