### ISSUE TITLE
switching shift button view.

### ISSUE THREAD

**Issue by bsurai** [Mottie/Keyboard#580]
Hi. I'd like to have different views for shift button when shifting to lower and upper case. Is it possible to make settings as below?

```
let keyboardOptions:  = {
    display: {
...
        "S": `ABC`, // 'shift' to upper case
        "s": `abc`,  // 'shift' to lower case
	},
...
```

**Comment by Mottie** [comment]
Hi @bsurai!

It is not currently possible to display two different values for the shift key, but you could set the display to the letter "s" then use css to change the appearance of the uppercase version - [demo](http://jsfiddle.net/Mottie/egb3a1sk/2848/)

CSS

```css
.ui-keyboard-keyset-shift .ui-keyboard-shift {
  text-transform: uppercase;
}
```

Script

```js
$(function() {
  $('#keyboard').keyboard({
    display: {
      'shift': 's'
    }
  });
});
```

Or, you could use the [`visible` callback](https://github.com/Mottie/Keyboard/wiki/Methods#visible) function to target and directly change the key's displayed text (in 2 places; [demo](http://jsfiddle.net/Mottie/egb3a1sk/2849/)):

```js
$(function() {
  $('#keyboard').keyboard({
  	display: {
    	'shift': 's' // lower case displayed value
    },
    visible: function(e, kb) {
      // change uppercase displayed value
      var $shift = kb.$keyboard.find('.ui-keyboard-keyset-shift .ui-keyboard-shift');
      $shift
      	.attr('data-html', '<span class="ui-keyboard-text">S</span>')
      	.find('span').text('S');
    }
  });
});
```

**Comment by bsurai** [comment]
Yep. I have used css.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
