### ISSUE TITLE
moving up from last right key in the Navigation extension. 

### ISSUE THREAD

**Issue by bsurai** [Mottie/Keyboard#581]
Here is demo https://mottie.github.io/Keyboard/docs/navigate.html

Case:
1) assume 'Cancel' is active now.
2) user presses Up button on laptop keyboard
3)  'x' button has been activated because 'Cancel' and 'x' have index 2 in their arrays.

I prefer to get different 3rd step.
3) right 'shift' has been activated because 'Cancel' and right 'shift' are last in theirs arrays.

May I implement it?

**Comment by Mottie** [comment]
Hi @bsurai!

Sure go for it! I would appreciate some help!

**Comment by Mottie** [comment]
Available in v1.26.26, thanks again @bsurai!
