### ISSUE TITLE
Bootstrap Validator

### ISSUE THREAD

**Issue by movitch** [Mottie/Keyboard#582]
Hi @Mottie,

I would like to ask your help once again. I have integrated bootstrap validator into a form. It's seems to work as I would like with the physical keyboard. However, using the virtual keyboard, events are not triggered as with the physical keyboard and validation does not occur. Could you guide me?

Thanks by advance.

Regards

**Comment by Mottie** [comment]
Hi @movitch!

If you could please modify [this demo](http://jsfiddle.net/Mottie/egb3a1sk/2850/) to show the current implementation, I could better help troubleshoot the problem. Also, make sure to have the [`acceptValid` option](https://github.com/Mottie/Keyboard/wiki/Usability#acceptvalid) set to `true` as well as use the [`validate` function](https://github.com/Mottie/Keyboard/wiki/Methods#validate).

**Comment by movitch** [comment]
Hi @Mottie ,

Thank you for your help. 

I finally found a workaround. If that can help.
By forcing data-bv-trigger = "keyup" in the HTML page at each input field, it works and bootstrap validator trigger.

Regards
