### ISSUE TITLE
Bigger Keyboard

### ISSUE THREAD

**Issue by Trony** [Mottie/Keyboard#584]
Hi,
is there a way to create a little bigger than the default keyboad ?

thanks.

**Comment by Mottie** [comment]
Hi @Trony!

Check out the [FAQ entry](https://github.com/Mottie/Keyboard/wiki/FAQ#changesize) on changing the size of the keyboard.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
