### ISSUE TITLE
nice validation on input it self

### ISSUE THREAD

**Issue by almih2m** [Mottie/Keyboard#585]
is there any way that to make validation in input with a nice message that shows upper the input 

Example: use verifyjs library to make validation before close keyboard?

**Comment by Mottie** [comment]
Hi @almih2m!

There is a built-in [`validate` callback function](https://github.com/Mottie/Keyboard/wiki/Methods#validate) which can be used with any validation library &ndash; make sure to set the [`acceptValid` option](https://github.com/Mottie/Keyboard/wiki/Usability#acceptvalid) to activate this callback. Also check out the [`autoAcceptOnValid` option](https://github.com/Mottie/Keyboard/wiki/Usability#autoacceptonvalid).

There isn't a message or tooltip to show the state of the validation, but the accept button will get a class of either "ui-keyboard-valid-input" or "ui-keyboard-invalid-input". A working example can be seen with the ["Custom: Hex Code" demo](https://mottie.github.io/Keyboard/#hex). There are additional implementation examples included with the `validate` callback function documentation.

If you need assistance, please modify [this demo](http://jsfiddle.net/Mottie/egb3a1sk/) to make it easier for me to find any problems or provide help with the specific library being used.

**Comment by almih2m** [comment]
so we can use that code

validate : function(keyboard, value, isClosing){
   
         var valid = /^\d{3}$/g.test(value);
        if (isClosing && valid) {

            // *** closing and valid ***
            return true;
        } else if (isClosing && !valid) {
            $(".ui-keyboard-preview-wrapper").append('<div id="keyboard-error-message" style="font-size: 6PX" class="container-fluid p-r-20"><div style="padding:10px;" class="alert alert-danger alert-dismissable fade in"></a> <Error</div></div>');
            // *** closing and not valid ***
            // add an indicator/popup here to tell the user the input is not valid
            // keyboard.$preview.addClass('form-error-message') ;// needs css: .red-border { border: #f00 1px solid; }
            setTimeout(function(){
                $("#keyboard-error-message").remove();
              
            }, 3000);
            // fire off a canceled event
            keyboard.$el.trigger('canceled', [ keyboard, keyboard.el ]  );
            return false;
        }

        // *** not closing ***
        // continuous checking during input, so don't go nuts here
        // accept button is enabled/disabled automatically if "acceptValid" is true
        return valid;


    },

//remark: I use CSS of bootstrap error message

did you have any addition improve?
also if we can make it on key up to real time validation

**Comment by Mottie** [comment]
Maybe instead of adding a block that moves the keys down, you could add a tooltip... [something like this](https://jsfiddle.net/Mottie/gfgkb4o1/50/):

CSS

```css
#keyboard-error-message + .tooltip .tooltip-inner {
  background: #f2dede;
  color: #a94442;
}
#keyboard-error-message + .tooltip .tooltip-arrow {
  border-top-color: #ebccd1;
}
```

Script

```js
var timer,
  tooltipVisible = false;

function validationTooltip($keyboard, state) {
  // if the keyboard is closed before this timeout fires, then the
  // $keyboard reference will be an empty array; and
  // "#keyboard-error-message" will not exist on initial check
  if ($keyboard.length && $keyboard.find('#keyboard-error-message').length) {
    $keyboard.find('#keyboard-error-message').tooltip(state);
    tooltipVisible = state === 'show';
  }
}

$('#keyboard').keyboard({
    layout: 'qwerty',
    css: {
      // input & preview
      input: 'form-control input-sm',
      // keyboard container
      container: 'center-block dropdown-menu', // jumbotron
      // default state
      buttonDefault: 'btn btn-default',
      // hovered button
      buttonHover: 'btn-primary',
      // Action keys (e.g. Accept, Cancel, Tab, etc);
      // this replaces "actionClass" option
      buttonAction: 'active',
      // used when disabling the decimal button {dec}
      // when a decimal exists in the input area
      buttonDisabled: 'disabled'
    },
    visible: function(e, kb) {
      $(".ui-keyboard").prepend('<div id="keyboard-error-message" data-toggle="tooltip" title="Invalid Entry!"></div>');
    },
    acceptValid: true,
    validate: function(keyboard, value, isClosing) {

      var valid = /^\d{3}$/g.test(value);

      clearTimeout(timer);
      if (valid) {
      	validationTooltip(keyboard.$keyboard, 'hide');
      }
      if (isClosing && valid) {
        // *** closing and valid ***
        return true;
      } else if (!valid) {
        // prevent tooltip blinking when "show" is called on a visible tooltip
        if (!tooltipVisible) {
	        validationTooltip(keyboard.$keyboard, 'show');
  	      // *** closing and not valid ***
    	    // add an indicator/popup here to tell the user the input is not valid
      	  // keyboard.$preview.addClass('form-error-message') ;
          // needs css: .red-border { border: #f00 1px solid; }
        }
        timer = setTimeout(function() {
         	validationTooltip(keyboard.$keyboard, 'hide');
        }, 3000);
        // fire off a canceled event
        keyboard.$el.trigger('canceled', [keyboard, keyboard.el]);
        return false;
      }

      // *** not closing ***
      // continuous checking during input, so don't go nuts here
      // accept button is enabled/disabled automatically if "acceptValid" is true
      return valid;
    }
  })
  // activate the typing extension
  .addTyping({
    showTyping: true,
    delay: 50
  });
```

**Comment by almih2m** [comment]
can you make a demo with out make keys down effect?

I mean error shows only if user click on ok button

**Comment by Mottie** [comment]
You can rearrange the code in the `visible` callback a bit ([demo](https://jsfiddle.net/Mottie/gfgkb4o1/52/)):

```js
validate: function(keyboard, value, isClosing) {

  var valid = /^\d{3}$/g.test(value);

  if (valid) {
    validationTooltip(keyboard.$keyboard, 'hide');
  }
  if (!tooltipVisible) {
    clearTimeout(timer);
  } else {
    timer = setTimeout(function() {
      validationTooltip(keyboard.$keyboard, 'hide');
    }, 3000);
  }
  if (isClosing && valid) {
    // *** closing and valid ***
    return true;
  } else if (isClosing && !valid) {
    // prevent tooltip blinking when "show" is called on a visible tooltip
    if (!tooltipVisible) {
      validationTooltip(keyboard.$keyboard, 'show');
      // *** closing and not valid ***
      // add an indicator/popup here to tell the user the input is not valid
      // keyboard.$preview.addClass('form-error-message') ;
      // needs css: .red-border { border: #f00 1px solid; }
    }
    // fire off a canceled event
    keyboard.$el.trigger('canceled', [keyboard, keyboard.el]);
    return false;
  }

  // *** not closing ***
  // continuous checking during input, so don't go nuts here
  // accept button is enabled/disabled automatically if "acceptValid" is true
  return valid;
}
```

**Comment by almih2m** [comment]
Is there any way to apply this code on same keyboard but with angular version  ?

https://github.com/antonio-spinelli/ng-virtual-keyboard

Thank you a lot

**Comment by Mottie** [comment]
Hi @almih2m!

Sorry, I don't know angular well enough to answer that question.

**Comment by LeReveur711** [comment]
Hey @almih2m!

Which version of Angular would you like to use?

**Comment by almih2m** [comment]
Angular 1.6

**Comment by LeReveur711** [comment]
If I understand correctly, you want to know how to use both together and integrate the mottie code?

If that's so, you can install both with bower for example:
"keyboard": "~1.26.26",
"ng-virtual-keyboard": "~0.2.0"

Include all in your index.html:
<script src="bower_components/keyboard/dist/js/jquery.keyboard.min.js"></script>
        <script src="bower_components/keyboard/dist/js/jquery.keyboard.extension-typing.min.js"></script>
        <script src="components/keyboard/languages/fr.js"></script>
        <script src="components/keyboard/layouts/french-light.min.js"></script>
        <script src="bower_components/ng-virtual-keyboard/dist/ng-virtual-keyboard.min.js"></script>

Into your app.js don't forget to import ng-virtual-keyboard module like that and configue Keyboard:
angular.module('myapp', [
    ...,
    'ng-virtual-keyboard',
    ...,
  ]).config(['VKI_CONFIG', function(VKI_CONFIG) {
    VKI_CONFIG.language = 'fr';
    VKI_CONFIG.layout = 'french-azerty-light';
    ......... apply your new code here ........
  }])
  .run(..........));

**Comment by almih2m** [comment]
Thank You 
I think I have problem on bootstrap file, I will test the code again

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
