### ISSUE TITLE
Virtual Keyuboard with jquery 1.7

### ISSUE THREAD

**Issue by mostafa358** [Mottie/Keyboard#586]
how can i use this nice keyboard with jquery 1.7 or less?
i cant use jquery 1.8 or higher

**Comment by Mottie** [comment]
Hi @mostafa358!

Hmm, it looks like I used a `.prop()` in the code which is only available in jQuery v1.6+. So, I either need to work around that to change the documentation which states that jQuery v1.4.3+ is supported.

I set up [this demo](http://jsfiddle.net/Mottie/egb3a1sk/2902/) which is using jQuery 1.7 without any problems. Make sure to include the appropriate version of jQuery UI, if you're using it, or the positioning won't work correctly.

**Comment by mostafa358** [comment]
Thanks For Your Answer.
But My Problem does'n Solve,
I use Dojo and Jquery 1.7 and when i use [this sample ](http://jsfiddle.net/Mottie/egb3a1sk/2902/) i have error in page.
in other way i know dojo and jquery 1.8 or higher confilct

**Comment by Mottie** [comment]
What error?

**Comment by mostafa358** [comment]
i screen shot from my error.
usually i see  multipleDefine Error Because Jquery Confilct with Dojo and i cant Handeled.
what Your Opinion?

![pic1](https://user-images.githubusercontent.com/18675860/29106628-49258286-7ceb-11e7-8f92-c5f48d35d1fb.PNG)
![pic2](https://user-images.githubusercontent.com/18675860/29106629-492bd2c6-7ceb-11e7-9b85-af403137ea04.jpg)

**Comment by Mottie** [comment]
Oh, it appears that jQuery is being loaded *after* the keyboard. Move jQuery above jQuery UI in that list and it *should* start working properly.

**Comment by mostafa358** [comment]
I found one thins.
i add Jquery and Jquery.ui and that didnt have problem but when i add jquery.keyboard this error is occured.
![pic4](https://user-images.githubusercontent.com/18675860/29159297-36afc372-7dc3-11e7-96cd-4876e22298cc.png)
this error show:  jquery.keyboard are conflict with dojo on a command in jquery.keyboard.
Can You Check This?

**Comment by Mottie** [comment]
The typing extension is inside of an enclosure, so it doesn't depend on the jQuery `$` definition. The only way to get that error, I think, is due to jQuery not being defined. Please make sure the typing extension is loaded *after* the keyboard plugin.

I'll have this fix available by the weekend.

**Comment by mostafa358** [comment]
`
<script type="text/javascript" src="/js/keyboard/jquery.min.js"></script>
<script type="text/javascript" src="/js/keyboard/jquery-ui.min.js"></script>
<script type="text/javascript" src="/js/keyboard/jquery.keyboard.js"></script>
<script type="text/javascript" src="/js/keyboard/jquery.keyboard.extension-typing.js"></script>
<script type="text/javascript" src="/js/keyboard/jquery.mousewheel.js"></script>
`
this code i write for insert this file and ordering is shows. first jquery then other.

thanks for your support
