### ISSUE TITLE
Keyboard appearing animation. 

### ISSUE THREAD

**Issue by ExmoDesign** [Mottie/Keyboard#587]
Hello, is it possible to set an animation when keyboard shows up? like fadeIn/Out or SlideUp

**Comment by Mottie** [comment]
Hi @ExmoDesign!

You can use the `beforeVisible` callback function to quickly set the final position of the keyboard (if determined by the input location), then use whatever effect you want... [this demo](http://jsfiddle.net/egb3a1sk/2966/) is using one of jQuery UI's custom [`show` effects](http://jqueryui.com/show/).

```js
$(function() {
  $('#keyboard').keyboard({
      beforeVisible: function(e, keyboard, el) {
      	// set positioning quickly
        keyboard.$keyboard.show();
        keyboard.$keyboard.position(keyboard.position);
        keyboard.$keyboard.hide();
        // jQuery UI show effects (http://jqueryui.com/show/)
      	keyboard.$keyboard.show('bounce');
      }
    })
    .addTyping({
      showTyping: true,
      delay: 250
    });
});
```

If the keyboard is positioned at the bottom of the screen, or somewhere else, then you don't need to set the positioning before applying the custom show effect.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
