### ISSUE TITLE
Prefilled data in input or textarea

### ISSUE THREAD

**Issue by Akhileshkumarr** [Mottie/Keyboard#594]
Hi !
I have a trouble... I'm using the virtualkeyboard in a meteor js project. i want to prefilled data in input or textarea
please help how to do that
thank you.

**Comment by Mottie** [comment]
Hi @Akhileshkumarr!

Fill the input or textarea using the same method that is always used to fill an input or textarea.

```html
<input id="keyboard" value="This is the input value">
<textarea id="keyboard2">This is the textarea value</textarea>
```

**Comment by Akhileshkumarr** [comment]
Thanks for the reply, I tried it this way before but i figured out I messed up something at that time. Now its working fine :) 
Cheers!
