### ISSUE TITLE
Only lowercase keyactions are processed

### ISSUE THREAD

**Issue by vatioz** [Mottie/Keyboard#595]
If you try example from wiki on "Adding a keyaction" with one small modification - you use **upper case** letter in the name of the function, it will **not work**. The custom key will not show in your layout.

So this code works:  

```javascript
    $.keyboard.keyaction.test = function(base) {
  alert("you smell like Cheese");
};

$("#keyboard").keyboard({
  layout: "custom",
  display: {
    test: "TEST"
  },
  customLayout: {
    default: ["{test}"]
  }
});
```

But this code doesn't work:  

```javascript
    $.keyboard.keyaction.testMe = function(base) {
  alert("you smell like Cheese");
};

$("#keyboard").keyboard({
  layout: "custom",
  display: {
    testMe: "TEST"
  },
  customLayout: {
    default: ["{testMe}"]
  }
});
```

I didn't find any mention of a rule *"don't use uppercase in keyaction names"*, so I suspect this to be a bug.

**Comment by Mottie** [comment]
Hi @vatioz!

I set up [this demo](http://jsfiddle.net/egb3a1sk/3056/) combining the two examples, and they are both working as expected.

```js
$(function() {

  $.keyboard.keyaction.test = function(base) {
    base.insertText("Cheese");
  };
  $.keyboard.keyaction.testMe = function(base) {
    base.insertText("Cheese2");
  };

  $("#keyboard").keyboard({
    layout: "custom",
    display: {
      test: "TEST",
      testMe: "TESTME"
    },
    customLayout: {
      default: ["{test} {testMe}"]
    }
  });
});
```

**Comment by vatioz** [comment]
Ok, I see. Can this be caused by me using version 1.18.12?

**Comment by Mottie** [comment]
I don't think so... I looked through the revision history and didn't see any changes that would change the above behavior. Anyway, it's always best to use the latest version.

**Comment by vatioz** [comment]
Ok, so it seems to be some problem with my set up (I tested it inside our bigger project), something else is probably affecting it. 
I am sorry to waste your time, sir.

**Comment by Mottie** [comment]
No worries!
