### ISSUE TITLE
How to place the Keyboard on bottom of screen?

### ISSUE THREAD

**Issue by sohrabhejazi** [Mottie/Keyboard#597]
I want to place the Keyboard on bottom of screen So that when we click a TextEdit, the keyboard appears in button of screen. The button of current frame is my purpose.

**Comment by sohrabhejazi** [comment]
I solved it:
    top: auto;
    bottom: 16rem;
    position: fixed;

**Comment by Mottie** [comment]
Hi @sohrabhejazi!

I'm glad you figured it out! By the way, there are a ton of demos on the [main wiki page](https://github.com/Mottie/Keyboard/wiki#main-demos) if you need examples.
