### ISSUE TITLE
Caret is missing when keyboard is opened for input in a bootstrap 3 modal.

### ISSUE THREAD

**Issue by robsdedude** [Mottie/Keyboard#599]
I've prepared a minimal [JSFiddle](https://jsfiddle.net/egb3a1sk/3076/).

First click into the visible input field under "works": Everything is fine and you'll see a caret as expected.
Now click the "Launch demo modal" button. A modal with an input field will show up. Click into that input field: The caret is missing.

I couldn't find out why that happens.

**Comment by Mottie** [comment]
Hi @robsdedude!

Thanks for reporting this issue, and providing a demo! It does look like a problem. I'll try to investigate the cause some time today.

**Comment by Mottie** [comment]
Hmm, I created [this demo](https://jsfiddle.net/Mottie/jLu8ysh0/) a while ago, and when `usePreview` is `false` everything works great; but, setting that to `true` doesn't allow you to click inside the input. I don't remember if I had `usePreview` set as `true` when I initially created the demo. I see the same issue using Bootstrap v4.

Anyway, I'll need a bit more time to investigate the cause.

**Comment by robsdedude** [comment]
Well, that demo helped. Removing the backdrop and setting `usePreview` to `false` is at least a temporal quick-fix.

**Comment by Mottie** [comment]
Whew, ok I found the issue. It can be solved in two ways:

1. Append the keyboard inside of the modal in the `beforeVisible` callback ([demo](https://jsfiddle.net/egb3a1sk/3083/)).
2. Disable the modal re-focus binding (`focusin.bs.modal`)... this may cause issues since they added a comment that this function prevents an infinite focus loop ([ref](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/modal.js#L281-L289))

    ```js
    visible: function(e, keyboard, el) {
      $(document).off('focusin.bs.modal');
      var modal = $('<div class="keyboard-modal"></div>');
      modal.click(function(e) {
        keyboard.accept();
        return false;
      });
    },
    ```

**Comment by robsdedude** [comment]
Perfect! I've extended your solution so that it works with several modals:
```javascript
beforeVisible : function(e, keyboard, el) {
  inModal = $(el).parents('.modal').length > 0;
  if (inModal) {
    keyboard.$keyboard.appendTo($(el).parent());
  }
}
```
From my side, this issue can be closed now, except you want to integrate this knowledge somehow into the code base.

**Comment by Mottie** [comment]
Added to the [FAQ page](https://github.com/Mottie/Keyboard/wiki/FAQ#bsmodal). Thanks!
