### ISSUE TITLE
invalid-meta The “main” field has to contain only 1 file per filetype; found multiple .js files

### ISSUE THREAD

**Issue by mattspaulding** [Mottie/Keyboard#600]
Bower install is giving this error:

> invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .js files: ["dist/js/jquery.keyboard.js","layouts/keyboard-layouts-combined.js","layouts/keyboard-layouts-greywyvern.js","layouts/keyboard-layouts-microsoft.js"]

**Comment by Mottie** [comment]
Hi @mattspaulding!

Thanks, I'll take a look.

**Comment by Mottie** [comment]
I'm not sure if I need to update the version before it'll work... I can push a new release if you need it.

**Comment by mattspaulding** [comment]
@Mottie I imagine others will soon be affected by this as they update bower. A new patch release would be nice 😬

**Comment by Mottie** [comment]
I'm trying to figure out how to make the backspace work properly after pressing enter inside of a contenteditable element. It's more complicated than it sounds... Once I get that resolved, I'll provide a new release.

**Comment by mattspaulding** [comment]
Everything is more complicated than it sounds. 😓 Thanks for the quick response and fix!
