### ISSUE TITLE
Change input text without "accept" button

### ISSUE THREAD

**Issue by macdasi** [Mottie/Keyboard#602]
Is there a way I can configure the keyboard to change the input without pressing "accept" button ? 
I want the client to be able to open keyboard -> press keys -> when exit see the change

**Comment by Mottie** [comment]
Hi @macdasi!

Set the [`autoAccept` option](https://github.com/Mottie/Keyboard/wiki/Usability#autoaccept) to `true` - see [demo](https://jsfiddle.net/egb3a1sk/3089/).

**Comment by macdasi** [comment]
10x
