### ISSUE TITLE
Non-fixed positioning

### ISSUE THREAD

**Issue by timmyomahony** [Mottie/Keyboard#603]
I want the keyboard to be inserted into an element instead of being fixed-positioned at the top-level. Is this possible?

**Comment by Mottie** [comment]
Hi @timmyomahony!

This sounds like it is related to the [FAQ entry](https://github.com/Mottie/Keyboard/wiki/FAQ#q-how-do-i-use-the-keyboard-in-a-bootstrap-modal) on how to use the keyboard with a Bootstrap modal.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
