### ISSUE TITLE
Automatic regex ignore keys after {empty}

### ISSUE THREAD

**Issue by chepseskaf** [Mottie/Keyboard#606]
Hi,

When I try to create custom layout, I've found that an empty key {empty} will invalidate next key when option `restrictInput` is activated.

In the sample https://jsfiddle.net/chepseskaf/ow2hwtya/2/, the `0` is uanvailable until modifying `restrictInclude` or disable `restrictInput`.

Can I submit a pull request ?

Regards,

**Comment by Mottie** [comment]
Hi @chepseskaf!

Thanks for letting me know! No need for a PR since I've already found and fixed the problem. I'll provide a new release shortly.
