### ISSUE TITLE
MaxLength excluding sign and decimal symbol

### ISSUE THREAD

**Issue by nvkfr** [Mottie/Keyboard#608]
Hi @Mottie,

I'm looking to set a maxLength excluding the decimal symbol and the negative sign. An example of what I'm trying to do : 

maxLength = 4;
input = -ii.dd => works

There are 6 characters but I need to have a way to only track numbers (in this case, 4 numbers). Is there currently a way to do this ?

On a side note, because I will probably be asked to do this, is there a way to limit the number of characters after the decimal symbol ?

Appreciate your help with this. Thanks in advance !

**Comment by Mottie** [comment]
Hi @nvkfr!

There are a bunch of demos on the [Home wiki page](https://github.com/Mottie/Keyboard/wiki#manipulating-text), one of which is a demo named "[Numpad limits to two decimal places](https://jsfiddle.net/Mottie/e1c8nqe2/)"; but that doesn't account for a sign or integer part.

I set up [this demo](https://jsfiddle.net/Mottie/kgd3d9uc/) that should give you a general idea of how to implement it &ndash; it's not perfect and I'm not sure of your requirements.

```js
$(function() {

  var maxInteger = 3,
    maxFractional = 2,

    regex = new RegExp(`([+-]?\\d{${maxInteger}}(?:\\.\\d{0,${maxFractional}})?)`);

  $('#keyboard').keyboard({
    layout: 'custom',
    customLayout: {
      'normal': [
        '7 8 9 {b}',
        '4 5 6 {clear}',
        '1 2 3 {c}',
        '0 {dec} {empty} {a}'
      ]
    },
    restrictInput: true,
    change: function(e, keyboard, el) {
      var change,
        val = keyboard.$preview.val().replace(/[^\d-.]/g, ''),
        c = $.keyboard.caret(keyboard.$preview),
        start = c.start,
        end = c.end,
        restrict = val.match(regex);
      if (restrict) {
        restrict = restrict.slice(1).join('');
      } else {
        restrict = val;
      }
      keyboard.$preview.val(restrict);
      change = restrict.length - val.length;
      start += change;
      end += change;
      $.keyboard.caret(keyboard.$preview, start, end);
      // enable/disable decimal key as needed
      keyboard.checkDecimal();
    }
  });

});
```

**Comment by nvkfr** [comment]
Hi Mottie,

A huge thanks for your quick answer, will manage with this :)

Best regards,

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
