### ISSUE TITLE
Is it possible to pass \ register a mode as a delegate function?

### ISSUE THREAD

**Issue by Jonathan435** [Mottie/Keyboard#609]
Hi, 
I need to change values of tokens dynamically, using custom mode that i wrote.
is it possible to change modes by passing delegate function of the mode, or maybe there is a better way,
btw i am implementing codemirror using angular 2.
thank you.

**Comment by Mottie** [comment]
Hi @Jonathan435!

Did you figure this out? I'm not exactly sure what you're asking, so if you still need help, please clarify and share some of the code you're using. Thanks!
