### ISSUE TITLE
Input loses value when use more then one input and usePreview: false

### ISSUE THREAD

**Issue by Tora-Bora** [Mottie/Keyboard#617]
I try to setup static keyboard which hungs on the bottom of view and enters text to a few inputs. I set usePreview: false,  alwaysOpen: true. I enter text to the first input, then click to the next input and text from previous input is disappeared.

**Comment by Tora-Bora** [comment]
I found the sample [https://jsfiddle.net/Mottie/9t1nrrbh/]() and it demonstrates the problem, impossible to fill both inputs.

**Comment by Mottie** [comment]
Hi @Tora-Bora!

The [`autoAccept` option](https://github.com/Mottie/Keyboard/wiki/Usability#autoaccept) is set to `false` by default. Set it to `true` and the changes will be retained without pressing the accept button - [demo](https://jsfiddle.net/Mottie/9t1nrrbh/12/).

**Comment by Tora-Bora** [comment]
Thanks a lot @Mottie !
