### ISSUE TITLE
Bug with plugin Navigator and MouseWheel

### ISSUE THREAD

**Issue by Tapia83** [Mottie/Keyboard#619]
Hi,
The plugin mouse wheel have to be 'avoided' when the plugin 'navigator' is used.
The bug is:
Click on a key with the mouse, the text is changing; now, use the navigator to add caracts. : The last key touched by the mouse keep the focus.
if the mousewheel is avoided, it works very good.
option: useWheel: false,
You can see this bug even on the 'navigator' examples page.

Bye,
Philippe.

**Comment by Mottie** [comment]
Hi @Tapia83!

I can't seem to follow the steps needed to reproduce this bug. Would you please elaborate or provide an animated gif. Thanks!

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
