### ISSUE TITLE
Import extensions using npm

### ISSUE THREAD

**Issue by Judahh** [Mottie/Keyboard#621]
How can I import Typing and extender using the npm package?
because this does not work:
import { KeyboardOptions, Typing, Extender } from 'virtual-keyboard';

**Comment by Mottie** [comment]
Hi @Judahh!

Hmm, I'm not sure that `import` would work since the code isn't using `export`, unless Babel handles that for you... Anyway, to include the extensions, you'll need to point to the files within the `node_modules` folder. Something like this:

```js
var jquery = require("jquery");
var virtualKeyboard = require("virtual-keyboard");
var typing = require("./node_modules/virtual-keyboard/dist/js/jquery.keyboard.extension-typing.min.js");
var extender = require("./node_modules/virtual-keyboard/dist/js/jquery.keyboard.extension-extender.min.js");
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
