### ISSUE TITLE
Physical Keyboard: jQuery is not defined

### ISSUE THREAD

**Issue by garethwarry** [Mottie/Keyboard#622]
**Problem** 
When typing using the physical keyboard, errors are thrown with each key stating "Uncaught ReferenceError: jQuery is not defined". Otherwise, the virtual keyboard works as intended. Input from the physical keyboard is even accepted, it just floods the console with errors.

```
C:\Development\TestProject\node_modules\virtual-keyboard\dist\js\jquery.keyboard.js:863 Uncaught ReferenceError: jQuery is not defined
    at HTMLInputElement.<anonymous> (C:\Development\TestProject\node_modules\virtual-keyboard\dist\js\jquery.keyboard.js:863)
    at HTMLInputElement.dispatch (C:\Development\TestProject\node_modules\jquery\dist\jquery.js:5206)
    at HTMLInputElement.elemData.handle (C:\Development\TestProject\node_modules\jquery\dist\jquery.js:5014)
```

**Versions**
node: v6.11.4
react: 16.0.0
jQuery: 3.2.1
jQuery UI: 1.12.1
virtual-keyboard: 1.25.28
yarn: v1.2.1

**Setup**
I'm using the [React version](https://github.com/Utzel-Butzel/react-virtual-keyboard) as recommended from the Mottie homepage. It doesn't appear to error in that package though. It errors in the virtual-keyboard package (which is what has me confused). Any suggestions? Using it as shown in [the example](https://github.com/Utzel-Butzel/react-virtual-keyboard) exactly.

**Comment by Mottie** [comment]
Hi @garethwarry!

Hmm, I'm still learning React, so I would have to guess that jQuery isn't being loaded before the keyboard plugin. If it is, then make sure it's only being loaded once.

**Comment by Mottie** [comment]
Hopefully I fixed this issue in https://github.com/Mottie/Keyboard/commit/cc721120e5b838f6984b45450756b779f1db53fe.

**Comment by garethwarry** [comment]
That commit resolves the issue. Thank you very much!

**Comment by Mottie** [comment]
v1.27.0 released now!
