### ISSUE TITLE
Something in there that is effecting touch events

### ISSUE THREAD

**Issue by emomooney** [Mottie/Keyboard#631]
Hi. 

I was hoping I would get a response as I just can't work out how to fix this myself. I am using your keyboard plugin with Electron and webviews. 

Everything works perfectly with touches everywhere and only mouse clicks on the keyboard, but once I use touch click events on the keyboard the other clickes within the pages are delayed. They don't work at all for about 10 seconds, this time may be accumulative.  Sorry if this is a bit vague. Any ideas at all? I could send you an example of the code if you want to take a look. 

Thanks for your time!

**Comment by Mottie** [comment]
Hi @emomooney!

In the past I've seen reports of touch delays. I don't know about Electron, but try these solutions that have worked in the past:

* Switch to use [PEP](https://github.com/jquery/PEP) and set the [`keyBinding` option](https://github.com/Mottie/Keyboard/wiki/Usability#keybinding) to use `pointerdown`.
* Install [fastclick](https://github.com/ftlabs/fastclick) to remove the 300ms delay between touch start and click event being fired. Make sure to read about [when it isn't needed](https://github.com/ftlabs/fastclick#when-it-isnt-needed) as you may only need some css to fix the problem.

Please let me know if you find a solution.

**Comment by emomooney** [comment]
Did you mean to use PEP instead of JQuery? 
I popped it in along side anyway and changed the keybinding but it didn't seem to help. 
It more than the touches are actually gone once you use the keyboard with touch instead of a mouse. It seems to be consistently gone for a minimum of 10 seconds, but I have a feeling that could be shorter or longer depending the amount of characters typed. 

Is there anyway of making the keyboard only use click events? Instead of listening for touchstart etc, or was that what the PEP would have done? 

Thanks for the quick response!

**Comment by Mottie** [comment]
PEP is independent of jQuery. I wanted you to try using pointer events, but you can change the `keyBinding` to `'click'` ([demo](http://jsfiddle.net/egb3a1sk/3336/)).

I'm still not sure why you're seeing that really long delay.

**Comment by emomooney** [comment]
Hey, so I didn't have access to a touchscreen for the weekend. Just testing the demo you set up at the moment, with just a 'click' event as the keybinding option, it actually doesn't work at all with touchscreen ( this is native windows touch ). I have set up click listeners on the body which fires with the touchscreen but the keyboard does not react at all. Will continue to work on it and see if I can find out where the problem is but it's strange.

**Comment by mellinger** [comment]
Experiencing this as well.

**Comment by Mottie** [comment]
Any update on this?

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
