### ISSUE TITLE
Problem with possible callbacks

### ISSUE THREAD

**Issue by lucas-signorini** [Mottie/Keyboard#632]
Hi,

I have several keyboards in one page, and they work pretty ok. 
In some of those there is a mask (simple functions like date mask), and i call it on beforeInsert method.
Everything goes well untill "something happens", and some of the masks stop working.

I can't tell what triggers this behaviour, but imagine that i fill every field, and then come back to some already filled field. What is wierd is that i can see my function working, as i type a date ('12/1'), i can see the '/' being added, but then it is removed, and the text is back to '121'.

What i cant understand is why it happens just after everything is filled, just in one field (i have 3 fields with mask, and each time a different one shows this problem), and why it is 'triggered' just after a release a key (if i hold the key in a physical KB , it fills the mas '11/11/1111', and when i release, it goes back to '11111111').

Do you have any idea what can be causing it? Is there any callback function that may be in my way?

Thats how i did it, the jquery selectors now are the most specific as possible to avoid "preview-clone" to get in the way.
```
 
../
beforeInsert : 
             format_date(w.charCodeAt(0));
            return w;
        },
/...

function format_date(keyCode){
    var value = $("#dataNascimento_keyboard .ui-keyboard-preview:not(.ui-keyboard-preview-clone)")[0].value;
    if(keyCode === 8){

    }else if(value.length === 2 || value.length === 5 ){
        $("#dataNascimento_keyboard .ui-keyboard-preview:not(.ui-keyboard-preview-clone)")[0].value = value +"/";
    }
}
```

**Comment by Mottie** [comment]
Hi @lucas-signorini!

I can't tell what's going on without seeing it in action. Please modify [this demo](http://jsfiddle.net/Mottie/egb3a1sk/) too duplicate the issue you're seeing.

**Comment by lucas-signorini** [comment]
Ok i made this example.

http://jsfiddle.net/egb3a1sk/3346/

To reproduce, please insert values for all 3 fields, and then fill every field again. For some reason maxlenght do not work there, so the expected format is 123.123.123-12, 12/12/1222 and (12) 12312-1231.

You will see the error when you see the mask being typed and then removed.

**Comment by Mottie** [comment]
The formatting isn't working because the second time the user types in the input, the `value.length === 0`, etc, won't be accurate because the input value contains all the numbers.

The way to get around this is to:
1. Save the caret position on input ([docs](https://github.com/Mottie/Keyboard/wiki/Methods#caret)).
2. Grab the entire input value.
3. Strip out all delimiters (e.g. `.`, `-`, `(`, `)` and `/`)
4. Reformat the value using something like [numeral.js](http://numeraljs.com/).
5. Update the input value.
6. Restore the caret position, but add one if the character to the right of the caret is a delimiter.

**Comment by lucas-signorini** [comment]
Hi @Mottie,

I manage to make it work with the mask.js plugin following your tips.

For future reference, that's how i did:

```
...
function(e, a, el,w, t){
            $(".ui-keyboard-preview").trigger('input');
        },
        beforeInsert : 
        function(e, a, el,w, t){
            if(w.charCodeAt(0) != 8){
                if($(".ui-keyboard-preview").length){
                    $(".ui-keyboard-preview").mask("99/99/9999");
                    var pos = $(".ui-keyboard-preview").val().length;
                    var kb = $('#dataNascimento_keyboard').getkeyboard();
                    $.keyboard.caret(kb.$preview, pos);            
                }
            }
            return w;       
        }, ....
```

Again, thank you very much for your fast answer :)

**Comment by Mottie** [comment]
I haven't tested it, I think you'll still encounter some issues using the length of the input, especially when editing the values after the first time:

If you do, try saving the caret using something like this:

```js
beforeInsert : function(e, kb, el, txt) {
  if(txt.charCodeAt(0) !== 8) {
    if($(".ui-keyboard-preview").length) {
      var pos = kb.caret();
      $(".ui-keyboard-preview").mask("99/99/9999");
      kb.caret(pos);            
    }
  }
  return txt;
}
```

**Comment by lucas-signorini** [comment]
I have tried everything.

My solution just seamed to work, but after some test's i got the same scenario again.
Tried to clear the text, removing the formatting, using specific selectors, every one of your suggestions, but nothing can change this behavior.
Even with no data filled, if you keep focusing on different fields, eventually one will break. It happens in just one field, and is can be in any masked field.
The funny thing is that if you use debugger on chrome, and go step by step, the bug disappear, but if you remove the breakpoint, there is the bug again...

I would like to know is why the mask is applied, and then removed. What could be the cause of the mask removal, i still think about callbacks, but i dont know what happens under the hood.

**Comment by Mottie** [comment]
Hi, sorry for the long delay. Any updates on this issue?

**Comment by lucas-signorini** [comment]
I didn't make any progress since my last comment. I remember that i try your suggestions, but problems still happens.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
