### ISSUE TITLE
'closeByClickEvent' not working?

### ISSUE THREAD

**Issue by Thosty** [Mottie/Keyboard#634]
Please look at [this example](https://jsfiddle.net/egb3a1sk/3352/). I assumed that the keyboard would close when I click outside the keyboard.

**Comment by Mottie** [comment]
Hi @Thosty!

It looks like there's a JS error that is causing the trouble. I'll get it fixed here shortly.

**Comment by Thosty** [comment]
Wonderful. Thanks a lot.
