### ISSUE TITLE
Destroy autocomplete

### ISSUE THREAD

**Issue by fozix** [Mottie/Keyboard#636]
Hi Mottie,

I have some memory leak using AngularJS, jquery and keyboard under IE8 and I dont know at this moment where it is comming from.

I'm searching for good way of destroying the autocomplete attached to a keyboard.

Can you help me with that ?

regards

**Comment by Mottie** [comment]
Hi @fozix!

You'll need to destroy the autocomplete instance, then unbind the extension listeners ([demo](https://jsfiddle.net/Mottie/8cdu2je0/)):

```js
$('#destroy').click(function(){
	var $kb = $('#keyboard'),
  	kb = $kb.getkeyboard();
  $kb.unbind(kb.autocomplete_namespace);
  $kb.autocomplete('destroy');
  delete kb.$autocomplete;
});
```

I think I'll add a method to destroy the extension internally.

**Comment by fozix** [comment]
Hi @Mottie,

Thank you for your help.
Adding a function to destroy the extension will be a good idea. I searched for it before posting this question.

Regards.

**Comment by Mottie** [comment]
A new autocomplete destroy method has been added to v1.27.4. See [the documentation](https://github.com/Mottie/Keyboard/wiki/Extension-Autocomplete#destroy).
