### ISSUE TITLE
Disable mobile keyboard with contenteditable div

### ISSUE THREAD

**Issue by carlosn8** [Mottie/Keyboard#637]
Hi, not sure if this is possible. I was able to remove the mobile keyboard by using the readonly property for the textarea option. Unfortunately with it the caret is not appearing, and there are some issue when moving with the cursor keys. I wanted to do the same with the contenteditable div, with it the caret appears, but even setting it to readonly the mobile keyboard appears. Anyone has played with this? It has been asked before, but not for the contenteditable option I think.

**Comment by Mottie** [comment]
Hi @carlosn8!

Hmm, I haven't tested it with a contenteditable element, but you can use the caret extension to replace the missing caret when the textarea/input is readonly - See https://jsfiddle.net/Mottie/24n8wsak/

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
