### ISSUE TITLE
How to set a selected autocomplete tag as keyboard content (or just accept it upon selection)

### ISSUE THREAD

**Issue by chipimix** [Mottie/Keyboard#639]
Hi there! First-timer here so I apologize for noob related issues.
Firstly, this plugin is awesome. Thank you so much for your work!

I'm struggling with the autocomplete extension.
In your excellent demo, when a user selects a listed autocomplete tag, as seen here:
![untitled-1](https://user-images.githubusercontent.com/15652959/34777636-daaddd98-f612-11e7-8397-467412803dd9.png)
Its contents are ignored, as seen here:
![untitled-2](https://user-images.githubusercontent.com/15652959/34777709-18554c6c-f613-11e7-8e87-7b3a9c7a2123.png)

I don't understand if this is on purpose.  Can I fetch this tag? Can I automatically accept it?

Thanks in advance!

**Comment by Mottie** [comment]
Hi @chipimix!

Hmm, that looks like a bug that got introduced recently. I'll take a look and get it fixed today.

**Comment by Mottie** [comment]
Thanks for reporting this problem. It's been fixed in v1.27.4.
