### ISSUE TITLE
beforeInsert with a telephone number

### ISSUE THREAD

**Issue by JL1946** [Mottie/Keyboard#642]
I worked a "beforeInsert" function to add a telephone number to a single input field and thought that I would share it with you:

```js
$(function() {
  var kb = $('.cl_telephone').keyboard({
    position: {
      // position to the right of top input within the window
      of: $("input:eq(0)"),
      my: 'right top+12',
      at: 'right top'
    },
    enterNavigation: true,
    maxLength: 16,
    layout: 'num',
    initialFocus: false,
    autoAccept: false,
    usePreview: true,

    beforeInsert: function(e, keyboard, el, txt) {
      var len = keyboard.$preview.val().length;
      if (len === 0 && keyboard.last.key !== "bksp") {txt = "+1(" + txt}
      if (len === 5 && keyboard.last.key !== "bksp") {txt = txt + ") "}
      if (len === 10 && keyboard.last.key !== "bksp") {txt = txt + "-"}
      if (len === 12 && keyboard.last.key === "bksp") {
        var value = keyboard.$preview.val();
        var newvalue = value.slice(0, -2);
        keyboard.$preview.val(newvalue);
        txt = "";
      }
      if (len === 8 && keyboard.last.key === "bksp") {
        value = keyboard.$preview.val();
        newvalue = value.slice(0, -3);
        keyboard.$preview.val(newvalue);
        txt = "";
      }
      if (len === 4 && keyboard.last.key === "bksp") {
        value = keyboard.$preview.val();
        newvalue = value.slice(0, -4);
        keyboard.$preview.val(newvalue);
        txt = "";
      }
      len = keyboard.$preview.val().length;
      /*alert(len);*/
      return txt;
    },
```

**Comment by Mottie** [comment]
Hi @JL1946!

Thanks! Sadly, that's not generic enough to handle any type of phone number.

Ref:
* https://docs.microsoft.com/en-us/globalization/locale/telephone-number
* https://msdn.microsoft.com/en-us/library/dn454587(v=vs.85).aspx
* https://stackoverflow.com/q/15745545/145346

**Comment by JL1946** [comment]
Hi rob:

thanks for your comments. However, my only interest at the moment is to 
deal with North American Numbers, My submission was meant to deal with a 
single input box as opposed to 3 as was presented on jsfiddle.

Sorry if it does not meet your expectations.

Joe

Rob Garrison wrote:

**Comment by Mottie** [comment]
Really! Thanks for sharing! I'm just saying the code would need to be adjusted to work with different telephone formats, since there are so many.

**Comment by Mottie** [comment]
I'm going to redirect future questions about this issue to #201 - since an input mask would solve this problem.
