### ISSUE TITLE
How to enable language translation in custom keyboard layout

### ISSUE THREAD

**Issue by jonalxh** [Mottie/Keyboard#643]
Hi friend, I wanna know how to enable language translation if I have a custom keyboard layout, actually I'm setting `language: 'es'` as the screenshot shows, but the keyboard keys are being shown in English still.

I know that I can edit the text shown in **display** settings, but I need it to be multilanguage and take advantage of the lang files.

Thanks a lot.

![image](https://user-images.githubusercontent.com/12530606/35105029-97fe9ad8-fc38-11e7-8ae5-e4fd678c89e4.png)

**Comment by Mottie** [comment]
Hi @jonalxh!

You should only need to load the needed [language files](https://github.com/Mottie/Keyboard/tree/master/dist/languages) along with the core.

To dynamically switch layouts and language, use the [`redraw` method](https://github.com/Mottie/Keyboard/wiki/Methods#redraw) with the named layout. To switch between custom layouts, add it as a named layout to `$.keyboard.layouts` and make sure to define the `lang`.

```js
jQuery.keyboard.layouts['my-custom-1'] = {
  "lang": ["en"],
  'normal': [
    '` 1 2 3 4 5 6 7 8 9 0 - = {bksp}',
    '{tab} q w e r t y u i o p [ ] \\',
    'a s d f g h j k l ; \' {enter}',
    '{shift} z x c v b n m , . / {shift}',
    '{accept} {space} {cancel}'
  ]
  // ...
};
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
