### ISSUE TITLE
In touch device on using lockInput, caret does not display on the touched letter

### ISSUE THREAD

**Issue by aravindG92** [Mottie/Keyboard#646]
When using lockInput method to disable the device keyboard, I am not able to see the caret on the focused  character even on using caretToEnd method. This is for touch device.

Eg: on typing "Milk" and i touch between i & l, the caret not shows up

**Comment by Mottie** [comment]
Hi @aravindG92!

When `lockInput` is set, you'll need to include the [caret extension](https://github.com/Mottie/Keyboard/wiki/Extension-Caret) to visually see the caret.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
