### ISSUE TITLE
Don't close keyboard every time on change input

### ISSUE THREAD

**Issue by shoudaos** [Mottie/Keyboard#648]
I have an issue, when i click on input the keyboard appears. Then i change input, and keyboard closes and appears again. 

Almost every time it looks good but sometimes you can see that shifting, in other words keyboard disappears in few milliseconds.

Is it possible not to close the whole keyboard every time but only change focused element?

**Comment by Mottie** [comment]
Hi @shoudaos!

I'm not exactly sure what you're seeing, but maybe try using the [`stayOpen` option](https://github.com/Mottie/Keyboard/wiki/Usability#stayopen)?

**Comment by shoudaos** [comment]
Yes, i saw this option, but i want to hide keyboard on unfocus. i want not to hide on REfocus.

**Comment by Mottie** [comment]
Would you please modify [this demo](http://jsfiddle.net/Mottie/egb3a1sk/) to show the issue being described.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
