### ISSUE TITLE
click of disabled key closes keyboard

### ISSUE THREAD

**Issue by debanjana** [Mottie/Keyboard#655]
Hi , 

The decimal / {dec} key is defined placed as shown below : 

```
[

    '{questiontool} 7 8 9 {bksp} {clear} {accept}',

    '{maxbtn} 4 5 6 {plusbtn}',

    '{defaultbtn} 1 2 3 {minusbtn} {prev}',

    '{minbtn} 0 {dec} {sign} {left} {next} {right}'

]
```

When a textbox already has decimal dot (.) , this key is disabled. 
1. On clicking the disabled  . key the keyboard closes. 
2. On tapping ( in touch mode) the disabled . key , the field is updated with . (ie the disabling is not working).

I would like the event to not fire on click of the disabled button. Also, I don't want the keyboard to close. 
Any idea how I can do that?
Thanks.

**Comment by Mottie** [comment]
Hi @debanjana!

I'm not able to duplicate the issue you're describing. I set up [this demo](http://jsfiddle.net/Mottie/egb3a1sk/3589/) with a plain `.` and a `{dec}`. Clicking the decimal button when disabled doesn't close the keyboard nor does it add a decimal. Would you please modify this demo to show the problem.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
