### ISSUE TITLE
Touch clicks delayed by one step

### ISSUE THREAD

**Issue by nicobaga** [Mottie/Keyboard#656]
Hello everyone!

I'm having a small issue regarding digitation on the digital keyboard. Whenever I try to input some text using a touchscreen, the letters are appear delayed by one step.

For the sake of example, if I'm writing "hello" I first press "h" and nothing happens, then as soon as I click "e" the "h" appears (but not the "e"). Going on, if I then press "l" i have the "e" showing up. How can I solve this?

The delay is not "time-based" (the letter appears after a certain time), but more "event-based" as the letter appear on the next input.

I'm running a web-page on Chrome (I'm not a web-developer, I'm just messing around so pardon me if the question is trivial). Don't esistate to ask for further information if required
NB: if i do the same input by clicking with the moues I have no such delay 

Thanks for your time :)

**Comment by Mottie** [comment]
Hi @nicobaga!

There have been some reports of a delay on touchscreens, but nothing as extreme as this.

Are you using the latest version of the keyboard? What initialization code is being used? Is this behavior seen in other browsers, like Firefox?

One thing you could try is including [PEP](https://github.com/jquery/PEP) (pointer events polyfill) and set the [`keyBinding` option](https://github.com/Mottie/Keyboard/wiki/Usability#keybinding) to use `pointerdown`.

You can also try out [fastclick](https://github.com/ftlabs/fastclick) to remove the 300ms delay between touch start and click event being fired; even though click isn't being used here, but make sure to read about [when it isn't needed](https://github.com/ftlabs/fastclick#when-it-isnt-needed) as you may only need some css to fix the problem.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
