### ISSUE TITLE
Can keyboard update preview and text input

### ISSUE THREAD

**Issue by msj121** [Mottie/Keyboard#657]
I don't need any validation and want the keyboard to update both the input and preview together, not wait until "Done" or closing the keyboard.

I am running on an ipad, and the keyboard is at the bottom of the screen. Sometimes the input is visible even with preview, I don't like that the input remains unchanged while preview does. It looks incorrect to the user.

I would love if I could either update both (let me know where to look to change the code even if I have to do this on my version only).
OR
Only show preview when input is not visible?

Is there a way I can do one of these? Or is there an alternative solution?

**Comment by Mottie** [comment]
Hi @msj121!

To update the original input, use the change callback ([demo](http://jsfiddle.net/egb3a1sk/3645/)):

```js
$(function() {
  $('#keyboard').keyboard({
    change: function(e, keyboard, el) {
      el.value = keyboard.preview.value;
    }
  });
});
```

To only show the preview, you can use a hidden input - see the [hidden input](https://mottie.github.io/Keyboard/#hidden) example in the main demo (click on "Custom: hidden" header, then scroll down to see the code).

**Comment by msj121** [comment]
Thank you! Worked perfectly.
