### ISSUE TITLE
Usability problem regarding autoAccept

### ISSUE THREAD

**Issue by billccn** [Mottie/Keyboard#66]
In the design of my app the keyboard plug-in should act like an real keyboard, so the user should be able to type something into a field, click something else and come back to the field to fill the rest.

To emulate this, I have to enable autoAccept, but that will fire the accept handler even if the user is only half done. This prevents me from doing useful things in the accept handler and must provide a separated button for the user to confirm the input.

This approach confused some users during internal testing as they don't understand why they have pressed "Accept" multiple times and still have to press the submit button.

I think an extra event handler flag is necessary to inducate whether the accept is autoAccept or not.

(I have a local work around for this, so this isn't a critical bug for me. Sorry I wasn't able to post this issue with the previous two.)

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.
