### ISSUE TITLE
Keyboard is not closing after using redraw().

### ISSUE THREAD

**Issue by anshuljain579** [Mottie/Keyboard#668]
Hi Mottie,

Your contribution keyboard api jquery is brilliant. Usage of this is very handy. 
I facing one issue here. 

After using redraw(), if I click outside of the div, keyboard is not closing. I used userClosed: false, still keyboard is always displaying.
This issue will come only usage of redraw() function.

**Comment by Mottie** [comment]
Hi @anshuljain579!

Thanks for letting me know. I'll look into the problem as soon as I can.
