### ISSUE TITLE
How to disable the keyboard 

### ISSUE THREAD

**Issue by gol1980** [Mottie/Keyboard#669]
Hello,
I want to enable/disable the keyboard only when some1 is press on specific button
This is my code, 

```
var virtual_keyboard_on = false;
    jQuery('.acc-virtual-keyboard').on('click', function () {
        if (virtual_keyboard_on) {
           //disable keyboard
            virtual_keyboard_on = false;
        }
        else {

           if (lang == 'en') {
                jQuery('input, textarea').keyboard({});
            }

            virtual_keyboard_on = true;
        }
    });
```

I manage to start the keyboard, but I have no idea how to cancel it.

Thanks in advance

**Comment by Mottie** [comment]
Hi @gol1980!

It sounds like you want to add a [`{toggle}` button](https://github.com/Mottie/Keyboard/wiki/Methods#toggle); if not that button, then maybe you have an external button that can be clicked to trigger the toggle method:

```js
$('#toggle').click(function() {
  $('#keyboard').getkeyboard().toggle();
});
```

**Comment by gol1980** [comment]
The function .getkeyboard().toggle(); is now working
Maybe I'm missing a script file?
This is what I load:
jquery.keyboard.js
keyboard-dark.css

I will explain again what I need
I need in on specific button to enable and disable the keyboard on every input/textarea

The code I worte above is working on enable, the virtual keyboard open on every input/textarea.
But I also need a cancelation option to disable the virtual keyboard when input/textarea

Thanks in advance

**Comment by gol1980** [comment]
I figure out the problem and I'm adding a solution for future visitors,

Assume you want to start the virtual on all input and text area on the page you need to loop keyboard on every element, the Func  keyboard = $('#keyboard').keyboard().getkeyboard(); will actually work on all but you wont be able to cancel them all if you want to, every element needs to have it's own keyboard delegate.

So incase you need to activate and disactivate the keyboard on several elements, this is the solution : 
* I classed all input/textarea elements as 'acc-keyboard' just to make it more clear -->jQuery(input, textarea).addClass('acc-keyboard');

```
 var virtual_keyboard_on = false;
        var acc_vir_keyboard = {};
        jQuery('.acc-virtual-keyboard').on('click', function () {
            if (virtual_keyboard_on) {
                i = 0;
                $('.acc-keyboard').each(function () {
                    acc_vir_keyboard[i].destroy();
                    i++;
                });
            }
            else {
                i = 0;
                $('.acc-keyboard').each(function () {
                    acc_vir_keyboard[i] = jQuery(this).keyboard().getkeyboard();
                    i++;
                });
            }
            virtual_keyboard_on = !virtual_keyboard_on;
        });

```
The same button is activate and disactivate the keyboard on all choosen elements (inputs and textareas in my case)

**Comment by Mottie** [comment]
Nice! Thanks for sharing your solution. I'll go ahead and close this issue.
