### ISSUE TITLE
Autocomplete not working with JQuery/JQuery-UI (Edge)

### ISSUE THREAD

**Issue by mreis1** [Mottie/Keyboard#670]
To reproduce the issue use the demo project available at https://jsfiddle.net/Mottie/pf79f43c/ 
Modify the project to use jquery edge and the corresponding jQuery-ui

![screenshot](https://user-images.githubusercontent.com/1719667/40316896-05ab69c4-5d20-11e8-8516-8ef495d4f475.png)

**Comment by Mottie** [comment]
Hi @mreis1!

It looks like the jQueryUI team renamed the data attribute for custom autocomplete widgets. For UI v1.12.1, only set the data with a "custom" prefix, and capitalize "Cat":

```js
$.widget("custom.catcomplete", $.ui.autocomplete, {
  // ...
})
// ...
.addAutocomplete({
  data: 'customCatcomplete', // add "custom" in front
  events: 'catcomplete',
  position: {
    of: null,
    my: 'right top',
    at: 'left top',
    collision: 'flip'
  }
})
```

I figured this out by checking the input's data structure: `$('input').data()`.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
