### ISSUE TITLE
Logo Proporsal

### ISSUE THREAD

**Issue by tjulises** [Mottie/Keyboard#671]
Hey, I'm graphic designer and my aim is supporting open source projects and make my portfolio better. So, I can contribute on your project with making logo design. I am waiting your feedback! Have a nice day! :)
@Mottie 

Best Regards,
TJ Ulises
Visual Communication Designer

**Comment by tjulises** [comment]
Yes for sure! @Mottie 

I can help up with that,
before proceeding making my first logo proposal, 
I'd like to ask you some questions:

How would you describe this project,
what is it intended to do?

What would you like this logo to transmit?

this details would help _US_ a lot! :+1:

**Comment by Mottie** [comment]
> How would you describe this project

It is a completely customizable virtual keyboard. 

> what is it intended to do?

A [list of features](https://github.com/Mottie/Keyboard#features-demo) can be found in the main read me. There are many, but it might be easier to check out [the demo](http://mottie.github.com/Keyboard/) to get a better idea.

From interactions with users, I have heard of this keyboard being used as an input method for:
* Kiosks.
* TV apps.
* Arduino projects.
* Virtual reality games.
* And various other projects that can input music, math equations, passwords via a scrambled keyset.

> What would you like this logo to transmit?

<kbd>K</kbd><kbd>E</kbd><kbd>Y</kbd><kbd>B</kbd><kbd>O</kbd><kbd>A</kbd><kbd>R</kbd><kbd>D</kbd>... LOL just kidding.

Personally, I'd like a logo that is simple and recognizable. I've thought about something like `|<` which has a sideways "v" and also forms a "k", but you don't need to limit yourself... the logo doesn't have to include letters or even resemble a keyboard. I'll leave that up to you.

**Comment by tjulises** [comment]
Hello @Mottie ,

This is my first proposal, I'd like to know what you like and didn't like about it, I can change anything or everything as you wish! I hope you like it.
![1](https://user-images.githubusercontent.com/39039587/40850889-c9d2086e-6593-11e8-8d71-2776b509e976.png)

**Comment by tjulises** [comment]
![31234](https://user-images.githubusercontent.com/39039587/40882762-50a1d000-66ba-11e8-90b2-953d15cc7a7f.png)
hi @Mottie ,
this is my second proposal.

**Comment by tjulises** [comment]
It can be any colour you want it to be, I can add or delete any element too,

I'll gladly adjust it as many times as necessary! Let me know what you think about this, @Mottie .

**Comment by Mottie** [comment]
I like the purple; but the "K" key colors are too dark... and my OCD doesn't like that the shadow of the keys aren't right... I photoshopped this change, but even now, the "K" keys color is brighter but still seems a bit off.

![logo](https://user-images.githubusercontent.com/136959/40924926-0d2371f6-67de-11e8-8e07-cf7e255232ef.png)

Sorry for being a pain.

**Comment by tjulises** [comment]
hi @Mottie  ,
here i have updated the logo, I hope you like it.
![logotipo keyboard2 2018](https://user-images.githubusercontent.com/39039587/40949291-57c2f17a-683b-11e8-80af-952ddb6947e0.png)

**Comment by tjulises** [comment]
![logotipo keyboard3 2018](https://user-images.githubusercontent.com/39039587/40950557-497269a6-6841-11e8-954e-c443ad42ad68.png)

**Comment by tjulises** [comment]
@Mottie

**Comment by Mottie** [comment]
Hey sorry... long day!

I wasn't really happy with the "k" color selection, so I tried both the [complimentary color](https://www.sessions.edu/color-calculator-results/?colors=6e4d8b,523a66,ffffff,8b7d4d,665c3a,ffffff)

![complimentary](https://user-images.githubusercontent.com/136959/41017603-38e8b6f0-691b-11e8-8789-22207f3a1e2e.png)

and the [analogous color](https://www.sessions.edu/color-calculator-results/?colors=6e4d8b,523a66,ffffff,5f4378,b38ca9) and I think I like the analogous one better...

![analogous](https://user-images.githubusercontent.com/136959/41017607-3c7914ae-691b-11e8-92f2-38eb1089203e.png)

I also like the shadow... would it be too much trouble to get the key to cast a "proper" shadow?

![](https://user-images.githubusercontent.com/136959/41017644-6e191572-691b-11e8-9984-47bceb8de388.png)

**Comment by tjulises** [comment]
I agree, I'll update it and upload when ready @Mottie .

**Comment by tjulises** [comment]
something like this @Mottie ?
![logotipo keyboard4 2018](https://user-images.githubusercontent.com/39039587/41052418-b5bd8a14-6986-11e8-8f44-fcd9cc7ba67e.png)

**Comment by Mottie** [comment]
Yes! I like the top one! 😸

**Comment by tjulises** [comment]
Ok @Mottie I've sended a pull request #673 .

Now I'll close this issue.
