### ISSUE TITLE
No caret $el.length

### ISSUE THREAD

**Issue by msj121** [Mottie/Keyboard#672]
In the function (on line 3091):
```
$keyboard.caret = function($el, param1, param2) {
   if (!$el || !$el.length || $el.is(':hidden') || $el.css('visibility') === 'hidden') {
```

I added !$el in the above if statement to make sure there is an object, got an error before this change:

> window.onerror: TypeError: null is not an object (evaluating '$el.length')

**Comment by Mottie** [comment]
Hi @msj121!

This was added back in Feb in PR #651. Please update your version.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
