### ISSUE TITLE
Doesn't work at all.

### ISSUE THREAD

**Issue by muhammedbello** [Mottie/Keyboard#675]
Hello.

I don't know what I'm doing wrong but I've downloaded this source files at least 10 times. And I simply can't get the keyboard to pop up except on your included index.html file with all the samples.

I have no idea why it simply doesn't work.

**Comment by Mottie** [comment]
Hi @muhammedbello!

Please share the code you're using. I can't help without seeing where the problem lies.

I set up [this demo](https://jsbin.com/meqemot/edit?html,output) that you can modify to show the code being used... make sure to use file -> save snapshot, then copy the url of the demo and share it here.

**Comment by muhammedbello** [comment]
Hi,

Thanks a lot for the demo set up. It worked and I was able to make modifications. 

Actually trying to create a phonegap application based on a RTL language. Two issues; the caret doesn't show up in the text area (preview is set to off) and pop-up alt keys don't seem to work.

Still hacking away though. 

Remarkable bit of coding - thumbs up to you.

**Comment by Mottie** [comment]
Thanks!

The caret won't show up if the textarea/input is set to read only. You might need the [caret extension](https://github.com/Mottie/Keyboard/wiki/Extension-Caret) in that case.

As for the altkeys popup, please make sure to include the extension. The setup is shown on the [wiki page](https://github.com/Mottie/Keyboard/wiki/Extension-AltKeysPopup), and [here's a demo](https://jsfiddle.net/Mottie/k7741r7n/) of it working. If you're still having trouble, then please modify that demo to show the issue. I *might* be able to help, although I haven't had to set up anything to work in phonegap before.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
