### ISSUE TITLE
Getting the keyboard instance from an input

### ISSUE THREAD

**Issue by Cereal-Killa** [Mottie/Keyboard#676]
It's not really a glitch but this was the only place where I could ask, I would like to hide any active keyboard on the screen without knowing which input is currently active but I can't seem to cast the inputs to a keyboard instance in order to call the close method, can you help me with that?

`$('.ui-keyboard-input').each(function(a, b) {
            $(b).keyboard().close();////?????
        });`

**Comment by Cereal-Killa** [comment]
My kb object is returning undefined even though the keyboard is working and active, what could I be doing wrong?

I'm still on version 1.18.1...
Thank you

**Comment by Cereal-Killa** [comment]
![2018-06-13_17-39-01](https://user-images.githubusercontent.com/25939765/41376828-bfced710-6f30-11e8-9fa6-1a2616ce784d.png)

**Comment by Mottie** [comment]
Ah, I didn't add the `data` to the open keyboard until v1.25.15. So in your case, you should then target the input and get it's data as you were doing.

**Comment by Cereal-Killa** [comment]
Worked like a charm, I appreciate it your help.

Sharing the solution:

`$('.ui-keyboard-input').each(function(a, b) 
    {
        var kb = $(this).data("keyboard");

        if (!$.isEmptyObject(kb)) 
        {       
           kb.close(kb.options.autoAccept ? "true" : false);
        }
    });`
