### ISSUE TITLE
issues when simulating click

### ISSUE THREAD

**Issue by arthurmougin** [Mottie/Keyboard#679]
hi, I'm using the keyboard through webvr as a "virtual" virtual keyboard.. the problem is when I receive a click in VR, I have to reEmit the click to the "real" keyboard input : 
with vanilla JS, .click() don't work.
and jquery don't handle  $('[data-value="'+myvalue+'"]') when myvalue is '...

**Comment by Mottie** [comment]
Hi @WellanDraco!

Are you trying to get jQuery handlers to detect the click? If so, try using [`triggerHandler`](http://api.jquery.com/triggerHandler/). Also, jQuery *should* handle that selector if you properly escape - I just discovered that jQuery v3.0+ added an [`$.escapeSelector()` function](http://api.jquery.com/jQuery.escapeSelector/) that will take care of that for you.

**Comment by WellanDraco** [comment]
Thanks for the escape selector but yet the triggerHandler fail... 
there is the code, the init function is called for every virtual key
(not a true jquery user in fact)
```
AFRAME.registerComponent("keyboardinput", {
  schema: {
    keydata: {type: 'string', default: 'a'}
  },
  init: function() {
    var el = this.el;
    var tempo = false;
    var keydata = this.data.keydata;
    
    console.log(keydata);
    
    var realKey = $("[data-value="+$.escapeSelector( keydata )+"]");//this work well THX !
    //document.querySelector("[data-value='"+keydata+"']");
    //console.log(realKey);
    
    el.addEventListener("click", function(evt) { // click on the vr input
      if (tempo == false) {
        if (clickdetail == false && evt.detail != 0) { // little glitches
          return;
        }

        realKey.triggerHandler("click"); // no input animation nor text added in the preview :/
        console.log(realKey); // working

        tempo = true;
        setTimeout(function() { // prevent flood
          tempo = false;
        }, 200);
      }
    });
  }
});
```

**Comment by Mottie** [comment]
Sorry I haven't followed up!

I'm still not entirely sure of the goal here... so the click you're trying to trigger is for this library or another library?

For this library, you'll need to use `mousedown` instead of `click` (`triggerHandler` will work).

For a different non-jQuery library, try using [`dispatchEvent`](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events) with a click event.

**Comment by arthurmougin** [comment]
I close this issue because this library is seriously great but not for my use case, I decided to make my own keyboard directly in VR. 
This issue might be caused by my lack of competence in jquery and the fact that the keyboard is not used as it is meant to be in my use case.
