### ISSUE TITLE
Sending key to input

### ISSUE THREAD

**Issue by Davdew** [Mottie/Keyboard#680]
Hi, I like very much your keyboard, congrats for the great job. 
I run into a little problem when using dataTables jquery plugin. Because the filter input box reacts on keypress or keyup keyboard when I use your keyboard, the filter does not fire. 

Is there a way to, when a click on the vitual key fire then keydown of the input box?

**Comment by Mottie** [comment]
Hi @Davdew!

You can use the [`keyboardChange` event](https://github.com/Mottie/Keyboard/wiki/Methods#events) to perform any additional interactions, like fire a keydown event.

If you have any problems getting it to work, then please provide a demo with the code being used and I can attempt to find a solution. You can modify [this demo](http://jsfiddle.net/Mottie/egb3a1sk/) or create your own.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
