### ISSUE TITLE
Enter key not updating textarea

### ISSUE THREAD

**Issue by kentishman46** [Mottie/Keyboard#686]
I was trying to insert a newline in a textarea using the virtual keyboard and nothing happened, I eventually discovered that this was due to having restrictInput=true.

It seems that that keys generated by {enter} are not acceptable.

Not a big issue, just unexpected.

**Comment by Mottie** [comment]
Hi @kentishman46!

I'm not sure why you're encountering this issue. In the source code, the enter key is allowed during [`restrictInput`](https://github.com/Mottie/Keyboard/wiki/Usability#restrictinput) when [`enterNavigation`](https://github.com/Mottie/Keyboard/wiki/Usability#enternavigation) is `true`, or a textarea is being used ([ref](https://github.com/Mottie/Keyboard/blob/v1.28.4/js/jquery.keyboard.js#L571-L573)).

If you ever need to add an additional key to the list of allowable keys, add it to the [`restrictInclude` option](https://github.com/Mottie/Keyboard/wiki/Usability#restrictinclude).

**Comment by kentishman46** [comment]
This may help
If I use the real keyboard Enter key I see a newline (possibly 2) being added (caret moves down and to the left) briefly then it looks like the newline gets removed.

**Comment by Mottie** [comment]
Would you please modify [this demo](http://jsfiddle.net/Mottie/egb3a1sk/) to duplicate what's being described?

**Comment by Mottie** [comment]
Actually, nevermind. I was able to reproduce this issue. I'll have it fixed in the master shortly.
