### ISSUE TITLE
There is a mistakenly touch on the touch screen

### ISSUE THREAD

**Issue by liijuu** [Mottie/Keyboard#688]
When the keyboard is popped up, if the keyboard is underneath the finger, a click operation will be triggered.

**Comment by Mottie** [comment]
Hi @liijuu!

I'm not exactly sure what you're describing here. A "click" event is triggered? On the button? What happens? What did you expect to happen? What needs to be fixed?

Internally, the code is set up to ignore "click" events.

Things only happen on "mousedown" and "touchstart" by default (see the [`keyBinding` option](https://github.com/Mottie/Keyboard/wiki/Usability#keybinding)). The opposite events of "mouseup", "mouseleave", "touchend", "touchmove" (if moved outside of the current key), and "touchcancel" does stuff like re-focus the input, position the caret and check the input validation, if enabled.

If possible, please [modify this demo](http://jsfiddle.net/Mottie/egb3a1sk/) to show the problem.

**Comment by Mottie** [comment]
Also, are you using any extensions?
