### ISSUE TITLE
Problem to close the keyboard - conflict with fancybox

### ISSUE THREAD

**Issue by CptZeroG** [Mottie/Keyboard#689]
If you simply try to include Fancybox script into the page with virtual keyboard the function to close the keyboard returns this error and the keyboard still open.:
Uncaught TypeError: Cannot read property 'hash' of undefined

There is some workaround to avoid this issue?

Regards ;)

**Comment by Mottie** [comment]
Hi @CptZeroG!

It looks like this is actually an issue with FancyBox binding to Bootstrap's "beforeClose" event without being initialized.

You can solve this by modifying the keyboard's "beforeClose" event ([demo](http://jsfiddle.net/egb3a1sk/5752/)):

```js
$(function() {
  $.keyboard.events.kbBeforeClose = "kbBeforeClose";
  $('#keyboard').keyboard();
});
```

**Comment by CptZeroG** [comment]
Hi Mottie,
Thanks for the quick reply :)
Great! By changing the name of the event it's works like a charm
Thanks again Mottie and compliments for that work, it's very useful.

Have a great day
