### ISSUE TITLE
Need to have keyboard enabled on all input fields dynamically

### ISSUE THREAD

**Issue by magicallyindia** [Mottie/Keyboard#690]
Hello 

We are injecting javascript dynamically into chromium cefsharp browser ( Winforms chromium browser control ) . Is it possible to enable virtual keyboard for all input fields of random websites  being loaded into the cefsharp chromium browser. Is there an example or a way to do it . Exploring. 

Bhushan

**Comment by Mottie** [comment]
Hi @epayindia!

The keyboard can be initialized on any number of inputs/textareas; you should be able to dynamically add and reveal a keyboard when any input is focused. I put together [this demo](http://jsfiddle.net/Mottie/cyk8x4et/) which allows you to dynamically add/remove inputs; and they all work with the keyboard.

```js
$(function() {
  var handled = false;

  function initKb(e) {
    if (
      e.target.nodeName !== "INPUT" ||
      handled ||
      e.target.classList.contains('ui-keyboard-input') ||
      e.target.classList.contains('ui-keyboard-preview')
    ) {
      return;
    }
    handled = true;
    var $el = $(e.target);
    if ($el.data().keyboard) {
      $el.getkeyboard().reveal();
    } else {
      $el
        .on('hidden', function() {
          if ($el.data().keyboard) {
            $el.getkeyboard().destroy();
          }
        })
        .keyboard({
          usePreview: false
        });
    }

    setTimeout(function() {
      handled = false;
    }, 200);
  }
  $('body').on('focus', 'input', initKb);

	$('.add').on('click', function() {
  	$('#wrap').append('<input type="text">');
  });
	$('.delete').on('click', function() {
  	$('#wrap input').last().remove();
  });
});
```

**Comment by epayindia** [comment]
Great. Thanks for a quick revert saved my day. 







Thanks and Regards Bhushan Ivatury 


Director Eng & Ops


EPay Solutions India Pvt Ltd


Hyderabad - 500082Get Outlook for Android







On Fri, Sep 7, 2018 at 4:13 AM +0530, "Rob Garrison" <notifications@github.com> wrote:












Hi @epayindia!


The keyboard can be initialized on any number of inputs/textareas; you should be able to dynamically add and reveal a keyboard when any input is focused. I put together this demo which allows you to dynamically add/remove inputs; and they all work with the keyboard.
$(function() {
  var handled = false;

  function initKb(e) {
    if (
      e.target.nodeName !== "INPUT" ||
      handled ||
      e.target.classList.contains('ui-keyboard-input') ||
      e.target.classList.contains('ui-keyboard-preview')
    ) {
      return;
    }
    handled = true;
    var $el = $(e.target);
    if ($el.data().keyboard) {
      $el.getkeyboard().reveal();
    } else {
      $el
        .on('hidden', function() {
          if ($el.data().keyboard) {
            $el.getkeyboard().destroy();
          }
        })
        .keyboard({
          usePreview: false
        });
    }

    setTimeout(function() {
      handled = false;
    }, 200);
  }
  $('body').on('focus', 'input', initKb);

	$('.add').on('click', function() {
  	$('#wrap').append('<input type="text">');
  });
	$('.delete').on('click', function() {
  	$('#wrap input').last().remove();
  });
});

**Comment by epayindia** [comment]
Any idea the keyboard is not coming up on textarea

**Comment by Mottie** [comment]
The code I shared didn't account for textareas... try this ([demo](http://jsfiddle.net/Mottie/cyk8x4et/4/)):

```js
$(function() {
  var handled = false;

  function initKb(e) {
    if (
      e.target.nodeName !== "INPUT" &&
      e.target.nodeName !== "TEXTAREA" ||
      handled ||
      e.target.classList.contains("ui-keyboard-input") ||
      e.target.classList.contains("ui-keyboard-preview")
    ) {
      return;
    }
    handled = true;
    var $el = $(e.target);
    if ($el.data().keyboard) {
      $el.getkeyboard().reveal();
    } else {
      $el
        .on("hidden", function() {
          if ($el.data().keyboard) {
            $el.getkeyboard().destroy();
          }
        })
        .keyboard({
          usePreview: false
        });
    }

    setTimeout(function() {
      handled = false;
    }, 200);
  }
  $("body").on("focus", "input, textarea", initKb);

  $(".add").on("click", function() {
    $("#wrap").append(Math.random() < .5 ? '<input type="text">' : '<textarea/>');
  });
  $(".delete").on("click", function() {
    $("#wrap input, textarea").last().remove();
  });
});
```

**Comment by epayindia** [comment]
Thanks , one more question , the keyboard is not floating / attaching but stays in the bottom of the screen. Im trying to inject dynamically into a html using chromium control. can you also help on the same.

**Comment by epayindia** [comment]
![image](https://user-images.githubusercontent.com/12893334/45201353-9df74f00-b292-11e8-9e37-14a6f11df2e5.png)

**Comment by epayindia** [comment]
![image](https://user-images.githubusercontent.com/12893334/45201366-aea7c500-b292-11e8-9b5d-14eea47b0337.png)

**Comment by Mottie** [comment]
The keyboard is positioned using jQuery UI's position utility, so you'll need to either inject that or use either the provided [light or dark theme](https://github.com/Mottie/Keyboard/wiki#themes) which positions the keyboard at the bottom without jQuery UI.

**Comment by Mottie** [comment]
If you have a specific element you want to inject the keyboard into, use the [`appendTo` option](https://github.com/Mottie/Keyboard/wiki/Usability#appendto)... please take a look at the other options as well.

**Comment by epayindia** [comment]
Hi 
One quick note. The keyboard is coming now. But when we inject and for first time , the keyboard is initializing but not displaying. 

This is in the embedded browser dynamic injection. 

Any idea ! 

Bhushan

**Comment by Mottie** [comment]
No idea. Please share the code you're using.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Comment by xinthose** [comment]
@Mottie The inputs in your jsfiddle no longer display a keyboard when they are focused.  Why is this?

**Comment by Mottie** [comment]
It's because jQuery UI v1.12.1 is not compatible with jQuery edge.

JSFiddle is weird in that it doesn't include a jQuery UI version with every jQuery version. So in [this demo](http://jsfiddle.net/Mottie/cyk8x4et/12/) I changed it to jQuery v1.9.1 & jQuery UI v1.9.2.

This keyboard library *is* compatible with jQuery edge so if you use the [light](https://jsfiddle.net/Mottie/jsh0377k/) or [dark](https://jsfiddle.net/Mottie/6dmqhLvh/) theme demos, you'll see the keyboard works the latest jQuery without any issues.
