### ISSUE TITLE
Pressing Tab button inserts indentation in textarea. How to prevent it?

### ISSUE THREAD

**Issue by dineshrsharma** [Mottie/Keyboard#692]
Hi,

Pressing Tab button inserts indentation for textarea field. How to prevent it so that pressing Tab navigates to next input field. Below is the config applied:

layout: 'custom',
autoAcceptOnEsc: true,
autoAccept: true,
usePreview: false,
useWheel: false,
tabNavigation: true,

Thanks.
Dinesh

**Comment by Mottie** [comment]
Hi @dineshrsharma!

Using the tab key inside a textarea is difficult. The `tabNavigation` option was really only meant for inputs since the textarea allows tab insertion.

I could modify the action so that <kbd>Shift</kbd>+<kbd>Tab</kbd> would jump to the next input/textarea, but then there would be nothing to make it move backwards. All other modifier keys + <kbd>Tab</kbd> cause browser tab navigation.

There is good news though - all key actions are modifiable. Change the tab action as follows ([demo](https://jsfiddle.net/Mottie/egb3a1sk/6102/)):

```js
$.keyboard.keyaction.tab = function(kb) {
  if (kb.options.tabNavigation) {
    return kb.switchInput(!kb.shiftActive, true);
  }
  return false;
};
```

This will make the `tabNavigation` option move to the next input/textarea when <kbd>Tab</kbd> is pressed, and move to the previous input/textarea when <kbd>Shift</kbd> + <kbd>Tab</kbd> is pressed.

That behavior may not always be preferred, so I think in the next major version, I'll rename this option to `tabBehavior` and give it 3 options:

* "disable" - do nothing
* "insertTab" - textarea only
* "navigate" - textarea & input

**Comment by dineshrsharma** [comment]
Hi @Mottie ,

Thanks for quick response. Really appreciate it... 
Sorry for replying this late due to no access to internet.

The solution seems to be pretty simple, hope this will work with our complex application. Will update you soon.

Thanks once again @Mottie .

**Comment by dineshrsharma** [comment]
Hi @Mottie,

It works fine but in console there is an error

Uncaught TypeError: Cannot set property 'tab' of null
    at HTMLTextAreaElement.<anonymous> (jquery.keyboard.min.js.xhtml?ln=js:2)
    at HTMLTextAreaElement.dispatch (jquery.js.xhtml?ln=primefaces&v=6.0&v=6.0:14)
    at HTMLTextAreaElement.cd.handle (jquery.js.xhtml?ln=primefaces&v=6.0&v=6.0:14)

Any clue on this?

**Comment by dineshrsharma** [comment]
Thanks @Mottie for the reply...

The keyboard that I have implemented has many metakeys, say for example A to Z which contains all special characters (umlauts). Now, what happens is suppose if I am on meta 'o' & I again click on 'o' then it takes me to default meta i.e., 'a'.
Is there any way to disable the current metakey or prevent redirection to default meta.

**Comment by Mottie** [comment]
That sounds like the typing extension automatically switching keysets to make the typed in character visible.

**Comment by dineshrsharma** [comment]
Below is the screenshot for better understanding.

![capture](https://user-images.githubusercontent.com/17684396/45623908-66648000-baa6-11e8-8834-5235f9eaf15c.JPG)

**Comment by Mottie** [comment]
Oh, you can think of meta keys behaving like a capsLock... press it once to enable, press it a second time to turn it off. It wasn't really set up to have the key lock in the keyset.

And of course you can modify this behavior. Include the following code ([demo](https://jsfiddle.net/Mottie/egb3a1sk/6122/)):

```js
$.keyboard.keyaction.meta = function(kb, el) {
  var $el = $(el);
  if (kb.getKeySet() !== $el.attr('data-name')) {
  	kb.metaActive = true;
    kb.showSet($el.attr('data-name'));
  }
};
```

**Comment by dineshrsharma** [comment]
**Super Super Super**.... You beauty @Mottie ... Thanks a ton :)

Now only stuck with console error "Cannot set property 'tab' of null". Tried inside document.ready, before & after initialization of keyboard but no luck.

**Comment by Mottie** [comment]
Please share an example of how you're loading the keyboard & initializing it.

**Comment by dineshrsharma** [comment]
Hi @Mottie,

Shouldn't "keysetChange" event be triggered when keys are changed by clicking any of the meta key?

**Comment by Mottie** [comment]
If you only want to fire off the event with the meta key then use `keysetChange` event; interacting with the meta key will fire off both the `keysetChange` and `keyboardChange` events - [demo](https://jsfiddle.net/Mottie/egb3a1sk/6323/).

**Comment by dineshrsharma** [comment]
Thanks for reply @Mottie,

keysetChange works well for met key click event but I want to execute script after keyboard is loaded on meta key is click.

**Comment by Mottie** [comment]
Maybe you need the [`visible`](https://github.com/Mottie/Keyboard/wiki/Methods#events) event, or callback then?

**Comment by dineshrsharma** [comment]
I checked visible event too & it is trigger only for the 1st time.

**Comment by Mottie** [comment]
I'm not sure what you need then... can you use the `keysetChange` and check the [`keyboard.last.keyset[2]` value](https://github.com/Mottie/Keyboard/wiki/Methods#values) for the meta key that was pressed.

**Comment by Mottie** [comment]
`keysetChange` is triggered after the key set switches. Maybe you just need to wrap your function in a `setTimeout` to allow the DOM to render.
