### ISSUE TITLE
Keyboard + Android Device + Scanner issue

### ISSUE THREAD

**Issue by mezmaghost** [Mottie/Keyboard#697]
Hi,

I'm using an wrist device using android with finger strapped scanner. I've added your virtual keyboard script to replace the android keyboard - as it's way too small for what we want. I've had to lock the inputs on the web page to stop the android keyboard popping up, and this seems to work perfectly.

The issue comes when I get to an input that requires the use of the scanner. It can no longer scan into it.
Ideally, we want it to scan in, but if this fails, have use of the virtual keyboard (keeping the android keyboard from popping in the way).

Does that make sense?

Any help / advice would be great.

**Comment by mezmaghost** [comment]
In addition and related:  Your input on the virtual keyboard, also does not except scanned barcodes on the device. Does something need to be added to enable this?

**Comment by mezmaghost** [comment]
Hi @Mottie!

Hmm, yes it's an odd one.
I need the cloned input unfortunately.

Just testing now on your website: https://mottie.github.io/Keyboard/
using a USB scanner. They all accept the barcode and it appears in the input and cloned inputs.

On my web page however it does not (and the regular keyboard does not)...  I'm guessing it is because the field is locked and is making the cloned input locked too... 

2 questions then:
Is there a way to unlock the cloned input only?
OR
Is there a way to trick it into thinking the scan is coming from the virtual keyboard?

It's a head-scratcher...

**Comment by mezmaghost** [comment]
The value once scanned... The barcodes we're scanning will be 13 digit barcodes, or an order number consisting of 2 letters a hyphen and numbers - If that's what you meant.

**Comment by mezmaghost** [comment]
Doesn't seem to work.
If I use the virtual keyboard there is a preview clone that has the input 'disabled' but I don't this that could be stopping it... 

![image](https://user-images.githubusercontent.com/25169856/46154906-07ed8d80-c26e-11e8-98a1-6d1388167f84.png)

**Comment by Mottie** [comment]
That second clone is used to calculate the caret position. You can ignore it.

**Comment by mezmaghost** [comment]
ah ok. 

Well, the USB scanner doesn't work with the change.

Device scanner also doesn't work, but I've noticed if I tap the preview input and get it focused it allows me to scan (but i get the issue of the regular android keypad appearing).

I'll have to take another look at the tomorrow.

**Comment by mezmaghost** [comment]
I think I've got it working now.

I added openOn : null, but had an initial .focus() for the form field. And turned the lockInput off... not sure if that makes sense. But thanks for the help, it got me on track.
