### ISSUE TITLE
Jquery keyboard events does not work, when i use mottie keyboard. 

### ISSUE THREAD

**Issue by arczas89** [Mottie/Keyboard#698]
Hi, look at this:

$("#someInput").keyboard({ usePreview: false });
$("#someInput").on("keypress", function(event) {
alert("!!!")  //not fired 

 });

Why when i clicking on mottie keyboard keys a keypress (and other key events) didnt fire? Ofcourse when i use phisical keyboard events works fine. I need this key events because i need to prevent typing double dots, replace comas to dots and other stuff like this.

**Comment by Mottie** [comment]
Hi @arczas89!

Use the [`keyboardChange` event](https://github.com/Mottie/Keyboard/wiki/Methods#events) instead of keypress ([demo](http://jsfiddle.net/Mottie/egb3a1sk/6361/)):

```js
$(function() {

  $("#someInput").keyboard({
    usePreview: false
  });
  $("#someInput").on("keyboardChange", function(event, keyboard) {
    alert(keyboard.last.key + "!!!");
  });

});
```
