### ISSUE TITLE
Close Keyboard

### ISSUE THREAD

**Issue by cloudstudio** [Mottie/Keyboard#702]
Hello @Mottie !!! i love this plugin, congratulations ! 

I need do something "easy?" close keyboard :P 

I have one idle detect, so if you are AFK for 30 sec, y launch one modal, i close all other modals / keyboards.

I find this one :   $('#keyboard').getkeyboard().reveal(); is perfect for show.

Something like $('#keyboard').getkeyboard().hide(); 😃 

Thanks for you time !

**Comment by Mottie** [comment]
Hi @cloudstudio!

Use the [`close`](https://github.com/Mottie/Keyboard/wiki/Methods#close) or [`accept` method](https://github.com/Mottie/Keyboard/wiki/Methods#accept).

```js
$('#keyboard').getkeyboard().accept();
```

**Comment by cloudstudio** [comment]
So easy ! thanks mate !
