### ISSUE TITLE
Input mask

### ISSUE THREAD

**Issue by cloudstudio** [Mottie/Keyboard#704]
Hello ! thanks in advance.

I see one issue in 2013 :P but i don't know if we can use mask at the moment.

We have options for this ? 

For example date : dd/mm/yyyy

Thanks!!!

**Comment by Mottie** [comment]
Hi @cloudstudio!

Sadly, no there isn't any mask library, that I know of, that works with this plugin. The difficulty is in controlling the cursor position while the user types. The keyboard and the mask plugin need to adjust it, so they both end up fighting for control. It makes for a bad user experience.

I think the only solution would be for me, or someone, to write an extension for the keyboard that applies a mask. The extension can either make the keyboard relinquish control of the cursor, or rewrite an existing mask plugin to use the keyboard cursor functions.

**Comment by Mottie** [comment]
I'm going to close this issue and refer you to #201 for updates. Thanks!
