### ISSUE TITLE
How to map Accept to touchend?

### ISSUE THREAD

**Issue by Michael-F-Ellis** [Mottie/Keyboard#706]
My application uses the keyboard with JQMobile  in chromium-browser running in kiosk mode on a Raspberry Pi with the RPi touchscreen.  The Pi is running Raspbian Jessie.

In some of the pages, the Accept button ends up positioned above other active elements in the main app.  Touching the accept button closes the keyboard and triggers the appropriate action but the touch falls through to whatever item was under the button causing it to fire inappropriately.

I tried setting `closeByClickEvent: true`. It had no effect.

What's the right way to handle this?

Thanks!

**Comment by Mottie** [comment]
Hi @Michael-F-Ellis!

The only way I can think of to handle this is to have whatever listener on the page check the `touchend` event. All of the keyboard bindings include a [namespace](http://api.jquery.com/event.namespace/) and the [`target`](http://api.jquery.com/event.target/) should point to an element that is no longer attached to the DOM.

I haven't messed around with this in a while... does stopping the propagation or preventing the default of the `touchstart` prevent the `touchend` from firing? If that is true, then you may be able to use `e.preventDefault()` within the keyaction?

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
