### ISSUE TITLE
KeyboardEvent.key

### ISSUE THREAD

**Issue by danielbsig** [Mottie/Keyboard#707]
Hi,

we've been using this excellent extension with good results. We did run into the same problem as reported here:

https://github.com/Mottie/Keyboard/issues/654

i.e. where multiple keys were inserted into the textbox (both the accented character and the character beneath it from the original keyboard), but by upgrading to the latest version (1.28), this problem is eliminated.

However, as I understand it, the latest version uses the KeyboardEvent.key property, which apparently isn't supported in older browsers, and unfortunately we are required to support Chrome ~40 (on a special kiosk hardware, which we are unfortunately not able to update).

Would it be possible to use some polyfill? What are our options?

Best regards,
Daníel

**Comment by Mottie** [comment]
Hi @danielbsig!

A polyfill like [shim-keyboard-event-key](https://github.com/shvaikalesh/shim-keyboard-event-key) *should* work (I haven't tested it); but if that fails, I'll see if I can modify the altkeys extension to fallback to the older method.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
