### ISSUE TITLE
Unable to initialize keyboard in Typescript class

### ISSUE THREAD

**Issue by CPMikeAmato** [Mottie/Keyboard#709]
Hi all-

Having some issues initializing the keyboard while working in an Angular2 typescript class. Here's a screenshot of the error I'm seeing:
![image](https://user-images.githubusercontent.com/41522106/48437051-5c7d9700-e74e-11e8-9424-9b32255f7610.png)

In the case this didn't load properly, here's the text: 
"[ts]
Argument of type '{ userClosed: any; autoAccept: true; }' is not assignable to parameter of type 'KeyboardOptions'.
  Property 'type' is missing in type '{ userClosed: any; autoAccept: true; }'.
(property) KeyboardOptions.autoAccept?: boolean"

----

I have the following imports in my file:
import { Component, OnInit } from '@angular/core';
import { Tile } from '../tile';
import { TileService } from '../tile.service';

import { KeyboardOptions } from 'virtual-keyboard';
import * as $ from 'jquery';

-- 

Thanks for any help on this!

**Comment by CPMikeAmato** [comment]
Finally got rid of the above error for some reason by declaring the keyboardOptions separately like this:

![image](https://user-images.githubusercontent.com/41522106/48439478-67d3c100-e754-11e8-8134-166511135747.png)

But now, once I tap the button which is supposed to spawn the keyboard, I'm getting the following error in the Chrome debugger:

![image](https://user-images.githubusercontent.com/41522106/48439510-79b56400-e754-11e8-85c1-b10d03c8c606.png)

**Comment by Mottie** [comment]
Hi @CPMikeAmato!

Have you tried using the `keyboard` variable that's already defined?
```js
var keyboard = $("#keyboard").data("keyboard");

$("button.open").on("click", function () {
  keyboard.reveal(); 
});
```

**Comment by CPMikeAmato** [comment]
> Hi @CPMikeAmato!
> 
> Have you tried using the `keyboard` variable that's already defined?
> 
> ```js
> var keyboard = $("#keyboard").data("keyboard");
> 
> $("button.open").on("click", function() {
>   keyboard.reveal();
> });
> ```

Thanks for the reply @Mottie - I tested this and got the following:

![image](https://user-images.githubusercontent.com/41522106/48570854-54029900-e8d3-11e8-9d72-ec99ad1e8acc.png)

Will keep messing around a bit and see if I can figure out a fix.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Comment by CPMikeAmato** [comment]
Unfortunately never found a solution to get this into my AngularJS project properly. If others are experiencing the same problems, this project worked for me:

https://github.com/ngx-material-keyboard/core

Thanks for your responsiveness Mottie!
