### ISSUE TITLE
Hello all, i need some help setting up the keypobard...

### ISSUE THREAD

**Issue by CodingProjects2017** [Mottie/Keyboard#711]
Hello all, thanks in advance. I some some layout help, i need a limited keyboard only showing the following keys:

A-Z (all caps, no need for lowercase)
0-9 (all the digits)
space
backspace

We can probably even do with out the digits 0-9

but i do need to test how it looks and so on. I need an easy way to set how the keys appear, that is, in rows and columns, and also the font and probably BOLD text, and how big each key is. they can all be the same size.

But, the touch screen we are using is a 24 inch so we want the buttons to be pretty big for ease of touch.

I really won't know except by trial and error.

Any ideas to help me? Thanks again!!!

**Comment by Mottie** [comment]
Hi @CodingProjects2017!

The [main demo](https://mottie.github.io/Keyboard/) shows the code at the bottom of the page after you click on the title of the keyboard you want to examine. That's probably a bit to subtle.

The best way, in my opinion, to mess around with the keyboard is to play with the options in an online editor. I have two separate playgrounds set up:

* [JSFiddle](http://jsfiddle.net/Mottie/egb3a1sk/) - Includes all the options with some comments. You'll need to click on the "Resources" link in the left column to see which files have been included.
* [JS Bin](https://jsbin.com/meqemot/edit?html,output) - Super minimal setup; but it shows all the HTML needed to get it up and working.

If you need more help, please feel free to ask. Also, I've added some documentation in the [wiki pages](https://github.com/Mottie/Keyboard/wiki) for reference.
