### ISSUE TITLE
How to trigger keyup

### ISSUE THREAD

**Issue by Chokomoko** [Mottie/Keyboard#713]
Hi @Mottie , I am trying to make pinyan jquery plugin work with virtual keyboard.
The problem is that pinyan plugin processes only pysical keyup\keydown events. Is there any way to trigger proper keyup when we type with the help of virtual keyboard?

I've found similar isssue, but there is no proper answer
https://github.com/Mottie/Keyboard/issues/322

**Comment by Mottie** [comment]
Hi @Chokomoko!

You should be able to use the [`change` callback](https://github.com/Mottie/Keyboard/wiki/Methods#change) to trigger a keyup event. I set up [this demo](https://jsfiddle.net/Mottie/egb3a1sk/6755/) showing that the [`beforeInsert` callback](https://github.com/Mottie/Keyboard/wiki/Methods#beforeinsert) (simulating a keydown) would catch repeated keys (holding down a key) whereas the `change` callback would only be called once.

```js
$(function() {

	const $report = $('#report');
	function report(msg) {
  	$report.append(`<li>${msg}</li>`);
    $report.find('li:first-child').remove();
  }

  $('#keyboard').keyboard({
      beforeInsert: function(e, keyboard, el, textToAdd) {
      	report(`beforeInsert (keydown): ${textToAdd}`);
      	return textToAdd;
      },
      change: function(e, keyboard, el) {
      	report(`change (keyup): ${keyboard.last.key}`);
      }
    });
});

```

**Comment by Chokomoko** [comment]
@Mottie , Thank you, that helps a lot!
