### ISSUE TITLE
How to check if altKeyPopup added

### ISSUE THREAD

**Issue by Chokomoko** [Mottie/Keyboard#714]
Dear @Mottie.
Is there any way to check if altpopup is already added for given input with keyboard?
Because when I try to call addAltKeyPopup twice for the same element it throws me error, so id like to avoid it

**Comment by Mottie** [comment]
Hi @Chokomoko!

You can check to see if the `altkeypopup_namespace` is defined:

```js
var altKeyPopupActive = $('#keyboard').getkeyboard().altkeypopup_namespace ? true : false;
```

**Comment by Chokomoko** [comment]
Thanks a lot!
