### ISSUE TITLE
Not able to get the entered value if user did not click on accept button and click anywhere on the page.

### ISSUE THREAD

**Issue by Bhumika801** [Mottie/Keyboard#716]
we cannot get the value of input field without click on accept button.
**

base.close = function (accepted) {
if (base.isOpen && base.$keyboard.length) {
clearTimeout(base.throttled);
var kbcss = $keyboard.css,
kbevents = $keyboard.events,
//val = accepted ? base.checkCombos() : base.originalContent;
val = base.checkCombos();
// validate input if accepted
if (accepted && $.isFunction(o.validate) && !o.validate(base, val, true)) {
val = base.originalContent;
accepted = false;
if (o.cancelClose) {
return;
}
}

**
This code is in jquery.keyboard.js In the above code firstly the check the accepted value and its set when user click on accept button.
How can manage this from ts?

**Comment by Mottie** [comment]
Hi @Bhumika801!

I'm guessing that the `usePreview` option is set to `true`. If that's the case, then the original input is not updated until after the accept button is used. To get the current value, target the preview input ([demo](http://jsfiddle.net/Mottie/egb3a1sk/6772/)):

```js
$(function() {
  $('#keyboard').keyboard({
    change: function(e, keyboard, el) {
      console.log('current value =', keyboard.preview.value);
    }
  });
});
```

**Comment by Bhumika801** [comment]
Hello @Mottie 

It's working but when we click on outside the input field it's reset the field value. I Don't want to reset the field value when user click on anywhere on the page.

**Comment by Mottie** [comment]
Set the [`autoAccept` option](https://github.com/Mottie/Keyboard/wiki/Usability#autoaccept) to `true`.

**Comment by Bhumika801** [comment]
Thankyou, it's working fine :-)

**Comment by Bhumika801** [comment]
How can I validate two fields at the same time. I mean I have two fields username and password. I want user can accept only if both fields are filled. Can you please help me to solve it?
