### ISSUE TITLE
Get Value/Text via jQuery in multiple input scenario

### ISSUE THREAD

**Issue by lehmann-labs** [Mottie/Keyboard#719]
Hi,

I have multiple text inputs, like:
```
<input id="i1.1" type="text" class="cappentry keyboard-init-focus input-code" maxlength="10"/>
<input id="i1.2" type="text"  class="cappentry input-weight" maxlength="4" />
<input id="i1.3" type="text"  class="cappentry input-weight" maxlength="4" />
...
etc
```

I have following settings for keyboard:
```
stayOpen : true,
alwaysOpen : true,
initialFocus : false,
ignoreEsc : true,
appendTo : 'body',
tabNavigation: true,
appendLocally : true,
usePreview: false,
autoAccept : true,
position: {
   of: $('#keyboard-anchor'),
}
```
I now would like to access the data entered via keyboard, via $("#i1.1").text() or $("#i1.1").val(). But both don't work - either empty or undefined. How can I get the typed in data after user has completed entering multiple inputs?

**Comment by Mottie** [comment]
Hi @lehmann-labs!

Maybe you can use the `hidden` event/callback to each input and check the content of all three to ensure there is no empty value? ([demo](https://jsfiddle.net/Mottie/egb3a1sk/6993/))

```js
$(function() {

  $('input').keyboard({
      layout: 'num',
      tabNavigation: true,
      usePreview: false,
      autoAccept: true,
      hidden: function(e, keyboard, el) {
        var result = [];
      	$('input[id^="i1\."]').each(function(_, elm) {
        	if (elm.value) {
          	result.push(elm.value);
          }
        });
        $('#result').text(result.length === 3 ? result.join(' ') : '');
      },
    })
    // activate the typing extension
    .addTyping({
      showTyping: true,
      delay: 250
    });

});
```

**Comment by lehmann-labs** [comment]
Hi @Mottie, thanks for quick reply - will try that out. My use case goes even further (as I have more then 3 input fields) I would like to give the user the ability to delete individual fields (if input was incorrect) by placing a button at each input. I have to experiment with your solution if then I can delete items :)

**Comment by lehmann-labs** [comment]
Hi! I tried it, thanks it's working for my use case!
I think this was the right snippet as I had an error in my each function - so issue not related to keyboard itself:
```
       $('input[id^="i1."]').each(function(_, elm) {
          if (elm.value) {
            result.push(elm.value);
          }
        });
```
