### ISSUE TITLE
i need help doing a custom layout of the keyboard, i have some code from jsfiddle

### ISSUE THREAD

**Issue by craigdelray** [Mottie/Keyboard#721]
hello all, i need a little bit of help making a custom version of the mottie keyboard. 
All i need is a simple layout like this:

            '1 2 3 4 5 6 7 8 9 0 {space} {bksp}',
            'A B C D E F G H I J K L M',
            'N O P Q R S T U V W X Y Z', 

but it looks like the attached picture.
<img width="432" alt="mottie" src="https://user-images.githubusercontent.com/36866061/51948995-beb67180-23f8-11e9-9a0a-710e9ae4d9e6.png">

But when i do that, the SPACE bar is too big. What i need is 3 equal size rows. A-M and N-Z take up the same screen width, so the top row 1-0 and SPACE/BKSPACE can be correct if i am able to set how wide the spacebar is.

Any ideas? Thanks in advance!!!

, i made this quick edit to the keyboard layout which you can see here by jsfiddle:
/* VIRTUAL KEYBOARD DEMO - https://github.com/Mottie/Keyboard */
/* Use Bootstrap theme */

/* Note: this plugin only requires the jQuery UI position utility
   from the jQuery UI library, UNLESS you position the keyboard
   on your own; then it becomes optional/unneccessary
*/

$(function() {
  $('#summernote')
    .on('summernote.init', initKeyboard)
    .summernote();

  function initKeyboard() {
    $('.note-editable').keyboard({
        layout: 'custom',
        customLayout: {
          'normal': [
            '1 2 3 4 5 6 7 8 9 0 {space} {bksp}',
            'A B C D E F G H I J K L M',
            'N O P Q R S T U V W X Y Z',            
          ],
          'shift': [
            '1 2 3 4 5 6 7 8 9 0 {space} {bksp}',
            'A B C D E F G H I J K L M',
            'N O P Q R S T U V W X Y Z',
          ]
        },
        css: {
          // input & preview
          input: 'form-control input-sm',
          // keyboard container
          container: 'center-block dropdown-menu', // jumbotron
          // default state
          buttonDefault: 'btn btn-default',
          // hovered button
          buttonHover: 'btn-primary',
          // Action keys (e.g. Accept, Cancel, Tab, etc);
          // this replaces "actionClass" option
          buttonAction: 'active',
          // used when disabling the decimal button {dec}
          // when a decimal exists in the input area
          buttonDisabled: 'disabled'
        }
      })
      // activate the typing extension
      .addTyping({
        showTyping: true,
        delay: 50
      });
  }

});

**Comment by Mottie** [comment]
Hi @craigdelray!

The spacebar width is [set in the css](https://github.com/Mottie/Keyboard/blob/master/css/keyboard.css#L41-L43). You can adjust it by adding custom css *after* the loaded keyboard.css file:

```css
.ui-keyboard-space {
	width: 1.5em;
}
```

The [theme wiki page](https://github.com/Mottie/Keyboard/wiki/Theme) goes into a bit more detail on how the class name is generated.
