### ISSUE TITLE
navigation with togglemode: true results in errors when accepted is emitted

### ISSUE THREAD

**Issue by grkblood13** [Mottie/Keyboard#724]
In my keyboard configuration I'm using the navigation extension with togglemode set to true.

$('#keyboard').keyboard({
	position: "center",		
	alwaysOpen: false
}).addNavigation({
	toggleMode: true,
	rowLooping: true
});

When listening for the Enter key to be pressed when hovered class is present I kick of the kb.accept() method.

// submit if virtual enter key is pressed
$.extend($.keyboard.keyaction, {
    enter : function(kb) {
		var _text = kb.$keyboard.find('.ui-state-hover')[0].textContent;
		if (_text == 'Enter') kb.accept();
    }
});

// push keyboard entry to proper field
$('#keyboard').on('accepted',function(e, keyboard, el) {
	closeDialog(); // <- hide div that keyboard is present in
	keyboardElm.val(el.value);
	keyboardElm.focus();
	keyboardElm='';
});

When I do this I get the following error:

jquery.keyboard.extension-navigation.js:120 Uncaught TypeError: base.$keyboard.toggleClass is not a function
    at $.keyboard.base.checkKeys (jquery.keyboard.extension-navigation.js:120)
    at HTMLInputElement.<anonymous> (jquery.keyboard.extension-navigation.js:105)
    at HTMLInputElement.dispatch (jquery-3.2.1.min.js:3)
    at HTMLInputElement.q.handle (jquery-3.2.1.min.js:3)
base.checkKeys @ jquery.keyboard.extension-navigation.js:120
(anonymous) @ jquery.keyboard.extension-navigation.js:105
dispatch @ jquery-3.2.1.min.js:3
q.handle @ jquery-3.2.1.min.js:3

**Comment by Mottie** [comment]
Hi @grkblood13!

Thanks for reporting this issue. I'll look into it.

**Comment by Mottie** [comment]
This doesn't seem to be an issue I can reproduce. Please verify that the `jquery.keyboard.js` file is loaded before the `jquery.keyboard.extension-navigation.js` file in the HTML. If that isn't the issue, then please modify [this demo](https://jsfiddle.net/Mottie/c6ftvy7r/) to show the error.

**Comment by grkblood13** [comment]
I'll get around to modifying that demo within the next week. Sorry it's taking me so long.

**Comment by grkblood13** [comment]
Here ya go: https://jsfiddle.net/7j9gvm8e/
