### ISSUE TITLE
Value is blank when using inside modal

### ISSUE THREAD

**Issue by dianeryanto** [Mottie/Keyboard#729]
Hi i have issue with your great plugin.

i have declare virtual keyboard for all input with class **num**, but the problem is when i use inside the modal.

The value is blank, like this:
![test](https://user-images.githubusercontent.com/33514077/53795796-51e94680-3f65-11e9-98ce-44d867bd8019.gif)

this is my code for class **num**
```
$('.num').keyboard({
        layout: 'custom',
        customLayout: {
            'normal': [
                '6 7 8 9',
                '3 4 5 {clear}',
                '0 1 2 {b}',
                '{accept} {cancel}'
            ]
        },
        css: {
            input: 'form-control input-sm',
            container: 'center-block dropdown-menu',
            buttonDefault: 'btn btn-default',
            buttonHover: 'btn-primary',
            buttonAction: 'active',
            buttonDisabled: 'disabled'
        },
        restrictInput: true,
        preventPaste: true,
        autoAccept: true,
        enterNavigation: true
    }).addTyping();
```

for class **char**
```
$('.char').keyboard({ 
        layout: 'qwerty',
        css: {
            input: 'form-control input-sm',
            container: 'center-block dropdown-menu',
            buttonDefault: 'btn btn-default',
            buttonHover: 'btn-primary',
            buttonAction: 'active',
            buttonDisabled: 'disabled'
        },
        restrictInput: true,
        preventPaste: true,
        autoAccept: true,
        enterNavigation: true 
    }).addTyping();
```

this is my html form:
```
<div class="row">
                            <div class="col-xs-6">
                                <div class="form-group">
                                    <label for="amount">Amount</label>
                                    <input type="text" name="amountPayment" id="amountPayment" maxlength="11" class="form-control num" pattern="^[0-9]+$" required>
                                </div>
                            </div>

                             <div class="col-xs-12" id="inputDetailNo" style="display: none">
                                <div class="form-group">
                                    <label for="detail_info" id="detail_info">Detail Info</label>
                                    <input class="form-control char" type="text" name="card_holder" id="card_holder" maxlength="50" placeholder="Card Name / Voucher Name">
                                </div>

                                <div class="form-group">
                                    <label for="payment_type" id="payment_type">Title Payment</label>
                                    <input class="form-control char" type="text" name="card_no" id="card_no" pattern="^[0-9]+$" maxlength="16" placeholder="Detail Card Number / Voucher">
                                </div>
                            </div>                                    
                        </div>
```

note : outside modal my code is work, but in modal it is become the problem.
Can you tell me whats wrong with my code?

**Comment by Mottie** [comment]
Hi @dianeryanto!

Modals will duplicate the HTML so you'll end up with two inputs with the same ID.

I believe the issue is due to when the keyboard is initialized. It should be initialized *after* the modal has opened, not before. I can't tell what modal library is being used, but if you're using bootstrap then check out issue #462. The demo is also available in the main wiki page under [how to](https://github.com/Mottie/Keyboard/wiki#how-to) (just search for "modal").

If that doesn't help, then please set up a demo to make it easier to troubleshoot the problem.

**Comment by dianeryanto** [comment]
Hi @Mottie, thanks for your response.

Im using modal bootstrap.

this is my full html modal
<div class="modal fade" id="modal-payment">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
        <h4 class="modal-title" id="modal-title">Default Modal</h4>
      </div>

      <form data-toggle="validator" role="form" id="formPayment">
        <div class="modal-body">
          <table class="table table-bordered table-condensed" style="margin-bottom: 0;">
            <tbody>
              <tr>
                <td style="border-right-color: #FFF !important;" width="25%">Total Items</td>
                <td class="text-right" width="25%"><span id="modalTotalItem">0</span></td>
                <td style="border-right-color: #FFF !important;" width="25%">Total Payable</td>
                <td class="text-right" width="25%"><span id="modalTotalPayment">0 (0)</span></td>
              </tr>
              <tr>
                <td style="border-right-color: #FFF !important;">Total Paying</td>
                <td class="text-right"><span id="modalTotalPaying">0</span></td>
                <td style="border-right-color: #FFF !important;">Balance</td>
                <td class="text-right"><span id="modalBalance">0</span></td>
              </tr>
            </tbody>
          </table>

          <div class="row">
            <div class="col-xs-6">
              <div class="form-group">
                <label for="amount">Amount</label>
                <input type="text" name="amountPayment" id="amountPayment" maxlength="11" class="form-control" pattern="^[0-9]+$" required>
              </div>
            </div>

            <div class="col-xs-6">
              <div class="form-group">
                <label for="paid_by">Paying by</label>
                <select id="paid_by" class="form-control" onchange="payment(this.value)">                       
                </select>
              </div>
            </div>

            <div class="col-xs-12" id="inputDetailNo" style="display: none">
              <div class="form-group">
                <label for="detail_info" id="detail_info">Detail Info</label>
                <input class="form-control" type="text" name="card_holder" id="card_holder" maxlength="50" placeholder="Card Name / Voucher Name">
              </div>

              <div class="form-group">
                <label for="payment_type" id="payment_type">Title Payment</label>
                <input class="form-control" type="text" name="card_no" id="card_no" pattern="^[0-9]+$" maxlength="16" placeholder="Detail Card Number / Voucher">
              </div>
            </div>
          </div>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary" id="submitPayment">Pay!</button>
        </div>
      </form>
    </div>
  </div>
</div>


And already follow your tips to define keyboard after modal opened like this

**Comment by Mottie** [comment]
Oh, it might be that the keyboard's "hidden" event is causing the modal to close, or something like that... see https://github.com/Mottie/Keyboard/issues/566#issuecomment-307186165.

**Comment by dianeryanto** [comment]
ok thanks @Mottie, already works perfectly.

But one more question, why my modal ignore my input from keyboard?
