### ISSUE TITLE
Toggle Navigation to keyboard on default.

### ISSUE THREAD

**Issue by chaosmasterro** [Mottie/Keyboard#738]
Hello, this may be a quick solution. I can't find anything on it, but is there a way to enable the toggle navigation to keyboard on default? Sorry, if this has already been answered.

**Comment by Mottie** [comment]
Hi @chaosmasterro!

I'm assuming you mean the toggle of the navigation extension? If so, then set the [`toggleMode` option](https://github.com/Mottie/Keyboard/wiki/Extension-Navigation#togglemode) to `true`:

```js
$('#keyboard')
	.keyboard({
		alwaysOpen: true
	})
	.addNavigation({
    // set start position [row-number, key-index]
		position   : [0,0],
    // true = navigate the virtual keyboard, false = navigate in input/textarea
		toggleMode : true,
    // css class added when toggle mode is on
		focusClass : 'hasFocus'
	});
```

**Comment by chaosmasterro** [comment]
Yes, this was it thank you. I also decided to edit the code to add functionality to add a controller to it and I needed the **base.navigateKeys = function(key, row, indx" ) { ...** to start listening immediately without a key input. I'll put my code here in case someone runs into a similar problem like me. Thanks! 

``base.navigation_init = function() {
			base.$keyboard.toggleClass(o.focusClass, o.toggleMode)
				.find('.' + kbcss.keySet + ':visible')
				.find('.' + kbcss.keyButton + '[data-pos="' + o.position[0] + ',' + o.position[1] + '"]')
				.addClass(opts.css.buttonHover);

			base.$preview
				.unbind(base.navigation_namespace)
				.bind('keydown' + base.navigation_namespace,function(e) {
					return base.checkKeys(e.which);
				});
				//Starts listening for key inputs without pressing a key.
				base.navigateKeys();

		};
