### ISSUE TITLE
Tab Navigation requires double tab press to enable physical keyboard input

### ISSUE THREAD

**Issue by rubenfranca** [Mottie/Keyboard#744]
When using the same keyboard to write on different inputs, combined with `alwaysOpen: true` and `tabNavigation: true`, the navigation is not working as expected. It is required to press the tab key twice in order to write on the input with the physical keyboard. This is only happening on the inputs which have the virtual keyboard.

Steps to reproduce:
1. Click on the first input
2. Press tab
3. Try to write with the physical keyboard (doesn't work)
4. Press tab key again
5. Try to write with the physical keyboard (works)

Here is a demo: [demo](http://jsfiddle.net/7wkuLjzo/7/)

**Comment by Mottie** [comment]
Hi @rubenfranca!

Thanks for the heads-up! I'll get this fixed ASAP!

**Comment by Mottie** [comment]
Try [this demo](https://jsfiddle.net/Mottie/egb3a1sk/7022/):

HTML

```html
  First Name:
  <input type="text" class="keyboard keyboard-init-focus">
  <br/> Last Name:
  <input type="text" class="keyboard">
```

The "keyboard-init-focus" ensures that the indicated input gets focused; but also make sure to set the `initialFocus` option to `false`.

JS
```js
$(function() {
  $('.keyboard').keyboard({
    usePreview: false,
    position: {
    	of: '#wrap',
      my: 'center top',
      at2: 'center bottom',
      offset: '0 20'
    },
    initialFocus: false,
    alwaysOpen: true,
    tabNavigation: true,
    autoAccept: true,
  });
});
```
