### ISSUE TITLE
Keyboard positioning

### ISSUE THREAD

**Issue by zorgoz** [Mottie/Keyboard#745]
I have made a minimal setup based on the playground: https://jsfiddle.net/wcuoLm41/7/
The problem is, that when I transfer this setup in the real environment, de keyboard is shown top-left, and not aligned to the input field. I have the same resources included (`jquery.keyboard.js`, `keyboard-layouts-microsoft.js`, `bootstrap.css`, `jquery-ui.css` and `keyboard.css`). 
I see that in jsfiddle there is `top` and `left` style property set on the keyboard div element. But not in my case. What am I missing?

**Comment by Mottie** [comment]
Hi @zorgoz!

The keyboard relies on [jQuery UI position utility](https://jqueryui.com/position/) to position the keyboard (and autocomplete popup). I've created a [minified custom build](https://github.com/Mottie/Keyboard/blob/master/docs/js/jquery-ui-custom.min.js) using their [download builder](https://jqueryui.com/download/) for the main demo; but it hasn't been updated to work with the latest versions of jQuery.

Alternatively, you can use the provided [basic dark or basic light theme](https://github.com/Mottie/Keyboard/wiki#themes) which uses CSS to position the keyboard at the bottom center of the page.

**Comment by Mottie** [comment]
I added a bit more information on the [FAQ page](https://github.com/Mottie/Keyboard/wiki/FAQ#position-keyboard) based on my above answer.

**Comment by zorgoz** [comment]
Thank you. I have switched to the dark theme, and it looks to be exactly what I need.
