### ISSUE TITLE
Open multiple inputs

### ISSUE THREAD

**Issue by cloudstudio** [Mottie/Keyboard#750]
Hello guys! since we can't use mask by default : https://github.com/Mottie/Keyboard/issues/704

I have another idea, maybe we can open multiple inputs in same modal ? something like this 
![Captura de pantalla 2019-07-10 a las 12 23 24](https://user-images.githubusercontent.com/3589377/60962010-a0d92b00-a30d-11e9-8576-2d5e90eea700.png)

Any idea if this is posible ? thanks !

**Comment by Mottie** [comment]
Hi @cloudstudio!

I don't think that would allow for a very good user experience. I think it would be better to not show the preview input and allow the user to tab between the three inputs - [demo](https://jsfiddle.net/Mottie/egb3a1sk/7035/):

HTML

```html
<div id="wrap">
  <input class="keyboard day" placeholder="dd" type="text" />
  <input class="keyboard month" placeholder="mm" type="text" />
  <input class="keyboard year" placeholder="yyyy" type="text" />
</div>
```

CSS

```css
#wrap {
  display: block;
  margin: 100px auto;
  text-align: center;
}

.keyboard {
  width: 50px;
}
```

JS

```js
$(function() {

  $('.keyboard').keyboard({
      layout: 'num',
      usePreview: false,
      tabNavigation: true,
      position: {
        of: $('#wrap'),
        my: 'center top',
        at: 'center top',
        at2: 'center bottom'
      },
      acceptValid: true,
      validate: function(kb, value, isClosing) {
        if (kb.$el.hasClass('day')) {
          return value > 0 && value <= 31;
        }
        if (kb.$el.hasClass('month')) {
          return value > 0 && value <= 11;
        }
        if (kb.$el.hasClass('year')) {
          return value > 1900 && value <= new Date().getFullYear();
        }
      }
    })
    .addTyping({
      showTyping: true,
      delay: 250
    });
});
```

**Comment by cloudstudio** [comment]
Thanks @Mottie! fast response!

At the moment ( just for design ) I have a big modal, so I need inputs inside modal :(

I thinks is not posible by default right ?

Thanks for you time !

**Comment by Mottie** [comment]
Yes, you can add the keyboard inside of a modal. There's an example in https://github.com/Mottie/Keyboard/issues/462#issuecomment-220790317 showing now to use the keyboard inside of a Bootstrap modal.

**Comment by cloudstudio** [comment]
Hey @Mottie sorry ! when I say modal, I mind in something like first image, inputs inside keyboard :P

I think is not posible right ?

![Captura de pantalla 2019-07-10 a las 12 23 24](https://user-images.githubusercontent.com/3589377/60992184-4dd29880-a34c-11e9-8732-ee7384aa82e0.png)

**Comment by Mottie** [comment]
Sure it's possible, but not practical.

If the keyboard is showing three inputs, are there three separate inputs on page as well? Adding the two extra inputs would require a bunch of custom code to switch between the inputs *within* the keyboard modal, and maintain & update the values in the modal and with the two other inputs (or one input) on the main page. It'll definitely be a lot of code that'll need to be maintained outside of the keyboard plugin versus the simple method I shared in the demo.

**Comment by cloudstudio** [comment]
Yep I understand, but is because design :(

I have 3 separate inputs, year month day, I can do this in only one input, but mask are not working for now.

I only want a date field, yyyy-mm-dd I try to find best way to do this, could be really nice do with masks, but nor posible for now.

So I little lost here, maybe I try to launch "mask" after load keyboard.

I have some open source things and I know answering is a job, thank you for your time.

**Comment by Mottie** [comment]
Sadly masks are not great. First, most are very bad for accessibilty. When you add `-`, `_` or `/` as placeholders, the screen reader reads out *all of them* out loud - watch the video in the [politespace repo](https://github.com/filamentgroup/politespace#beware-input-masks) to see what I mean.

Secondly, when a mask is being used, it takes over control of the caret position. For example, adding a `-` after you finish entering `2019` for the year. This keyboard library is also controlling the caret position, so there is a conflict that usually makes the caret not end up where you expect.

**Comment by cloudstudio** [comment]
I see, well but mask discarded.

I need then to get the 3 inputs inside the keyboard as in the image.

Wish me luck!

Thank you.
