### ISSUE TITLE
Controlling keyboard using a Gamepad

### ISSUE THREAD

**Issue by Cypaubr** [Mottie/Keyboard#760]
Hello,
I wondered if it is possible to control the keyboard (using navigation or not) with a gamepad. I tried to map Gamepad inputs to keyboard events but it does not work.

Cheers

**Comment by Mottie** [comment]
Hi @Cypaubr!

I'm guessing you mean Gamepad? If you can't use the navigation extension to remap the keys, then maybe you need to use the [Gamepad API](https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API)? Then, in the controller event functions, you can use the navigation extension built-in [navigation methods](https://github.com/Mottie/Keyboard/wiki/Extension-Navigation#navigation-methods).

**Comment by Cypaubr** [comment]
My bad for the typo. Yes this is what I needed. But I have an issue, not when I hit Accept, the value of my <input> is not updated with the entered value.

**Comment by Mottie** [comment]
Try using the [`change` callback](https://github.com/Mottie/Keyboard/wiki/Methods#change).
