### ISSUE TITLE
How to use keyboard without textfield?

### ISSUE THREAD

**Issue by mKliver** [Mottie/Keyboard#775]
In this demo https://jsfiddle.net/Mottie/egb3a1sk/ keyboard appears on button click. And here  is textfield that keyboard bounds. 
How can i do not show this field on page, but show it in preview in keyboard popup?

I tried to set `visibility: hidden; ` to text filed but in this case it not shown in keyboard popup.

**Comment by Mottie** [comment]
Hi @mKliver!

Please see the "Custom: hidden" example in the [main demo page](https://mottie.github.io/Keyboard/). Click on that header and scroll down to see the code example.

**Comment by mKliver** [comment]
I complitly blind. Thansk man.
