### ISSUE TITLE
Wrong Position of Keyboard

### ISSUE THREAD

**Issue by pilz97** [Mottie/Keyboard#777]
Hello,

I just added this awesome keyboard to my project.
But i have one problem:
When I open the keyboard it fully overlays over my input..
![image](https://user-images.githubusercontent.com/42172207/78247102-8d4ca080-74ea-11ea-903d-db3b43eace43.png)

Does anyone know what could cause this behaviour?

**Comment by Mottie** [comment]
Hi @pilz97!

The positioning is accomplished internally using jQuery UI's position utility ([docs](https://github.com/Mottie/Keyboard/wiki/Layout#position). It's completely optional and you could position the keyboard at the bottom of the page using css only - see the light & dark [theme demos](https://github.com/Mottie/Keyboard/wiki#themes).

**Comment by pilz97** [comment]
@Mottie firstly I want to thank you for the fast answer!

I don't want the keyboard to be placed on the bottom, i want that it is placed directly over or under the input, is this also possible (i have set the usePreview flag to false).

**Comment by Mottie** [comment]
I've noticed that the jQuery UI doesn't work well with the latest jQuery version; but luckily you can [download _just_ the position utility](https://jqueryui.com/download/#!version=1.12.1&components=010000000000000000000000000000000000000000000000). Look at the available options to determine where you want to position the keyboard.

Alternatively, you don't have to set the `position` option, and instead use the [`visible` event](https://github.com/Mottie/Keyboard/wiki/Methods#events) to position the keyboard using a different library, like [popper.js](https://popper.js.org/).

**Comment by pilz97** [comment]
@Mottie thank you so much for your support, i got it to work with propper.js 💯 🥇 👍
