### ISSUE TITLE
French translation mistake

### ISSUE THREAD

**Issue by fbenedetti06** [Mottie/Keyboard#781]
In file "fr.min.js" :
- alt:"AltGr:Charactère alternatif"
must be :
+ alt:"AltGr:Caractère alternatif"
(there is no 'h' here in my mother tongue language!)
It is for tooltip when mouse is over the key...

**Comment by Mottie** [comment]
Hi @fbenedetti06!

Thanks for the correction! I'll get it fixed ASAP.
