### ISSUE TITLE
How get EC2 instance list created by AWS user, AWS CLI

### ISSUE THREAD

**Issue by amittrivedinew** [Mottie/Keyboard#784]
I have an AWS account, in which i have created an OU (Organizational Unit) & we have created many users inside this OU. Now we would like to list the instances, created by these users. 
If you could do a favor in this cause i shall be highly obliged to you. 
Thanks in advance

**Comment by Mottie** [comment]
Hi @amittrivedinew!

Try asking this question on https://stackoverflow.com/, this Keyboard library has nothing to do with AWS.
