### ISSUE TITLE
Automatically opening keyboard

### ISSUE THREAD

**Issue by oscardimanno** [Mottie/Keyboard#797]
Hi, thanks for this useful library.

I'm having a problem, i'm using this keyboard in a form with some required input fields. When i have empty fields and i submit the form the keyboard will automatically open, and i don't want this. There are a parameter to setup this?

**Comment by Mottie** [comment]
Hi @oscardimanno!

The [`openOn` option](https://github.com/Mottie/Keyboard/wiki/Usability#openon) is set to `'focus'` by default. I'm not sure how empty fields would cause the keyboard to open unless you have something in your code that focuses those inputs. Validation code maybe?
