### ISSUE TITLE
Gujarati

### ISSUE THREAD

**Issue by tejastank** [Mottie/Keyboard#80]
Unable to work with gujarati or hindi launaguage support.

even not working with different lanugages./..

**Comment by Mottie** [comment]
In the last update, I added the converted keyboard layouts from greywyvern.com ([demo](http://mottie.github.io/Keyboard/layouts2.html)) which also includes a version of the Hindi & Gujarati keyboard layouts.

**Comment by durga598** [comment]
Hi @Mottie, have you added layouts from this [ascii-table-site](http://ascii-table.com/keyboards.php)? There is a letter missing in oriya layout, can I add that in [ms-Oriya.js](https://github.com/Mottie/Keyboard/blob/master/layouts/ms-Oriya.js) ?

**Comment by Mottie** [comment]
Hi @durga598!

The `ms-` prefix actually means that the source of that layout is from Microsoft - here's an updated page: https://docs.microsoft.com/en-us/globalization/windows-keyboard-layouts; the Oriya layout is listed as [Odia](https://docs.microsoft.com/en-us/globalization/keyboards/kbdinori.html).

There may have been some issues in the extraction & building process, so if you see an error, then yes please help me fix it. 😸

**Comment by durga598** [comment]
@Mottie , see in that [layout](https://docs.microsoft.com/en-in/globalization/keyboards/kbdinori.html) in between `right shift` key and `.` there is a letter `ୟ` is present while in generated layout that replaced by `/` in [ms-Oriya.js](https://github.com/Mottie/Keyboard/blob/master/layouts/ms-Oriya.js). So where and how to edit the file?

**Comment by Mottie** [comment]
You should be able to do everything from GitHub's interface.

* Go to: https://github.com/Mottie/Keyboard/blob/master/layouts/ms-Oriya.js
* Click the edit button. This should open the file in an editor.
* I haven't done this in a while, but I think saving causes the repo to become forked into your account. From there, open a pull request.
