### ISSUE TITLE
Prevent empty input

### ISSUE THREAD

**Issue by GenijeOnline** [Mottie/Keyboard#800]
Hello.
I'm trying to prevent input of blank field but only at begining of text (_blank_ + accept to enter text) and repeated space in text (example: "_Text blank blank blank_...+accept") on virtual keyboard. 
My idea is to implement something like this https://stackoverflow.com/questions/48714579/how-do-i-prevent-a-leading-space-from-being-entered-in-a-textbox but for now with no success. It's working on phisical keyboard but not on virtual.
Can you please help me with this?

**Comment by Mottie** [comment]
Hi @GenijeOnline!

Try this code ([demo](https://jsfiddle.net/Mottie/537kp6xs/)):

```js
$(function() {
  $('#keyboard').keyboard({
    beforeInsert: function(e, keyboard, el, textToAdd) {
      return keyboard.caret().start === 0 && textToAdd.trim() === ''
        ? ''
        : textToAdd;
    }
  });
});
```

**Comment by GenijeOnline** [comment]
Yes! That's it.. Thank you Mottie.
