### ISSUE TITLE
Keyboard's value doesn't get updated programmatically and it closes as well

### ISSUE THREAD

**Issue by sajalsuraj** [Mottie/Keyboard#809]
Hi,

I am using this keyboard in an Angular project, my requirement is to update the keyboard value programmatically, but the moment value reaches the point, the keyboard got closed. This happens when the angular page/component is navigated more than once.

This is the function that I wrote to update the value -

```
addNewScannedValue(val){
    var keyboard = $('.input-keyboard').getkeyboard();
    var k = keyboard
      .reveal()
      .setValue(val)
      .$el.trigger('change');
  }
```

Value doesn't get updated on the keyboard and the keyboard closes automatically. Please help me. @Mottie

**Comment by contra8** [comment]
Which version of Angular are you using? The latest, Angular 12?

**Comment by sajalsuraj** [comment]
@contra8 I am using Angular 8.

**Comment by sajalsuraj** [comment]
I have resolved this problem. I have removed the keyboard events such as getKeyboard() and reveal() and just using "keyboard.$preview.focus()". This resolved my issue. Closing this issue for now.
