### ISSUE TITLE
How can I get the keyboard to start Shifted?

### ISSUE THREAD

**Issue by bencrundwell** [Mottie/Keyboard#81]
I'm using the keyboard to add comments to a thread and personally hate it when poeple dont capitalise the first letter of a sentence.

How can I make the keyboard start up shitfted? Like it does on my Android phone and autoshift after a full stop '.' ?

**Comment by Suka1215** [comment]
Clicking shift changes keyboard to all caps then right back to lower case?

**Comment by ninapavlich** [comment]
A couple improvements to the logic:
- Include other sentence-ending punctuation (! and ?)
- Automatically un-capitalize as the user types.
- Don't capitalize if there is text already in the text box.

        $('#keyboard').keyboard({
            visible: function(e, kb, el) {
                autoshift_keyboard(kb, el);
            },
            change: function(e, kb, el) {
                autoshift_keyboard(kb, el);
            }
        });

        function autoshift_keyboard(keyboard, element){
            var caret = keyboard.$preview.caret();
            var end = caret.end - 2 >= 0 ? caret.end - 2 : caret.end;
            
            // find the two characters immediately to the left of the caret
            var str = keyboard.$preview.val().substring(end, caret.end);

            // start with shifted key set showing
            var is_at_beginning = keyboard.$preview.caret().start === 0;
            var is_at_new_sentence = str.indexOf('. ') >= 0 || str.indexOf('! ') >= 0 || str.indexOf('? ') >= 0;
            if (is_at_beginning || is_at_new_sentence) {
                keyboard.shiftActive = true;
                keyboard.showKeySet(element);
            }else{
                keyboard.shiftActive = false;
                keyboard.showKeySet(element);
            }
        }

**Comment by ninapavlich** [comment]
A couple improvements to the logic:
- Automatically un-capitalize as the user types.
- Also include ! and ? as sentence enders.
- Don't capitalize if text box already has text in it.

        $('#keyboard').keyboard({
            visible: function(e, kb, el) {
                autoshift_keyboard(kb, el);
            },
            change: function(e, kb, el) {
                autoshift_keyboard(kb, el);
            }
        });

        function autoshift_keyboard(keyboard, element){
            var caret = keyboard.$preview.caret();
            var end = caret.end - 2 >= 0 ? caret.end - 2 : caret.end;
            
            // find the two characters immediately to the left of the caret
            var str = keyboard.$preview.val().substring(end, caret.end);

            // start with shifted key set showing
            var is_at_beginning = keyboard.$preview.caret().start === 0;
            var is_at_new_sentence = str.indexOf('. ') >= 0 || str.indexOf('! ') >= 0 || str.indexOf('? ') >= 0;
            if (is_at_beginning || is_at_new_sentence) {
                keyboard.shiftActive = true;
                keyboard.showKeySet(element);
            }else{
                keyboard.shiftActive = false;
                keyboard.showKeySet(element);
            }
        }
