### ISSUE TITLE
Drag/Drop Keyboard to Desired poition

### ISSUE THREAD

**Issue by nagamounika1513** [Mottie/Keyboard#828]
Hii,

I have a requirement to allow users to dynamically move the virtual keyboard to their desired position by dragging it across the screen. How can I make the virtual keyboard draggable to the desired position without hardcoding the keyboard's position?

How can I move the keyboard to the desired position (top, left, bottom, or right) using mouse?

Any help will be very much appreciated.
Thanks in Advance

**Comment by Mottie** [comment]
[Check out the wiki page](https://github.com/Mottie/Keyboard/wiki#layout)
